import {
  DEFAULT_APPEARANCE_SETTINGS,
  normalizeAppearanceSettings,
  type AppearanceSettings,
} from "@/lib/appearance";

export type ThemePreset = {
  /** Stable identifier used for matching the active preset. */
  id: string;
  /** Latin name (kept for reference / analytics). */
  name: string;
  /** Arabic label shown in the UI. */
  label: string;
  /** Full appearance palette applied when the preset is selected. */
  colors: AppearanceSettings;
};

/**
 * Ready-made theme presets for "الإعدادات → مظهر الموقع → الثيمات الجاهزة".
 *
 * Every preset is just a complete {@link AppearanceSettings} palette, so it
 * reuses the exact same theming pipeline already in place
 * (appearanceCssVariables -> ThemeVariables -> CSS variables). No layout,
 * spacing, fonts or component structure is touched — only colors.
 *
 * "Classic AJN" intentionally mirrors {@link DEFAULT_APPEARANCE_SETTINGS} so it
 * doubles as the default/restore theme and is highlighted as active on a fresh
 * install.
 */
export const THEME_PRESETS: ThemePreset[] = [
  {
    // الافتراضي الحالي — ثيم فاتح عصري (أردوازي + مرجاني)
    id: "slate-coral",
    name: "Slate & Coral",
    label: "أردوازي ومرجاني (افتراضي)",
    colors: { ...DEFAULT_APPEARANCE_SETTINGS },
  },
  {
    // الثيم الأصلي محفوظ كخيار بضغطة واحدة للرجوع إليه متى شئت
    id: "classic-ajn",
    name: "Classic AJN",
    label: "AJN الكلاسيكي (أسود وذهبي)",
    colors: {
      background: "#0B0B12",
      header: "#12131A",
      footer: "#12131A",
      sidebar: "#12131A",
      primaryButton: "#D4B15A",
      secondaryButton: "#12131A",
      headings: "#FFFFFF",
      text: "#FFFFFF",
      cards: "#1A1C25",
      links: "#D4B15A",
      hover: "#E7D6A0",
      headingFont: "Cairo",
      bodyFont: "Cairo",
      baseFontPx: 16,
    },
  },
  {
    id: "concept-01-apple-calm",
    name: "Apple Quiet Luxury",
    label: "01 Apple Calm",
    colors: {
      background: "#F5F5F7",
      header: "#FFFFFF",
      footer: "#ECECF0",
      sidebar: "#FFFFFF",
      primaryButton: "#1D1D1F",
      secondaryButton: "#E8E8ED",
      headings: "#121214",
      text: "#2D2D31",
      cards: "#FFFFFF",
      links: "#9A7428",
      hover: "#C7A049",
    },
  },
  {
    id: "concept-02-linear-ops",
    name: "Linear Operations",
    label: "02 Linear Ops",
    colors: {
      background: "#080A0F",
      header: "#0B0D13",
      footer: "#080A0F",
      sidebar: "#0F121A",
      primaryButton: "#8B8CFF",
      secondaryButton: "#191D2A",
      headings: "#F4F6FF",
      text: "#DDE2F2",
      cards: "#11141D",
      links: "#B6B7FF",
      hover: "#8B8CFF",
    },
  },
  {
    id: "concept-03-stripe-commerce",
    name: "Stripe Commerce",
    label: "03 Stripe Commerce",
    colors: {
      background: "#F6F7FB",
      header: "#FFFFFF",
      footer: "#EDF0F8",
      sidebar: "#FFFFFF",
      primaryButton: "#625BFF",
      secondaryButton: "#E7E9F7",
      headings: "#121631",
      text: "#303650",
      cards: "#FFFFFF",
      links: "#625BFF",
      hover: "#7A73FF",
    },
  },
  {
    id: "concept-04-nike-editorial",
    name: "Nike Editorial Energy",
    label: "04 Nike Energy",
    colors: {
      background: "#080808",
      header: "#050505",
      footer: "#080808",
      sidebar: "#111111",
      primaryButton: "#F4F0E8",
      secondaryButton: "#222222",
      headings: "#FFFFFF",
      text: "#E9E4DC",
      cards: "#111111",
      links: "#D4AF37",
      hover: "#D4AF37",
    },
  },
  {
    id: "concept-05-adidas-grid",
    name: "Adidas Modular Grid",
    label: "05 Modular Grid",
    colors: {
      background: "#F2EEE5",
      header: "#0E0E0D",
      footer: "#0E0E0D",
      sidebar: "#161613",
      primaryButton: "#0E0E0D",
      secondaryButton: "#E2DACD",
      headings: "#11110F",
      text: "#2F2B24",
      cards: "#FFFDF7",
      links: "#B08A2E",
      hover: "#D4AF37",
    },
  },
  {
    id: "concept-06-luxury-boutique",
    name: "Luxury Boutique",
    label: "06 Luxury Boutique",
    colors: {
      background: "#F6EFE4",
      header: "#FFFAF1",
      footer: "#EADCC8",
      sidebar: "#FFF7EA",
      primaryButton: "#B9892D",
      secondaryButton: "#EADCC8",
      headings: "#251C14",
      text: "#3B3027",
      cards: "#FFFAF1",
      links: "#9F7224",
      hover: "#CFA34D",
    },
  },
  {
    id: "concept-07-dark-premium",
    name: "Dark Premium",
    label: "07 Dark Premium",
    colors: {
      background: "#070707",
      header: "#0B0B0C",
      footer: "#070707",
      sidebar: "#121214",
      primaryButton: "#E0B84C",
      secondaryButton: "#1F2024",
      headings: "#F7F0E4",
      text: "#E4DED4",
      cards: "#131417",
      links: "#E0B84C",
      hover: "#F1C85A",
    },
  },
  {
    id: "concept-08-editorial-magazine",
    name: "Editorial Magazine",
    label: "08 Editorial",
    colors: {
      background: "#F8F5EF",
      header: "#F8F5EF",
      footer: "#E8E0D2",
      sidebar: "#201B16",
      primaryButton: "#15120F",
      secondaryButton: "#E7DED0",
      headings: "#15120F",
      text: "#342D26",
      cards: "#FFFDF9",
      links: "#9C6B24",
      hover: "#C89B3C",
    },
  },
  {
    id: "concept-09-neo-brutal",
    name: "Neo Brutalism",
    label: "09 Neo Brutal",
    colors: {
      background: "#FFF3BF",
      header: "#FFFBEB",
      footer: "#111111",
      sidebar: "#111111",
      primaryButton: "#FF4D00",
      secondaryButton: "#FFE15D",
      headings: "#0A0A0A",
      text: "#181818",
      cards: "#FFFFFF",
      links: "#0B5FFF",
      hover: "#FF4D00",
    },
  },
  {
    id: "concept-10-glass-premium",
    name: "Glass Premium",
    label: "10 Glass Premium",
    colors: {
      background: "#EDF4F7",
      header: "#F8FCFF",
      footer: "#DCE9EF",
      sidebar: "#F8FCFF",
      primaryButton: "#B9974A",
      secondaryButton: "#DDEAF0",
      headings: "#17242A",
      text: "#30444D",
      cards: "#FFFFFF",
      links: "#8E6D25",
      hover: "#B9974A",
    },
  },
  {
    id: "concept-11-concierge-premium",
    name: "Concierge Premium",
    label: "11 Concierge",
    colors: {
      background: "#0D0B09",
      header: "#13100D",
      footer: "#0D0B09",
      sidebar: "#17120E",
      primaryButton: "#D4AF37",
      secondaryButton: "#241B13",
      headings: "#F7EFE2",
      text: "#E6D8C5",
      cards: "#17120E",
      links: "#E4C463",
      hover: "#D4AF37",
    },
  },
  {
    id: "concept-12-spatial-3d",
    name: "Spatial 3D Commerce",
    label: "12 Spatial 3D",
    colors: {
      background: "#0B1020",
      header: "#0E1428",
      footer: "#0B1020",
      sidebar: "#111936",
      primaryButton: "#7DD3FC",
      secondaryButton: "#1B2547",
      headings: "#F0F7FF",
      text: "#D8E7F8",
      cards: "#111936",
      links: "#BAE6FD",
      hover: "#7DD3FC",
    },
  },
  {
    id: "concept-13-calligraphy-luxury",
    name: "Arabic Calligraphy Luxury",
    label: "13 Calligraphy",
    colors: {
      background: "#0A0704",
      header: "#120D07",
      footer: "#0A0704",
      sidebar: "#171008",
      primaryButton: "#C29A3D",
      secondaryButton: "#2A1D0F",
      headings: "#FFF4D9",
      text: "#EBDDCA",
      cards: "#171008",
      links: "#E2BC65",
      hover: "#C29A3D",
    },
  },
  {
    id: "concept-14-fashion-mono",
    name: "High Fashion Monochrome",
    label: "14 Fashion Mono",
    colors: {
      background: "#F7F7F5",
      header: "#FFFFFF",
      footer: "#111111",
      sidebar: "#111111",
      primaryButton: "#111111",
      secondaryButton: "#E8E8E4",
      headings: "#080808",
      text: "#242424",
      cards: "#FFFFFF",
      links: "#6F6F6F",
      hover: "#111111",
    },
  },
  {
    id: "concept-15-warm-marketplace",
    name: "Warm Marketplace",
    label: "15 Warm Market",
    colors: {
      background: "#FFF3E4",
      header: "#FFF8EF",
      footer: "#E7C9A6",
      sidebar: "#2B1B11",
      primaryButton: "#B87333",
      secondaryButton: "#EED6BD",
      headings: "#2A1A11",
      text: "#493326",
      cards: "#FFFDF8",
      links: "#9E5F27",
      hover: "#B87333",
    },
  },
  {
    id: "concept-16-cyber-luxe",
    name: "Cyber Luxe",
    label: "16 Cyber Luxe",
    colors: {
      background: "#05070B",
      header: "#071018",
      footer: "#05070B",
      sidebar: "#0A111A",
      primaryButton: "#D4AF37",
      secondaryButton: "#0F2430",
      headings: "#F3FBFF",
      text: "#D7EAF0",
      cards: "#0A111A",
      links: "#38D9C8",
      hover: "#38D9C8",
    },
  },
  {
    id: "concept-17-calm-erp",
    name: "Calm SaaS ERP",
    label: "17 Calm ERP",
    colors: {
      background: "#F4F1EC",
      header: "#FAF8F3",
      footer: "#E5DED2",
      sidebar: "#2A2D2C",
      primaryButton: "#6B705C",
      secondaryButton: "#E1D9CC",
      headings: "#1E211F",
      text: "#3B3F3C",
      cards: "#FFFEFA",
      links: "#7A6843",
      hover: "#6B705C",
    },
  },
  {
    id: "concept-18-cinematic-wedding",
    name: "Cinematic Wedding",
    label: "18 Wedding",
    colors: {
      background: "#160D0A",
      header: "#1D110D",
      footer: "#160D0A",
      sidebar: "#261610",
      primaryButton: "#E2B15A",
      secondaryButton: "#352017",
      headings: "#FFF0E0",
      text: "#F1D8C1",
      cards: "#261610",
      links: "#F0C77A",
      hover: "#E2B15A",
    },
  },
  {
    id: "concept-19-artisan-heritage",
    name: "Artisan Heritage",
    label: "19 Heritage",
    colors: {
      background: "#F1E5D1",
      header: "#FFF4DF",
      footer: "#D7B78C",
      sidebar: "#302116",
      primaryButton: "#8B5E34",
      secondaryButton: "#DEC39E",
      headings: "#2F2117",
      text: "#4D392A",
      cards: "#FFF8EA",
      links: "#7A4F2B",
      hover: "#B5793F",
    },
  },
  {
    id: "concept-20-mobile-minimal",
    name: "Ultra Minimal Mobile",
    label: "20 Mobile Minimal",
    colors: {
      background: "#FCFBF8",
      header: "#FFFFFF",
      footer: "#F0EDE6",
      sidebar: "#FFFFFF",
      primaryButton: "#0B0B0B",
      secondaryButton: "#ECE8DF",
      headings: "#0B0B0B",
      text: "#2C2A26",
      cards: "#FFFFFF",
      links: "#B08A2E",
      hover: "#D4AF37",
    },
  },
  {
    id: "ajn-premium",
    name: "AJN Premium",
    label: "AJN بريميوم",
    colors: {
      background: "#0B0B0D",
      header: "#0B0B0D",
      footer: "#0B0B0D",
      sidebar: "#141417",
      primaryButton: "#E5C158",
      secondaryButton: "#1F1F24",
      headings: "#F5F0E6",
      text: "#E8E3D8",
      cards: "#15151A",
      links: "#E5C158",
      hover: "#E5C158",
    },
  },
  {
    id: "luxury-gold",
    name: "Luxury Gold",
    label: "الذهبي الفاخر",
    colors: {
      background: "#0A0A0A",
      header: "#100D06",
      footer: "#100D06",
      sidebar: "#15110A",
      primaryButton: "#D4AF37",
      secondaryButton: "#2A2310",
      headings: "#F7E9C2",
      text: "#EFE6D2",
      cards: "#15110A",
      links: "#E6C66A",
      hover: "#E6C66A",
    },
  },
  {
    id: "royal-blue",
    name: "Royal Blue",
    label: "الأزرق الملكي",
    colors: {
      background: "#0A0F1F",
      header: "#0A0F1F",
      footer: "#0A0F1F",
      sidebar: "#0F1730",
      primaryButton: "#3B82F6",
      secondaryButton: "#15203B",
      headings: "#EAF1FF",
      text: "#DCE6F7",
      cards: "#0F1730",
      links: "#6BA6FF",
      hover: "#3B82F6",
    },
  },
  {
    id: "midnight-black",
    name: "Midnight Black",
    label: "أسود منتصف الليل",
    colors: {
      background: "#050505",
      header: "#050505",
      footer: "#050505",
      sidebar: "#0D0D0D",
      primaryButton: "#4B5563",
      secondaryButton: "#161616",
      headings: "#ECECEC",
      text: "#D6D6D6",
      cards: "#0D0D0D",
      links: "#9CA3AF",
      hover: "#6B7280",
    },
  },
  {
    id: "emerald-green",
    name: "Emerald Green",
    label: "الأخضر الزمردي",
    colors: {
      background: "#07140F",
      header: "#07140F",
      footer: "#07140F",
      sidebar: "#0B1F17",
      primaryButton: "#10B981",
      secondaryButton: "#103026",
      headings: "#E6FFF4",
      text: "#D2F1E5",
      cards: "#0B1F17",
      links: "#34D399",
      hover: "#10B981",
    },
  },
  {
    id: "rose-gold",
    name: "Rose Gold",
    label: "الذهبي الوردي",
    colors: {
      background: "#14100F",
      header: "#14100F",
      footer: "#14100F",
      sidebar: "#1E1614",
      primaryButton: "#B76E79",
      secondaryButton: "#2A1E1C",
      headings: "#FBEDEA",
      text: "#F0DEDA",
      cards: "#1E1614",
      links: "#D49AA0",
      hover: "#B76E79",
    },
  },
  {
    id: "modern-gray",
    name: "Modern Gray",
    label: "الرمادي العصري",
    colors: {
      background: "#111315",
      header: "#111315",
      footer: "#111315",
      sidebar: "#1A1D21",
      primaryButton: "#64748B",
      secondaryButton: "#232830",
      headings: "#F1F5F9",
      text: "#D9DEE6",
      cards: "#1A1D21",
      links: "#94A3B8",
      hover: "#64748B",
    },
  },
  {
    id: "deep-purple",
    name: "Deep Purple",
    label: "البنفسجي العميق",
    colors: {
      background: "#0F0A18",
      header: "#0F0A18",
      footer: "#0F0A18",
      sidebar: "#170F26",
      primaryButton: "#8B5CF6",
      secondaryButton: "#221836",
      headings: "#F1EAFF",
      text: "#DED3F2",
      cards: "#170F26",
      links: "#A78BFA",
      hover: "#8B5CF6",
    },
  },
  {
    id: "ocean-blue",
    name: "Ocean Blue",
    label: "أزرق المحيط",
    colors: {
      background: "#07131A",
      header: "#07131A",
      footer: "#07131A",
      sidebar: "#0B1E2A",
      primaryButton: "#0EA5E9",
      secondaryButton: "#103040",
      headings: "#E4F6FF",
      text: "#CDEAF7",
      cards: "#0B1E2A",
      links: "#38BDF8",
      hover: "#0EA5E9",
    },
  },
  {
    id: "soft-pink",
    name: "Soft Pink",
    label: "الوردي الناعم",
    colors: {
      background: "#FFF5F8",
      header: "#FFFFFF",
      footer: "#FFF0F5",
      sidebar: "#FFE9F1",
      primaryButton: "#EC4899",
      secondaryButton: "#FBD7E7",
      headings: "#4A1730",
      text: "#5A2540",
      cards: "#FFFFFF",
      links: "#DB2777",
      hover: "#EC4899",
    },
  },
  {
    id: "dark-red",
    name: "Dark Red",
    label: "الأحمر الداكن",
    colors: {
      background: "#140707",
      header: "#140707",
      footer: "#140707",
      sidebar: "#1F0C0C",
      primaryButton: "#DC2626",
      secondaryButton: "#301212",
      headings: "#FFEAEA",
      text: "#F2D6D6",
      cards: "#1F0C0C",
      links: "#F87171",
      hover: "#DC2626",
    },
  },
  {
    id: "coffee-brown",
    name: "Coffee Brown",
    label: "البني القهوة",
    colors: {
      background: "#14100B",
      header: "#14100B",
      footer: "#14100B",
      sidebar: "#1E1812",
      primaryButton: "#B5793F",
      secondaryButton: "#2C2016",
      headings: "#F3E7D8",
      text: "#E4D5C2",
      cards: "#1E1812",
      links: "#C99A66",
      hover: "#B5793F",
    },
  },
  {
    id: "silver-night",
    name: "Silver Night",
    label: "ليلة فضية",
    colors: {
      background: "#0C0E12",
      header: "#0C0E12",
      footer: "#0C0E12",
      sidebar: "#14171D",
      primaryButton: "#C0C0C0",
      secondaryButton: "#1E222A",
      headings: "#F4F6FA",
      text: "#D7DCE4",
      cards: "#14171D",
      links: "#CBD5E1",
      hover: "#C0C0C0",
    },
  },
  {
    id: "elegant-white",
    name: "Elegant White",
    label: "الأبيض الأنيق",
    colors: {
      background: "#FAFAFA",
      header: "#FFFFFF",
      footer: "#F4F4F5",
      sidebar: "#FFFFFF",
      primaryButton: "#C9A84C",
      secondaryButton: "#ECECEC",
      headings: "#1A1A1A",
      text: "#2A2A2A",
      cards: "#FFFFFF",
      links: "#B08A2E",
      hover: "#C9A84C",
    },
  },
  {
    id: "sunset-orange",
    name: "Sunset Orange",
    label: "برتقالي الغروب",
    colors: {
      background: "#160C06",
      header: "#160C06",
      footer: "#160C06",
      sidebar: "#21130A",
      primaryButton: "#F97316",
      secondaryButton: "#321B0E",
      headings: "#FFEEDD",
      text: "#F6DCC6",
      cards: "#21130A",
      links: "#FB923C",
      hover: "#F97316",
    },
  },
  {
    id: "turquoise",
    name: "Turquoise",
    label: "التركواز",
    colors: {
      background: "#061413",
      header: "#061413",
      footer: "#061413",
      sidebar: "#0A201E",
      primaryButton: "#14B8A6",
      secondaryButton: "#0F302C",
      headings: "#E2FFFB",
      text: "#CDF3EE",
      cards: "#0A201E",
      links: "#2DD4BF",
      hover: "#14B8A6",
    },
  },
  {
    id: "premium-black",
    name: "Premium Black",
    label: "الأسود البريميوم",
    colors: {
      background: "#000000",
      header: "#000000",
      footer: "#000000",
      sidebar: "#0A0A0A",
      primaryButton: "#FFFFFF",
      secondaryButton: "#141414",
      headings: "#FFFFFF",
      text: "#E5E5E5",
      cards: "#0A0A0A",
      links: "#FFFFFF",
      hover: "#D4D4D4",
    },
  },
  {
    id: "forest-green",
    name: "Forest Green",
    label: "أخضر الغابة",
    colors: {
      background: "#0A130C",
      header: "#0A130C",
      footer: "#0A130C",
      sidebar: "#101E13",
      primaryButton: "#22C55E",
      secondaryButton: "#16301E",
      headings: "#E8F7EC",
      text: "#D2EBD8",
      cards: "#101E13",
      links: "#4ADE80",
      hover: "#22C55E",
    },
  },
  {
    id: "golden-luxury",
    name: "Golden Luxury",
    label: "الذهب الفخم",
    colors: {
      background: "#0B0A06",
      header: "#0B0A06",
      footer: "#0B0A06",
      sidebar: "#14110A",
      primaryButton: "#E8B923",
      secondaryButton: "#2A2412",
      headings: "#FBF1D4",
      text: "#EFE2BE",
      cards: "#14110A",
      links: "#F4D27A",
      hover: "#E8B923",
    },
  },
];

/**
 * Returns the id of the preset whose palette matches the given appearance
 * settings exactly (after normalization), or null when the palette is custom.
 */
export function matchPresetId(appearance: unknown): string | null {
  const current = normalizeAppearanceSettings(appearance);
  for (const preset of THEME_PRESETS) {
    const palette = normalizeAppearanceSettings(preset.colors);
    const isMatch = (Object.keys(palette) as Array<keyof AppearanceSettings>).every(
      (key) => palette[key] === current[key],
    );
    if (isMatch) return preset.id;
  }
  return null;
}
