import { useQuery } from "@tanstack/react-query";
import { CalendarDays, MapPin, Phone, Printer } from "lucide-react";
import type { KoshaManagerBooking, KoshaManagerDetail } from "@/lib/kosha-manager-contract";
import { bookingIdentity, displayEventDate, displayEventTime, sourceQuery } from "@/lib/kosha-manager";
import { adminFetch, formatCurrency } from "@/views/admin/_lib";
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from "@/components/ui/sheet";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { BookingThermalPrintAction } from "@/components/booking-thermal-print";
import { KoshaThumbnail, PaymentStatusBadge, BookingStatusBadge } from "./booking-presentation";
import { StaffExecutionPanel } from "./staff-execution-panel";

export const managerDetailQuery=(b:Pick<KoshaManagerBooking,"id"|"source">)=>({queryKey:["admin","kosha-manager","detail",bookingIdentity(b)],queryFn:()=>adminFetch<KoshaManagerDetail>(`/admin/kosha-bookings/${b.id}/manager-view?${sourceQuery(b)}`)});
export function BookingQuickView({booking,onClose,onEdit,onFull}:{booking:KoshaManagerBooking;onClose:()=>void;onEdit:(b:KoshaManagerBooking)=>void;onFull:(b:KoshaManagerBooking)=>void}) {
  const query=useQuery(managerDetailQuery(booking));
  const b=query.data?.booking;
  const progress=b&&b.totalAmount>0?Math.max(0,Math.min(100,Number(b.paidAmount)/Number(b.totalAmount)*100)):0;
  return <Sheet open onOpenChange={open=>{if(!open)onClose();}}><SheetContent side="right" dir="rtl" className="flex !w-[min(96vw,680px)] !max-w-[680px] flex-col !overflow-hidden !p-0 text-slate-900"><SheetHeader className="shrink-0 border-b p-5 pe-12"><SheetTitle>تفاصيل الحجز</SheetTitle><SheetDescription>{booking.number} · تفاصيل المناسبة والحساب وتنفيذ الكادر</SheetDescription></SheetHeader><div className="min-h-0 flex-1 overflow-y-auto overscroll-contain p-5">
    {query.isPending&&<div className="space-y-4" aria-label="جارٍ تحميل التفاصيل"><Skeleton className="h-20"/><Skeleton className="h-40"/><Skeleton className="h-64"/></div>}
    {query.isError&&<div role="alert" className="space-y-3 rounded-xl border border-red-100 p-4"><p>تعذر تحميل تفاصيل الحجز</p><p className="text-sm text-slate-500">{query.error.message}</p><Button variant="outline" onClick={()=>query.refetch()}>إعادة المحاولة</Button></div>}
    {b&&query.data&&<div className="space-y-6"><div className="flex flex-wrap items-center justify-between gap-3"><KoshaThumbnail booking={b}/><BookingStatusBadge status={b.status}/></div><section className="space-y-3 rounded-2xl border border-[#eee8df] p-4"><h3 className="text-lg font-semibold">{b.customerName||[b.groomName,b.brideName].filter(Boolean).join(" & ")}</h3><p className="flex items-center gap-2 text-sm"><Phone size={16}/><bdi>{b.phone||"لم يسجل هاتف"}</bdi></p><p className="flex items-center gap-2 text-sm"><CalendarDays size={16}/>{displayEventDate(b.eventDate)} · {displayEventTime(b.eventTime)}</p><p className="flex items-center gap-2 text-sm"><MapPin size={16}/>{b.hallLocation||[b.province,b.area,b.cityArea].filter(Boolean).join("، ")||"الموقع غير محدد"}</p>{b.eventType&&<p className="text-sm text-slate-500">المناسبة: {b.eventType}</p>}</section>
    <section className="space-y-4 rounded-2xl bg-[#faf8f5] p-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">الحساب</h3><PaymentStatusBadge status={b.paymentStatus}/></div><p className="text-xl font-semibold tabular-nums">{b.paymentStatus==="pending_pricing"?"بانتظار التسعير":formatCurrency(b.totalAmount)}</p><div role="progressbar" aria-label="نسبة المبلغ المدفوع" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(progress)} className="h-2 overflow-hidden rounded-full bg-white"><div className="h-full rounded-full bg-emerald-600" style={{width:`${progress}%`}}/></div><div className="flex flex-wrap justify-between gap-3 text-sm"><span>المدفوع: <b className="text-emerald-800">{formatCurrency(b.paidAmount)}</b></span><span>المتبقي: <b>{formatCurrency(b.remainingAmount)}</b></span></div><p className="text-xs text-slate-500">{Math.round(progress)}% مدفوع · وفق حالة الدفع المركزية</p></section>
    <section className="space-y-2"><h3 className="font-semibold">النقل</h3><p className="text-sm">{b.transportationMode==="customer"?"النقل من مسؤولية الزبون":b.transportationMode==="ajn"?"نقل AJN":"لم تحدد ترتيبات النقل"}</p>{b.transportationMode==="ajn"&&<p className="text-sm text-slate-600">{[b.transportationVehicleName,b.transportationDriverName].filter(Boolean).join(" · ")||"لم تعيّن المركبة أو السائق"} · {formatCurrency(b.transportationFee||0)}</p>}</section>
    <section><h3 className="mb-2 font-semibold">الملاحظات</h3><p className="whitespace-pre-wrap break-words text-sm text-slate-600">{[b.notes,b.internalNotes].filter(Boolean).join("\n")||"لا توجد ملاحظات."}</p></section><div className="flex flex-wrap gap-2"><Button asChild size="sm" variant="outline"><a href={`/admin/invoice/${b.id}?type=${b.source==="service"?"booking":"kosha"}&print=1`} target="_blank" rel="noopener noreferrer"><Printer size={16}/>طباعة A4</a></Button><BookingThermalPrintAction booking={{...b,raw:b}}/></div><div className="border-t pt-5"><StaffExecutionPanel detail={query.data}/></div></div>}
  </div><footer className="flex shrink-0 flex-wrap gap-2 border-t bg-white p-4"><Button disabled={!b} onClick={()=>b&&onFull(b)}>فتح التفاصيل الكاملة</Button><Button variant="outline" disabled={!b} onClick={()=>b&&onEdit(b)}>تعديل الحجز</Button><Button variant="ghost" onClick={onClose}>إغلاق</Button></footer></SheetContent></Sheet>;
}
