export type SalesInvoiceThermalItem = { productName?: string; name?: string; quantity: number | string; unitPrice: number | string; total: number | string };
export type SalesInvoiceThermalInput = {
  paperSize: "58mm" | "80mm";
  invoiceNo: string;
  issuedAt?: string | null;
  customerName?: string | null;
  customerPhone?: string | null;
  paymentMethod?: string | null;
  paymentStatus?: string | null;
  employeeName?: string | null;
  items: SalesInvoiceThermalItem[];
  subtotal?: number | string | null;
  discount?: number | string | null;
  tax?: number | string | null;
  deliveryFee?: number | string | null;
  total: number | string;
  paid: number | string;
  remaining: number | string;
  notes?: string | null;
  qrImageUrl?: string | null;
  qrCaption?: string | null;
  logoUrl?: string | null;
  companyName?: string | null;
  companyPhone?: string | null;
  companyAddress?: string | null;
  footerText?: string | null;
  showLogo?: boolean;
  showQr?: boolean;
  showCustomerPhone?: boolean;
  showEmployeeName?: boolean;
  showAddress?: boolean;
  horizontalOffsetMm?: number | string | null;
  verticalOffsetMm?: number | string | null;
};

export function toLatinDigits(value: unknown): string;
export function formatLatinNumber(value: unknown, options?: Intl.NumberFormatOptions): string;
export function formatLatinMoney(value: unknown): string;
export function formatLatinDate(value: unknown): string;
export function salesInvoiceThermalCss(size: "58mm" | "80mm", horizontalOffsetMm?: number | string | null, verticalOffsetMm?: number | string | null): string;
export function buildSalesInvoiceThermalHtml(input: SalesInvoiceThermalInput): string;
