import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "wouter";
import { AlertTriangle, Armchair, Banknote, Barcode, Boxes, Camera, Check, ChevronLeft, CircleDollarSign, ClipboardCheck, Crown, FileImage, Flower2, History, Lightbulb, ListChecks, Loader2, MapPin, PackageCheck, Plus, QrCode, RotateCcw, Save, ScanLine, Speaker, Truck, UserRound, Users, Warehouse, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { useToast } from "@/hooks/use-toast";
import { adminFetch, formatCurrency } from "@/views/admin/_lib";
import { filesToMedia, staffApi, type ExecutionAsset, type ExecutionDetail, type ExecutionServiceKey } from "./lib";
import "./event-execution-workspace.css";

const SERVICE_META: Record<ExecutionServiceKey, { label: string; icon: typeof Crown; tone: string }> = {
  kosha: { label: "الكوشة", icon: Crown, tone: "rose" }, sound: { label: "الصوتيات", icon: Speaker, tone: "blue" },
  lighting: { label: "الإضاءة", icon: Lightbulb, tone: "amber" }, furniture: { label: "الأثاث والديكور", icon: Armchair, tone: "purple" },
  decoration: { label: "الديكور", icon: Flower2, tone: "rose" }, transport: { label: "النقل والتنصيب", icon: Truck, tone: "blue" }, screens: { label: "الشاشات", icon: Boxes, tone: "purple" },
};
const MAIN_STAGES = [["booked", "تم الحجز"], ["details_approved", "اعتماد التفاصيل"], ["preparing", "قيد التجهيز"], ["loaded", "تم التحميل"], ["installing", "جاري التنصيب"], ["executed", "تم التنفيذ"], ["event_active", "المناسبة جارية"], ["dismantled", "تم الفك"], ["returned", "تمت الإعادة"], ["inspection", "قيد الفحص"], ["completed", "مكتمل"]] as const;
const WORKFLOWS: Record<string, ReadonlyArray<readonly [string, string]>> = {
  kosha: [["design_selected", "اختيار التصميم"], ["design_approved", "اعتماد التصميم"], ["prepared", "تجهيز القطع"], ["loaded", "التحميل"], ["installing", "التنصيب"], ["installed", "تم التنصيب"], ["photographed", "تصوير التنفيذ"], ["dismantled", "الفك"], ["returned", "الإعادة"], ["inspected", "الفحص"]],
  sound: [["reserved", "حجز المعدات"], ["checked", "فحص المعدات"], ["prepared", "التجهيز"], ["loaded", "التحميل"], ["out", "خرجت"], ["installed", "التركيب"], ["sound_checked", "اختبار الصوت"], ["ready", "جاهز"], ["dismantled", "الفك"], ["returned", "الإعادة"], ["inspected", "الفحص النهائي"]],
  lighting: [["reserved", "محجوز"], ["prepared", "مجهز"], ["loaded", "محمل"], ["installed", "مركب"], ["tested", "مختبر"], ["ready", "جاهز"], ["dismantled", "مفكوك"], ["returned", "معاد"], ["inspected", "مفحوص"]],
  furniture: [["reserved", "محجوز"], ["prepared", "مجهز"], ["loaded", "محمل"], ["installed", "مركب"], ["returned", "معاد"], ["inspected", "مفحوص"]],
};
const WAREHOUSE_STAGES = [["reserved", "محجوز"], ["picked", "تم التجهيز"], ["loaded", "تم التحميل"], ["out", "خرج من المستودع"], ["returned", "تمت الإعادة"], ["inspection", "قيد الفحص"], ["completed", "مكتمل"]] as const;
const PHOTO_SECTIONS = [["design_reference", "مرجع التصميم"], ["before_preparation", "قبل التجهيز"], ["during_preparation", "أثناء التجهيز"], ["loading", "التحميل"], ["during_installation", "أثناء التنصيب"], ["after_installation", "بعد التنصيب"], ["during_event", "أثناء المناسبة"], ["before_dismantling", "قبل الفك"], ["after_dismantling", "بعد الفك"], ["return_inspection", "فحص الإرجاع"], ["damage", "صور التلف"]] as const;

function tone(value: string) { if (["completed", "ready", "installed", "returned", "inspected", "paid"].includes(value)) return "success"; if (["damaged", "missing", "lost", "cancelled"].includes(value)) return "danger"; if (["preparing", "inspection", "pending", "reserved"].includes(value)) return "warning"; return "info"; }
function Status({ value, label }: { value: string; label?: string }) { return <span className={`ajn-ex-status is-${tone(value)}`}>{label || value}</span>; }

export default function EventExecutionWorkspace({ source, id, onBack }: { source: "kosha" | "service"; id: number; onBack: () => void }) {
  const queryClient = useQueryClient(); const { toast } = useToast(); const [tab, setTab] = useState("overview");
  const key = ["staff", "event-execution", source, id];
  const query = useQuery<ExecutionDetail>({ queryKey: key, queryFn: () => staffApi.execution(source, id) });
  const data = query.data; const base = `/admin/booking-operations/${source}/${id}`;
  const refresh = () => { queryClient.invalidateQueries({ queryKey: key }); queryClient.invalidateQueries({ queryKey: ["staff", "execution-bookings"] }); };
  const update = useMutation({ mutationFn: (payload: { section: string; stage?: string; data?: Record<string, any> }) => staffApi.updateExecution(source, id, payload), onSuccess: () => { refresh(); toast({ title: "تم حفظ تحديث التنفيذ" }); }, onError: (error: any) => toast({ title: "تعذر حفظ التحديث", description: error?.message, variant: "destructive" }) });
  if (query.isLoading) return <div className="ajn-ex-loading"><Loader2 className="animate-spin" /> جاري تحميل مساحة التنفيذ...</div>;
  if (!data) return <div className="ajn-ex-empty"><AlertTriangle /><h2>تعذر فتح الحجز</h2><Button variant="outline" onClick={onBack}>الرجوع</Button></div>;
  const currentMain = data.state.mainStage || "booked";
  const tabs = [
    ["overview", "نظرة عامة", ClipboardCheck],
    ...(data.services.includes("kosha") ? [["kosha", "الكوشة", Crown]] : []),
    ...(data.services.includes("sound") ? [["sound", "الصوتيات", Speaker]] : []),
    ...(data.services.includes("lighting") ? [["lighting", "الإضاءة", Lightbulb]] : []),
    ...(data.services.some((key) => ["furniture", "decoration"].includes(key)) ? [["furniture", "الأثاث والديكور", Armchair]] : []),
    ["assets", "الأصول", PackageCheck], ["warehouse", "المستودع", Warehouse], ["depreciation", "الإهلاك", Wrench], ["team", "فريق التنفيذ", Users], ["tasks", "المهام", ListChecks], ["photos", "الصور", Camera], ["damage", "التلف والنقص", AlertTriangle], ["finance", "الملخص المالي", CircleDollarSign], ["activity", "النشاط والتايملاين", History],
  ] as Array<[string, string, typeof Crown]>;
  return <div className="ajn-event-execution" dir="rtl">
    <header className="ajn-ex-header"><div className="ajn-ex-header-top"><Button variant="ghost" onClick={onBack}><ChevronLeft /> الحجوزات</Button><div className="ajn-ex-actions"><DropdownMenu dir="rtl"><DropdownMenuTrigger asChild><Button className="ajn-ex-primary"><Plus /> إضافة عنصر</Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem asChild><Link href={`/admin/bookings/${source}/${id}?tab=products`}><Boxes /> إضافة منتج من المتجر</Link></DropdownMenuItem><DropdownMenuItem asChild><Link href={`/admin/bookings/${source}/${id}?tab=assets`}><PackageCheck /> إضافة أصل من الأصول</Link></DropdownMenuItem><DropdownMenuItem onSelect={() => setTab("overview")}><Plus /> إضافة خدمة</DropdownMenuItem><DropdownMenuItem onSelect={() => setTab("finance")}><Banknote /> إضافة تكلفة إضافية</DropdownMenuItem></DropdownMenuContent></DropdownMenu><Button variant="outline" asChild><Link href={`/admin/bookings/${source}/${id}?tab=warehouse`}><ScanLine /> المسح والمستودع</Link></Button></div></div>
      <div className="ajn-ex-identity"><div><small>بوابة الكوشات والتنفيذ</small><h1>{data.booking.number}</h1><p><UserRound /> {data.booking.customerName} · {data.booking.phone}</p></div><div className="ajn-ex-header-facts"><span><b>{String(data.booking.eventDate || "").slice(0, 10)}</b><small>{data.booking.eventTime || "الوقت غير محدد"}</small></span><span><b>{data.booking.venue || "الموقع غير محدد"}</b><small>موقع المناسبة</small></span><span><b>{formatCurrency(data.booking.remaining)}</b><small>المبلغ المتبقي</small></span><span><Status value={currentMain} label={MAIN_STAGES.find(([key]) => key === currentMain)?.[1] || currentMain} /><small>حالة التنفيذ</small></span></div></div>
      <div className="ajn-ex-services">{data.services.map((service) => { const meta = SERVICE_META[service]; const Icon = meta.icon; return <span key={service} className={`is-${meta.tone}`}><Icon /> {meta.label}</span>; })}</div>
    </header>
    <Workflow title="مسار تنفيذ المناسبة" steps={MAIN_STAGES} current={currentMain} busy={update.isPending} onStep={(stage) => update.mutate({ section: "main", stage })} />
    <Tabs value={tab} onValueChange={setTab} className="ajn-ex-tabs"><TabsList>{tabs.map(([value, label, Icon]) => <TabsTrigger key={value} value={value}><Icon /> {label}</TabsTrigger>)}</TabsList>
      <TabsContent value="overview"><Overview data={data} setTab={setTab} /></TabsContent>
      {data.services.includes("kosha") && <TabsContent value="kosha"><ServiceSection type="kosha" data={data} update={update} /></TabsContent>}
      {data.services.includes("sound") && <TabsContent value="sound"><SoundSection data={data} update={update} /></TabsContent>}
      {data.services.includes("lighting") && <TabsContent value="lighting"><ServiceSection type="lighting" data={data} update={update} /></TabsContent>}
      <TabsContent value="furniture"><FurnitureSection data={data} update={update} /></TabsContent>
      <TabsContent value="assets"><AssetsSection data={data} base={base} refresh={refresh} /></TabsContent>
      <TabsContent value="warehouse"><WarehouseSection data={data} base={base} refresh={refresh} /></TabsContent>
      <TabsContent value="depreciation"><DepreciationSection assets={data.assets} /></TabsContent>
      <TabsContent value="team"><TeamSection data={data} update={update} /></TabsContent>
      <TabsContent value="tasks"><TasksSection data={data} source={source} id={id} refresh={refresh} /></TabsContent>
      <TabsContent value="photos"><PhotosSection data={data} source={source} id={id} refresh={refresh} /></TabsContent>
      <TabsContent value="damage"><DamageSection data={data} base={base} refresh={refresh} /></TabsContent>
      <TabsContent value="finance"><FinanceSection data={data} /></TabsContent>
      <TabsContent value="activity"><ActivitySection data={data} /></TabsContent>
    </Tabs>
  </div>;
}

function Workflow({ title, steps, current, busy, onStep }: { title: string; steps: ReadonlyArray<readonly [string, string]>; current: string; busy?: boolean; onStep: (stage: string) => void }) {
  const index = steps.findIndex(([key]) => key === current);
  return <section className="ajn-ex-workflow"><div><strong>{title}</strong><Status value={current} label={steps[index]?.[1] || current} /></div><div className="ajn-ex-steps">{steps.map(([key, label], stepIndex) => <button key={key} type="button" disabled={busy || stepIndex > index + 1 || stepIndex <= index} className={stepIndex < index ? "is-done" : stepIndex === index ? "is-current" : ""} onClick={() => onStep(key)}><i>{stepIndex < index ? <Check /> : stepIndex + 1}</i><span>{label}</span></button>)}</div></section>;
}

function Panel({ icon: Icon, title, subtitle, actions, children }: { icon: typeof Crown; title: string; subtitle: string; actions?: React.ReactNode; children: React.ReactNode }) { return <section className="ajn-ex-panel"><div className="ajn-ex-panel-head"><div><Icon /><span><small>{subtitle}</small><h2>{title}</h2></span></div>{actions}</div>{children}</section>; }

function Overview({ data, setTab }: { data: ExecutionDetail; setTab: (tab: string) => void }) {
  const open = data.assets.filter((item) => item.out > 0).length; const problems = data.assets.filter((item) => item.problem !== "none").length; const doneTasks = data.tasks.filter((item) => item.status === "completed").length;
  return <div className="ajn-ex-overview"><div className="ajn-ex-metrics"><button onClick={() => setTab("assets")}><PackageCheck /><span><small>الأصول</small><b>{data.assets.length}</b></span></button><button onClick={() => setTab("warehouse")}><Warehouse /><span><small>خارج المستودع</small><b>{open}</b></span></button><button onClick={() => setTab("tasks")}><ListChecks /><span><small>المهام المكتملة</small><b>{doneTasks}/{data.tasks.length}</b></span></button><button onClick={() => setTab("photos")}><Camera /><span><small>صور التنفيذ</small><b>{data.photos.length}</b></span></button><button onClick={() => setTab("damage")} className={problems ? "is-critical" : ""}><AlertTriangle /><span><small>التلف والنقص</small><b>{problems}</b></span></button><button onClick={() => setTab("finance")}><CircleDollarSign /><span><small>المتبقي</small><b>{formatCurrency(data.booking.remaining)}</b></span></button></div><Panel icon={History} title="آخر النشاطات" subtitle="تايملاين موحّد"><Timeline rows={data.timeline.slice(0, 8)} /></Panel></div>;
}

function ServiceSection({ type, data, update }: { type: "kosha" | "lighting"; data: ExecutionDetail; update: any }) {
  const meta = SERVICE_META[type]; const section = data.state.sections?.[type] ?? {}; const [form, setForm] = useState<Record<string, any>>(section);
  useEffect(() => setForm(section), [JSON.stringify(section)]);
  const fields = type === "kosha" ? [["model", "موديل الكوشة"], ["design", "التصميم"], ["size", "الحجم"], ["color", "اللون"], ["stageType", "نوع المنصة"], ["backdrop", "الخلفية"], ["flowers", "الورود"], ["sofa", "الكنبة"], ["tables", "الطاولات"], ["entrance", "قطع المدخل"], ["carpet", "السجاد"], ["accessories", "الإكسسوارات"]] : [["units", "وحدات الإضاءة"], ["movingHeads", "Moving Heads"], ["ledLights", "LED"], ["decorative", "إضاءة ديكورية"], ["stageLighting", "إضاءة المنصة"], ["power", "متطلبات الطاقة"], ["controllers", "وحدات التحكم"], ["cables", "الكيبلات"], ["positions", "مواقع التركيب"], ["testStatus", "حالة الاختبار"]];
  const workflow = WORKFLOWS[type]; return <Panel icon={meta.icon} title={meta.label} subtitle="تفاصيل التنفيذ وحالة التجهيز" actions={<Button className="ajn-ex-primary" onClick={() => update.mutate({ section: type, data: form })}><Save /> حفظ التفاصيل</Button>}><Workflow title={`مسار ${meta.label}`} steps={workflow} current={section.stage || ""} busy={update.isPending} onStep={(stage) => update.mutate({ section: type, stage, data: form })} /><div className="ajn-ex-form-grid">{fields.map(([key, label]) => <div key={key}><Label htmlFor={`${type}-${key}`}>{label}</Label><Input id={`${type}-${key}`} value={form[key] ?? ""} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></div>)}<div className="is-wide"><Label htmlFor={`${type}-notes`}>ملاحظات التنصيب</Label><Textarea id={`${type}-notes`} value={form.notes ?? ""} onChange={(event) => setForm({ ...form, notes: event.target.value })} /></div></div>{type === "kosha" && data.setup && <div className="ajn-ex-setup"><h3>التصميم المعتمد من الحجز</h3><div>{data.setup.kosha && <article>{data.setup.kosha.image ? <img src={data.setup.kosha.image} alt={data.setup.kosha.name} /> : <Crown />}<b>{data.setup.kosha.name}</b><small>{data.setup.kosha.specs.join(" · ")}</small></article>}{[...data.setup.welcomeBoards, ...data.setup.addons, ...data.setup.accessories].map((item) => <article key={item.name}>{item.image ? <img src={item.image} alt={item.name} /> : <Flower2 />}<b>{item.name}</b></article>)}</div></div>}</Panel>;
}

function SoundSection({ data, update }: { data: ExecutionDetail; update: any }) {
  const section = data.state.sections?.sound ?? {}; const [form, setForm] = useState<Record<string, any>>(section); useEffect(() => setForm(section), [JSON.stringify(section)]);
  const fields = [["speakers", "السماعات RCF / W17"], ["mixers", "المكسرات"], ["wirelessMics", "المايكات اللاسلكية"], ["wiredMics", "المايكات السلكية"], ["dj", "معدات DJ"], ["screens", "الشاشات"], ["stands", "الستاندات"], ["cables", "الكيبلات"], ["power", "الطاقة الاحتياطية"], ["technician", "فني الصوت"], ["installTime", "وقت التركيب"], ["soundCheckTime", "وقت فحص الصوت"]];
  const checks = [["speakersConnected", "تم توصيل السماعات"], ["mixerTested", "تم فحص المكسر"], ["microphonesTested", "تم فحص المايكات"], ["cablesChecked", "تم فحص الكيبلات"], ["backupPowerChecked", "تم فحص الطاقة الاحتياطية"], ["soundLevelTested", "تم اختبار مستوى الصوت"], ["managerConfirmed", "اعتماد العميل أو المدير"]];
  const checklist = form.checklist ?? {}; return <Panel icon={Speaker} title="الصوتيات" subtitle="المعدات والفني وقائمة الفحص الإلزامية" actions={<Button className="ajn-ex-primary" onClick={() => update.mutate({ section: "sound", data: form })}><Save /> حفظ الصوتيات</Button>}><Workflow title="مسار الصوتيات" steps={WORKFLOWS.sound} current={section.stage || ""} busy={update.isPending} onStep={(stage) => update.mutate({ section: "sound", stage, data: form })} /><div className="ajn-ex-form-grid">{fields.map(([key, label]) => <div key={key}><Label htmlFor={`sound-${key}`}>{label}</Label><Input id={`sound-${key}`} value={form[key] ?? ""} onChange={(event) => setForm({ ...form, [key]: event.target.value })} /></div>)}</div><div className="ajn-ex-checklist"><h3><ClipboardCheck /> قائمة فحص الصوت</h3>{checks.map(([key, label]) => <label key={key}><input type="checkbox" checked={checklist[key] === true} onChange={(event) => setForm({ ...form, checklist: { ...checklist, [key]: event.target.checked } })} /><span>{label}</span></label>)}</div></Panel>;
}

function FurnitureSection({ data, update }: { data: ExecutionDetail; update: any }) { const section = data.state.sections?.furniture ?? {}; const rows = data.assets.filter((item) => /chair|table|flower|decor|carpet|entrance|كرسي|طاول|ورد|ديكور|سجاد|مدخل/i.test(`${item.name} ${item.category || ""}`)); return <Panel icon={Armchair} title="الأثاث والديكور" subtitle="الكميات من سجل الأصول الفعلي"><Workflow title="مسار الأثاث والديكور" steps={WORKFLOWS.furniture} current={section.stage || ""} busy={update.isPending} onStep={(stage) => update.mutate({ section: "furniture", stage })} /><AssetQuantityTable rows={rows} /></Panel>; }

function AssetQuantityTable({ rows }: { rows: ExecutionAsset[] }) { return <div className="ajn-ex-table-wrap"><table><thead><tr><th>العنصر</th><th>المطلوب</th><th>المتاح</th><th>المحجوز</th><th>الخارج</th><th>المرتجع</th><th>التالف</th><th>المفقود</th><th>الحالة</th></tr></thead><tbody>{rows.map((item) => <tr key={item.productId}><td><b>{item.name}</b><small>{item.assetCode}</small></td><td>{item.quantity}</td><td>{item.available}</td><td>{item.reserved}</td><td>{item.out}</td><td>{item.returned}</td><td>{item.damaged}</td><td>{item.missing}</td><td><Status value={item.stage} /></td></tr>)}</tbody></table>{!rows.length && <p className="ajn-ex-no-data">لا توجد عناصر مرتبطة بهذا القسم بعد.</p>}</div>; }

function AssetsSection({ data, base, refresh }: { data: ExecutionDetail; base: string; refresh: () => void }) { const { toast } = useToast(); const action = useMutation({ mutationFn: (input: any) => adminFetch(`${base}/assets`, { method: "POST", body: JSON.stringify({ ...input, confirmation: true }) }), onSuccess: () => { refresh(); toast({ title: "تم تحديث حركة الأصل" }); }, onError: (e: any) => toast({ title: "تعذر تحديث الأصل", description: e?.message, variant: "destructive" }) }); const act = (item: ExecutionAsset, mode: string) => action.mutate({ mode, productId: item.productId, quantity: item.quantity, problem: "none" }); return <Panel icon={PackageCheck} title="الأصول والمعدات" subtitle="الحجز والتجهيز والخروج والإرجاع من سجل الأصول"><div className="ajn-ex-table-wrap"><table><thead><tr><th>الأصل</th><th>QR / باركود</th><th>المستودع</th><th>الكمية</th><th>المتاح</th><th>الصحة</th><th>القيمة</th><th>آخر حجز</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{data.assets.map((item) => <tr key={item.productId}><td><b>{item.name}</b><small>{item.assetCode}</small></td><td><QrCode /> {item.barcode || (item.qrToken ? "QR مسجل" : "—")}</td><td>{item.warehouse || item.location || "الرئيسي"}</td><td>{item.quantity}</td><td>{item.available}</td><td className={item.healthScore < 60 ? "is-danger" : "is-positive"}>{item.healthScore}%</td><td>{formatCurrency(item.currentValue)}</td><td>{item.lastBooking || "—"}</td><td><Status value={item.stage} /></td><td><div className="ajn-ex-row-actions">{item.stage === "linked" && <Button size="sm" onClick={() => act(item, "reserve")}>حجز</Button>}{item.stage === "reserved" && <Button size="sm" onClick={() => act(item, "pick")}><Barcode /> تجهيز</Button>}{item.stage === "picked" && <Button size="sm" onClick={() => act(item, "checkout")}><QrCode /> إخراج</Button>}{item.stage === "out" && <Button size="sm" onClick={() => act(item, "return")}><RotateCcw /> إرجاع سليم</Button>}{item.stage === "returned" && <Button size="sm" onClick={() => act(item, "inspect")}><ClipboardCheck /> فحص</Button>}</div></td></tr>)}</tbody></table></div></Panel>; }

function WarehouseSection({ data, base, refresh }: { data: ExecutionDetail; base: string; refresh: () => void }) { const { toast } = useToast(); const [stage, setStage] = useState(data.state?.warehouseStage || "reserved"); const query = useQuery<any>({ queryKey: ["booking-ops-overview", base], queryFn: () => adminFetch(`${base}/overview`) }); useEffect(() => setStage(query.data?.warehouseStage || "reserved"), [query.data?.warehouseStage]); const mutation = useMutation({ mutationFn: (next: string) => adminFetch(`${base}/warehouse`, { method: "PATCH", body: JSON.stringify({ stage: next, confirmation: true }) }), onSuccess: () => { query.refetch(); refresh(); toast({ title: "تم تحديث مسار المستودع" }); }, onError: (e: any) => toast({ title: "تعذر تحديث المستودع", description: e?.message, variant: "destructive" }) }); return <Panel icon={Warehouse} title="تنفيذ المستودع" subtitle="المسح والتجهيز والتحميل والإرجاع"><Workflow title="مسار المستودع" steps={WAREHOUSE_STAGES} current={stage} busy={mutation.isPending} onStep={(next) => mutation.mutate(next)} /><div className="ajn-ex-scan-card"><ScanLine /><div><h3>المسح التشغيلي</h3><p>امسح هوية الموظف، QR الحجز، ثم كل أصل أو دفعة مجمعة وسجل الكمية والتوقيع.</p></div><Button asChild><Link href="/admin/asset-movements"><QrCode /> فتح شاشة المسح</Link></Button></div><AssetQuantityTable rows={data.assets} /></Panel>; }

function DepreciationSection({ assets }: { assets: ExecutionAsset[] }) { return <Panel icon={Wrench} title="الإهلاك والاستخدام" subtitle="يُحدث بعد الإرجاع والفحص ولا يُضاف كعنصر"><div className="ajn-ex-table-wrap"><table><thead><tr><th>الأصل</th><th>القيمة الأصلية</th><th>الحالية</th><th>الإهلاك المتراكم</th><th>الاستخدامات</th><th>الساعات</th><th>الصحة</th><th>الصيانة</th></tr></thead><tbody>{assets.map((item) => <tr key={item.productId}><td><b>{item.name}</b><small>{item.assetCode}</small></td><td>{formatCurrency(item.purchaseValue)}</td><td>{formatCurrency(item.currentValue)}</td><td>{formatCurrency(item.depreciationAmount)}</td><td>{item.usageCount}</td><td>{item.usageHours}</td><td>{item.healthScore}%</td><td>{item.maintenanceRequired ? <Status value="damaged" label="مطلوبة" /> : "لا توجد توصية"}</td></tr>)}</tbody></table></div></Panel>; }

function TeamSection({ data, update }: { data: ExecutionDetail; update: any }) { const roles = ["قائد الفريق", "منصب الكوشة", "فني الصوت", "فني الإضاءة", "السائق", "موظف المستودع", "المصور", "مساعد"]; const [team, setTeam] = useState<any[]>(Array.isArray(data.state.team) ? data.state.team : []); useEffect(() => setTeam(Array.isArray(data.state.team) ? data.state.team : []), [JSON.stringify(data.state.team)]); const add = () => setTeam([...team, { staffId: "", name: "", role: roles[0], phone: "", task: "", startTime: "", completionTime: "", status: "assigned" }]); const patch = (index: number, values: any) => setTeam(team.map((row, i) => i === index ? { ...row, ...values } : row)); return <Panel icon={Users} title="فريق التنفيذ" subtitle="الموظفون والأدوار وأوقات العمل" actions={<div className="ajn-ex-row-actions"><Button variant="outline" onClick={add}><Plus /> إضافة موظف</Button><Button className="ajn-ex-primary" onClick={() => update.mutate({ section: "team", data: { team } })}><Save /> حفظ الفريق</Button></div>}><div className="ajn-ex-team">{team.map((row, index) => <article key={index}><Input inputMode="numeric" placeholder="رقم الموظف" value={row.staffId} onChange={(e) => patch(index, { staffId: e.target.value.replace(/\D/g, "") })} /><Input placeholder="اسم الموظف" value={row.name} onChange={(e) => patch(index, { name: e.target.value })} /><select value={row.role} onChange={(e) => patch(index, { role: e.target.value })}>{roles.map((role) => <option key={role}>{role}</option>)}</select><Input placeholder="الهاتف" value={row.phone} onChange={(e) => patch(index, { phone: e.target.value })} /><Input placeholder="المهمة" value={row.task} onChange={(e) => patch(index, { task: e.target.value })} /><Input type="datetime-local" value={row.startTime} onChange={(e) => patch(index, { startTime: e.target.value })} /><select value={row.status} onChange={(e) => patch(index, { status: e.target.value })}><option value="assigned">مكلف</option><option value="working">قيد التنفيذ</option><option value="completed">مكتمل</option></select><Button variant="ghost" onClick={() => setTeam(team.filter((_, i) => i !== index))}>إزالة</Button></article>)}{!team.length && <p className="ajn-ex-no-data">لم يتم تعيين فريق التنفيذ بعد.</p>}</div></Panel>; }

function TasksSection({ data, source, id, refresh }: { data: ExecutionDetail; source: "kosha" | "service"; id: number; refresh: () => void }) { const { toast } = useToast(); const mutation = useMutation({ mutationFn: () => staffApi.suggestExecutionTasks(source, id), onSuccess: (result) => { refresh(); toast({ title: result.created ? `تم إنشاء ${result.created} مهام` : "المهام المقترحة موجودة مسبقًا" }); }, onError: (e: any) => toast({ title: "تعذر إنشاء المهام", description: e?.message, variant: "destructive" }) }); return <Panel icon={ListChecks} title="مهام التنفيذ" subtitle="مهام مقترحة حسب خدمات الحجز" actions={<div className="ajn-ex-row-actions"><Button onClick={() => mutation.mutate()} disabled={mutation.isPending}><Plus /> إنشاء المهام المقترحة</Button><Button variant="outline" asChild><Link href="/admin/tasks">مركز المهام</Link></Button></div>}><div className="ajn-ex-task-list">{data.tasks.map((task) => <article key={task.id}><span>{task.status === "completed" ? <Check /> : <ListChecks />}</span><div><h3>{task.title}</h3><p>{task.description || "بدون وصف"}</p><small>{task.taskNo || `#${task.id}`} · {task.dueAt ? String(task.dueAt).slice(0, 16).replace("T", " ") : "بدون موعد"}</small></div><Status value={task.status} /></article>)}{!data.tasks.length && <p className="ajn-ex-no-data">أنشئ المهام المقترحة لبدء خطة التنفيذ.</p>}</div></Panel>; }

function PhotosSection({ data, source, id, refresh }: { data: ExecutionDetail; source: "kosha" | "service"; id: number; refresh: () => void }) { const { toast } = useToast(); const [purpose, setPurpose] = useState("after_installation"); const [media, setMedia] = useState<any[]>([]); const upload = useMutation({ mutationFn: () => staffApi.uploadExecutionPhotos(source, id, purpose, media), onSuccess: () => { setMedia([]); refresh(); toast({ title: "تم رفع صور التنفيذ" }); }, onError: (e: any) => toast({ title: "تعذر رفع الصور", description: e?.message, variant: "destructive" }) }); const before = data.photos.find((item) => item.purpose === "before_preparation"); const after = data.photos.find((item) => item.purpose === "after_installation"); return <Panel icon={Camera} title="صور التنفيذ" subtitle="توثيق المراحل والمقارنة قبل وبعد"><div className="ajn-ex-photo-upload"><select value={purpose} onChange={(e) => setPurpose(e.target.value)}>{PHOTO_SECTIONS.map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><Input type="file" accept="image/*,video/*" multiple onChange={async (e) => { if (e.target.files) setMedia(await filesToMedia(e.target.files)); }} /><Button className="ajn-ex-primary" disabled={!media.length || upload.isPending} onClick={() => upload.mutate()}>{upload.isPending ? <Loader2 className="animate-spin" /> : <Camera />} رفع الإثبات</Button></div>{(before || after) && <div className="ajn-ex-compare"><div><small>قبل</small>{before && <img src={before.url} alt="قبل التنفيذ" />}</div><div><small>بعد</small>{after && <img src={after.url} alt="بعد التنفيذ" />}</div></div>}<div className="ajn-ex-photo-grid">{PHOTO_SECTIONS.map(([key, label]) => { const rows = data.photos.filter((item) => item.purpose === key); return <section key={key}><h3>{label} <Badge variant="outline">{rows.length}</Badge></h3><div>{rows.map((item) => item.kind === "video" ? <video key={item.id} src={item.url} controls /> : <img key={item.id} src={item.url} alt={label} />)}</div></section>; })}</div></Panel>; }

function DamageSection({ data, base, refresh }: { data: ExecutionDetail; base: string; refresh: () => void }) { const { toast } = useToast(); const [selected, setSelected] = useState<ExecutionAsset | null>(null); const [form, setForm] = useState({ problem: "damaged", quantity: 1, description: "", estimatedCost: 0, managerApproval: false }); const action = useMutation({ mutationFn: () => adminFetch(`${base}/assets`, { method: "POST", body: JSON.stringify({ mode: "return", productId: selected!.productId, quantity: form.quantity, problem: form.problem, description: form.description, estimatedCost: form.estimatedCost, managerApproval: form.managerApproval, photoUrls: data.photos.filter((item) => item.purpose === "damage").map((item) => item.url), confirmation: true }) }), onSuccess: () => { setSelected(null); refresh(); toast({ title: "تم تسجيل حالة الإرجاع" }); }, onError: (e: any) => toast({ title: "تعذر تسجيل الحالة", description: e?.message, variant: "destructive" }) }); const problems = data.assets.filter((item) => item.problem !== "none"); return <Panel icon={AlertTriangle} title="التلف والنقص" subtitle="لا يكتمل الحجز قبل الفحص والاعتماد"><div className="ajn-ex-damage-question"><div><h3>هل يوجد تلف أو نقص؟</h3><p>اختر الأصل الخارج ثم سجل الحالة والصور والتكلفة.</p></div><select value={selected?.productId || ""} onChange={(e) => setSelected(data.assets.find((item) => item.productId === Number(e.target.value)) || null)}><option value="">اختر أصلًا...</option>{data.assets.filter((item) => item.out > 0 || item.stage === "returned").map((item) => <option key={item.productId} value={item.productId}>{item.name}</option>)}</select></div>{selected && <div className="ajn-ex-inline-form"><div><Label>النوع</Label><select value={form.problem} onChange={(e) => setForm({ ...form, problem: e.target.value })}><option value="damaged">تلف</option><option value="missing">نقص / فقدان</option></select></div><div><Label>الكمية</Label><Input type="number" min={1} max={selected.quantity} value={form.quantity} onChange={(e) => setForm({ ...form, quantity: Number(e.target.value) || 1 })} /></div><div><Label>التكلفة التقديرية</Label><Input type="number" min={0} value={form.estimatedCost} onChange={(e) => setForm({ ...form, estimatedCost: Number(e.target.value) || 0 })} /></div><div className="is-wide"><Label>الوصف *</Label><Textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /></div>{form.problem === "missing" && <label className="ajn-ex-confirm"><input type="checkbox" checked={form.managerApproval} onChange={(e) => setForm({ ...form, managerApproval: e.target.checked })} /> اعتماد المدير على تسجيل النقص</label>}<Button className="ajn-ex-primary" disabled={!form.description.trim() || action.isPending} onClick={() => action.mutate()}>تسجيل الحالة وإرسالها للفحص</Button></div>}<AssetQuantityTable rows={problems} /></Panel>; }

function FinanceSection({ data }: { data: ExecutionDetail }) { const amounts = data.finance.serviceAmounts || {}; const rows = [["الكوشة", amounts.kosha || 0], ["الصوتيات", amounts.sound || 0], ["الإضاءة", amounts.lighting || 0], ["الأثاث", amounts.furniture || 0], ["الديكور", amounts.decoration || 0], ["النقل", amounts.transport || 0], ["التنصيب", amounts.installation || 0], ["منتجات المتجر", data.products.reduce((sum, item) => sum + Number(item.total || 0), 0)], ["رسوم التلف", data.finance.damageCharges], ["الخصومات", -data.finance.discounts], ["الإجمالي", data.finance.total], ["المدفوع", data.finance.paid], ["المتبقي", data.finance.remaining]]; return <Panel icon={CircleDollarSign} title="الملخص المالي" subtitle="الصندوق الرئيسي وكشف العميل والمحاسبة"><div className="ajn-ex-finance">{rows.map(([label, value]) => <div key={String(label)}><span>{label}</span><b className={label === "المتبقي" && Number(value) > 0 ? "is-danger" : ""}>{formatCurrency(Number(value))}</b></div>)}</div><div className="ajn-ex-finance-note"><Banknote /><p>تُنشر الدفعات والقيود من مسار المالية الحالي فقط لمنع التكرار. التكاليف الإضافية تحتاج اعتمادًا ماليًا قبل الترحيل.</p><Button variant="outline" asChild><Link href={`/admin/bookings/${data.source}/${data.id}?tab=finance`}>فتح المالية الكاملة</Link></Button></div></Panel>; }

function ActivitySection({ data }: { data: ExecutionDetail }) { return <div className="ajn-ex-activity"><Panel icon={History} title="التايملاين التشغيلي" subtitle="كل تحديثات الحجز والوحدات"><Timeline rows={data.timeline} /></Panel><Panel icon={ClipboardCheck} title="سجل التدقيق" subtitle="المستخدم والإجراء والوقت"><div className="ajn-ex-audit">{data.audit.map((row) => <article key={row.id}><div><b>{row.action}</b><small>{row.userName || "النظام"}</small></div><time>{new Date(row.createdAt).toLocaleString("ar-IQ")}</time></article>)}</div></Panel></div>; }
function Timeline({ rows }: { rows: ExecutionDetail["timeline"] }) { return <div className="ajn-ex-timeline">{rows.map((row) => <article key={row.id}><i /><time>{new Date(row.createdAt).toLocaleString("ar-IQ", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" })}</time><div><b>{row.title}</b><p>{row.body || row.type}</p><small>{row.actorName || "النظام"}</small></div></article>)}{!rows.length && <p className="ajn-ex-no-data">لا يوجد نشاط مسجل بعد.</p>}</div>; }
