import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, Route, Switch, useLocation } from "wouter";
import { Banknote, ClipboardList, FileText, GraduationCap, HandCoins, LogOut, Search, Users, UserRoundCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { apiErrorMessage, adminFetch, fetchAdminMe, formatCurrency, hasPerm, logoutAdmin, type AdminMe } from "@/views/admin/_lib";
import { useToast } from "@/hooks/use-toast";

const api = <T,>(path: string, init?: RequestInit) => adminFetch<T>(`/admin/representative${path}`, init);
const statusLabel: Record<string, string> = { unpaid: "غير مدفوع", partial: "مدفوع جزئياً", paid: "مدفوع بالكامل", new: "تم الإنشاء", awaiting_measurements: "بانتظار القياسات", ready: "جاهز", delivered: "تم التسليم", pending: "بانتظار" };

function PortalGate({ children }: { children: React.ReactNode }) {
  const [, navigate] = useLocation();
  const me = useQuery({ queryKey: ["representative", "me"], queryFn: () => fetchAdminMe({ force: true }) });
  if (me.isLoading) return <div className="min-h-dvh p-6" dir="rtl"><Skeleton className="h-96" /></div>;
  if (!me.data) { navigate("/admin/login"); return null; }
  if (!hasPerm(me.data, "representative.portal.access")) return <main className="grid min-h-dvh place-items-center bg-muted p-6" dir="rtl"><Card className="max-w-md"><CardContent className="p-7 text-center"><GraduationCap className="mx-auto mb-3 h-10 w-10 text-primary" /><h1 className="text-xl font-bold">بوابة ممثلي الشعب</h1><p className="mt-2 text-sm text-muted-foreground">تواصل مع الإدارة لمنح حسابك صلاحية الدخول إلى البوابة.</p></CardContent></Card></main>;
  return <Shell user={me.data}>{children}</Shell>;
}

function Shell({ user, children }: { user: AdminMe; children: React.ReactNode }) {
  const [, navigate] = useLocation();
  return <div className="min-h-dvh bg-muted/35" dir="rtl"><header className="sticky top-0 z-20 border-b bg-background/95 backdrop-blur"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-primary text-primary-foreground"><GraduationCap className="h-5 w-5" /></span><div><strong>بوابة ممثلي الشعب</strong><p className="text-xs text-muted-foreground">{user.fullName || user.username}</p></div></div><Button variant="ghost" size="sm" onClick={async () => { await logoutAdmin(); navigate("/admin/login"); }}><LogOut className="ml-2 h-4 w-4" />خروج</Button></div></header><div className="mx-auto grid max-w-7xl gap-5 p-4 lg:grid-cols-[210px_1fr]"><aside className="rounded-xl border bg-card p-2 lg:sticky lg:top-20 lg:h-fit"><nav className="grid gap-1"><Link href="/representative" className="rounded-lg px-3 py-2 text-sm hover:bg-muted">الرئيسية</Link><Link href="/representative/students" className="rounded-lg px-3 py-2 text-sm hover:bg-muted">الطلبة</Link><Link href="/representative/payments" className="rounded-lg px-3 py-2 text-sm hover:bg-muted">الدفعات والعهدة</Link><Link href="/representative/reports" className="rounded-lg px-3 py-2 text-sm hover:bg-muted">التقارير</Link>{user.role === "admin" && <Link href="/representative/assignments" className="rounded-lg px-3 py-2 text-sm hover:bg-muted">تعيين الممثلين</Link>}</nav></aside><main className="min-w-0">{children}</main></div></div>;
}

function Dashboard() {
  const data = useQuery({ queryKey: ["representative", "dashboard"], queryFn: () => api<any>("/dashboard") });
  if (data.isLoading) return <Skeleton className="h-96" />; if (data.error) return <ErrorState error={data.error} />;
  const d = data.data, s = d.stats;
  const metrics = [["عدد الطلبة", s.students, Users], ["القيمة الكلية", formatCurrency(s.total), Banknote], ["المستلم", formatCurrency(s.paid), HandCoins], ["المتبقي", formatCurrency(s.remaining), Banknote], ["عهدتك الحالية", formatCurrency(s.custody), ClipboardList]];
  return <div className="space-y-5"><section><h1 className="text-2xl font-bold">{d.groups?.[0]?.title || "مجموعاتي"}</h1><p className="mt-1 text-sm text-muted-foreground">{[d.groups?.[0]?.university,d.groups?.[0]?.college,d.groups?.[0]?.department,d.groups?.[0]?.graduationYear].filter(Boolean).join(" · ")}</p></section><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{metrics.map(([label,value,Icon]: any) => <Card key={String(label)}><CardContent className="flex items-center justify-between p-4"><div><p className="text-xs text-muted-foreground">{label}</p><strong className="mt-1 block text-lg">{value}</strong></div><Icon className="h-5 w-5 text-primary" /></CardContent></Card>)}</div><div className="grid gap-4 lg:grid-cols-2"><Progress title="نسبة التحصيل" value={s.collectionProgress} note={`${formatCurrency(s.paid)} من ${formatCurrency(s.total)}`} /><Card><CardContent className="p-5"><h2 className="font-semibold">حالة الطلبة</h2><div className="mt-4 grid grid-cols-3 gap-3 text-center text-sm"><Stat label="غير مدفوع" value={s.unpaid} /><Stat label="جزئي" value={s.partial} /><Stat label="مكتمل" value={s.paidFull} /><Stat label="قياسات ناقصة" value={s.incompleteMeasurements} /><Stat label="قيد التجهيز" value={s.inProduction} /><Stat label="جاهز" value={s.ready} /></div></CardContent></Card></div></div>;
}
function Progress({ title, value, note }: { title: string; value: number; note: string }) { return <Card><CardContent className="p-5"><div className="flex justify-between"><h2 className="font-semibold">{title}</h2><strong className="text-primary">{value}%</strong></div><div className="mt-5 h-3 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary transition-[width] duration-200" style={{ width: `${Math.min(100, value)}%` }} /></div><p className="mt-3 text-sm text-muted-foreground">{note}</p></CardContent></Card>; }
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-lg bg-muted p-3"><strong>{value}</strong><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>; }

function Students() {
  const [search,setSearch] = useState(""); const [selected,setSelected] = useState<any>(null);
  const query = useQuery({ queryKey: ["representative","students",search], queryFn: () => api<any>(`/students?search=${encodeURIComponent(search)}`) });
  return <div className="space-y-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl font-bold">الطلبة</h1><p className="text-sm text-muted-foreground">البحث بالاسم أو الهاتف أو الكود أو QR.</p></div><Button onClick={() => setSelected({})}><HandCoins className="ml-2 h-4 w-4" />تسجيل مبلغ مستلم</Button></div><div className="relative max-w-md"><Search className="absolute right-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pr-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="ابحث عن طالب" /></div><div className="overflow-x-auto rounded-xl border bg-card"><Table><TableHeader><TableRow><TableHead>الطالب</TableHead><TableHead>الكود</TableHead><TableHead>الباقة</TableHead><TableHead>الإجمالي</TableHead><TableHead>المستلم</TableHead><TableHead>المتبقي</TableHead><TableHead>الدفع</TableHead><TableHead>التجهيز</TableHead><TableHead /></TableRow></TableHeader><TableBody>{query.isLoading ? <TableRow><TableCell colSpan={9}><Skeleton className="h-8" /></TableCell></TableRow> : query.data?.items?.map((row: any) => <TableRow key={row.id}><TableCell><b>{row.name}</b><small className="block text-muted-foreground">{row.phone}</small></TableCell><TableCell>{row.studentCode}</TableCell><TableCell>{row.package}</TableCell><TableCell>{formatCurrency(row.total)}</TableCell><TableCell>{formatCurrency(row.paid)}</TableCell><TableCell>{formatCurrency(row.remaining)}</TableCell><TableCell>{statusLabel[row.paymentStatus] || row.paymentStatus}</TableCell><TableCell>{statusLabel[row.productionStatus] || row.productionStatus}</TableCell><TableCell><Button size="sm" variant="outline" onClick={() => setSelected(row)}>دفعة</Button></TableCell></TableRow>)}</TableBody></Table></div><PaymentDialog open={selected !== null} student={selected} onClose={() => setSelected(null)} /></div>;
}
function PaymentDialog({ open, student, onClose }: { open: boolean; student: any; onClose: () => void }) { const { toast } = useToast(); const qc=useQueryClient(); const [form,setForm]=useState({ amount:"",paymentMethod:"cash",receiptNumber:"",notes:"" }); const save=useMutation({ mutationFn:()=>api("/payments",{method:"POST",body:JSON.stringify({ orderId:student?.id, ...form })}), onSuccess:()=>{ toast({title:"تم تسجيل الدفعة بانتظار اعتماد الإدارة"}); qc.invalidateQueries({queryKey:["representative"]}); onClose(); },onError:(e)=>toast({title:"تعذر التسجيل",description:apiErrorMessage(e),variant:"destructive"}) }); return <Dialog open={open} onOpenChange={(v)=>!v&&onClose()}><DialogContent dir="rtl"><DialogHeader><DialogTitle>تسجيل مبلغ مستلم</DialogTitle></DialogHeader><p className="text-sm text-muted-foreground">{student?.name || "اختر الطالب من الجدول"}</p><Label>المبلغ</Label><Input inputMode="decimal" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} /><Label>طريقة الدفع</Label><Select value={form.paymentMethod} onValueChange={v=>setForm({...form,paymentMethod:v})}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="cash">نقدي</SelectItem><SelectItem value="transfer">تحويل</SelectItem><SelectItem value="card">بطاقة</SelectItem><SelectItem value="other">أخرى</SelectItem></SelectContent></Select><Label>رقم الوصل</Label><Input value={form.receiptNumber} onChange={e=>setForm({...form,receiptNumber:e.target.value})} /><Label>ملاحظات</Label><Textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} /><DialogFooter><Button onClick={()=>save.mutate()} disabled={!student?.id || !Number(form.amount) || save.isPending}>حفظ بانتظار الاعتماد</Button></DialogFooter></DialogContent></Dialog>; }
function printReceipt(receipt: any) { const tab = window.open("", "_blank", "noopener,noreferrer"); if (!tab) return; const snap = receipt.snapshot || {}; tab.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>${receipt.receiptNo}</title><style>body{font-family:Tahoma,Arial;padding:28px;color:#181b1f}article{max-width:560px;margin:auto;border:1px solid #ddd;padding:26px;border-radius:12px}h1{margin:0 0 18px}.row{display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid #eee}.amount{font-size:24px;font-weight:bold;color:#16734b}</style></head><body><article><h1>مجموعة علي جان نهاد</h1><p>وصل استلام دفعة — ${receipt.receiptNo}</p><div class="row"><span>الطالب</span><b>${receipt.studentName || ""}</b></div><div class="row"><span>المجموعة</span><b>${receipt.groupTitle || ""}</b></div><div class="row"><span>المبلغ</span><b class="amount">${receipt.amount || snap.paymentAmount || 0}</b></div><div class="row"><span>طريقة الدفع</span><b>${receipt.payment_method || snap.paymentMethod || ""}</b></div><div class="row"><span>الممثل</span><b>${receipt.representative_name || ""}</b></div><div class="row"><span>التاريخ</span><b>${new Date(receipt.approved_at || receipt.occurred_at).toLocaleString("ar-IQ")}</b></div></article><script>window.print()<\/script></body></html>`); tab.document.close(); }
function Payments() { const { toast }=useToast(); const qc=useQueryClient(); const [amount,setAmount]=useState(""); const list=useQuery({queryKey:["representative","payments"],queryFn:()=>api<any>("/payments")}); const save=useMutation({mutationFn:()=>api("/custody",{method:"POST",body:JSON.stringify({amount})}),onSuccess:()=>{toast({title:"تم إرسال طلب تسليم العهدة للإدارة"});setAmount("");qc.invalidateQueries({queryKey:["representative"]});},onError:e=>toast({title:"تعذر إرسال الطلب",description:apiErrorMessage(e),variant:"destructive"})}); const receipt=async(id:number)=>{try{printReceipt((await api<any>(`/payments/${id}/receipt`)).receipt)}catch(e){toast({title:"الوصل غير متاح",description:apiErrorMessage(e),variant:"destructive"});}}; return <div className="space-y-4"><h1 className="text-xl font-bold">الدفعات والعهدة</h1><Card><CardContent className="space-y-3 p-5"><h2 className="font-semibold">تسليم المبلغ للإدارة</h2><p className="text-sm text-muted-foreground">لا تصبح العهدة صفراً إلا بعد اعتماد الإدارة للاستلام.</p><Input value={amount} onChange={e=>setAmount(e.target.value)} inputMode="decimal" placeholder="المبلغ المسلّم" /><Button onClick={()=>save.mutate()} disabled={!Number(amount) || save.isPending}>إرسال طلب التسليم</Button></CardContent></Card><Card><CardContent className="p-0"><div className="border-b p-4 font-semibold">سجل الدفعات</div><div className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>الطالب</TableHead><TableHead>المبلغ</TableHead><TableHead>الطريقة</TableHead><TableHead>الحالة</TableHead><TableHead>الوصل</TableHead></TableRow></TableHeader><TableBody>{list.data?.items?.map((item:any)=><TableRow key={item.id}><TableCell>{item.studentName}</TableCell><TableCell>{formatCurrency(Number(item.amount))}</TableCell><TableCell>{item.payment_method}</TableCell><TableCell>{item.status === "approved" ? "معتمد" : item.status === "rejected" ? "مرفوض" : item.status === "pending" ? "بانتظار اعتماد الإدارة" : item.status}</TableCell><TableCell>{item.status === "approved" && <Button size="sm" variant="outline" onClick={()=>receipt(item.id)}>طباعة الوصل</Button>}</TableCell></TableRow>)}</TableBody></Table></div></CardContent></Card></div>; }
function Assignments() { const { toast }=useToast(); const qc=useQueryClient(); const q=useQuery({queryKey:["representative","assignments"],queryFn:()=>api<any>("/assignments")}); const [staffId,setStaffId]=useState(""); const [groupId,setGroupId]=useState(""); const save=useMutation({mutationFn:()=>api("/assignments",{method:"POST",body:JSON.stringify({staffId,groupId})}),onSuccess:()=>{toast({title:"تم تعيين ممثل الشعبة"});setStaffId("");setGroupId("");qc.invalidateQueries({queryKey:["representative","assignments"]});},onError:e=>toast({title:"تعذر الحفظ",description:apiErrorMessage(e),variant:"destructive"})}); return <div className="space-y-4"><div><h1 className="text-xl font-bold">تعيين ممثلي الشعب</h1><p className="text-sm text-muted-foreground">لا يستطيع الممثل الوصول إلى أي مجموعة قبل تعيينه هنا.</p></div><Card><CardContent className="grid gap-3 p-5 sm:grid-cols-3"><Select value={staffId} onValueChange={setStaffId}><SelectTrigger><SelectValue placeholder="اختر ممثلاً" /></SelectTrigger><SelectContent>{q.data?.staff?.map((s:any)=><SelectItem key={s.id} value={String(s.id)}>{s.fullName || s.username}</SelectItem>)}</SelectContent></Select><Select value={groupId} onValueChange={setGroupId}><SelectTrigger><SelectValue placeholder="اختر المجموعة" /></SelectTrigger><SelectContent>{q.data?.groups?.map((g:any)=><SelectItem key={g.id} value={String(g.id)}>{g.groupNo} — {g.title}</SelectItem>)}</SelectContent></Select><Button onClick={()=>save.mutate()} disabled={!staffId || !groupId || save.isPending}><UserRoundCheck className="ml-2 h-4 w-4"/>تعيين</Button></CardContent></Card><div className="overflow-x-auto rounded-xl border bg-card"><Table><TableHeader><TableRow><TableHead>الممثل</TableHead><TableHead>المجموعة</TableHead><TableHead>الحالة</TableHead></TableRow></TableHeader><TableBody>{q.data?.items?.map((x:any)=><TableRow key={x.id}><TableCell>{x.representativeName || x.representativeUsername}</TableCell><TableCell>{x.groupNo} — {x.groupTitle}</TableCell><TableCell>{x.isActive ? "مفعل" : "موقوف"}</TableCell></TableRow>)}</TableBody></Table></div></div>; }
function Reports() { const q=useQuery({queryKey:["representative","reports"],queryFn:()=>api<any>("/reports")}); const download=()=>{const rows=q.data?.items||[];const csv=["الطالب,الكود,الإجمالي,المستلم,المتبقي",...rows.map((x:any)=>[x.name,x.studentCode,x.total,x.paid,x.remaining].join(","))].join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="representative-students.csv";a.click();}; return <div className="space-y-4"><h1 className="text-xl font-bold">التقارير</h1><Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">قائمة الطلبة وحالات الدفع والأرصدة من سجلات المجموعة الحالية.</p><Button className="mt-4" onClick={download} disabled={!q.data}><FileText className="ml-2 h-4 w-4"/>تصدير CSV</Button></CardContent></Card></div>; }
function ErrorState({error}:{error:any}) { return <Card><CardContent className="p-6 text-destructive">{apiErrorMessage(error)}</CardContent></Card>; }
export default function RepresentativePortal() { return <PortalGate><Switch><Route path="/representative/students" component={Students}/><Route path="/representative/payments" component={Payments}/><Route path="/representative/reports" component={Reports}/><Route path="/representative/assignments" component={Assignments}/><Route component={Dashboard}/></Switch></PortalGate>; }
