import { useEffect, useState } from "react";
import { Link } from "wouter";
import { Bell, CalendarDays, Check, CircleDollarSign, Clock3, Download, FileText, Heart, MessageCircle, Palette, Send, Sparkles } from "lucide-react";
import { formatCurrency } from "@/lib/money";

type Portal = any;
type Locale = "ar" | "ku" | "tr";

const copy = {
  ar: { title: "بوابة العروس", welcome: "مرحباً", remaining: "متبقياً على المناسبة", services: "خدمات مناسبتك", journey: "رحلة التجهيز", finance: "مركز الدفعات", schedule: "جدول المناسبة", notes: "طلبات وملاحظات", chat: "المحادثة", documents: "المستندات", send: "إرسال", login: "تسجيل الدخول", unavailable: "تظهر البوابة بعد تأكيد الحجز.", home: "الرئيسية", payments: "الدفعات", share: "مشاركة", noDocuments: "لا توجد مستندات جاهزة الآن.", write: "اكتبي رسالتك لفريق AJN…", requestHint: "تتحول رسالتك إلى مهمة منظمة للفريق مع إشعار وسجل متابعة.", total: "الإجمالي", paid: "المدفوع", due: "المتبقي", nextDue: "الاستحقاق القادم" },
  ku: { title: "پۆرتاڵی بووک", welcome: "بەخێربێیت", remaining: "ماوە بۆ بۆنەکە", services: "خزمەتگوزارییەکانی بۆنەکەت", journey: "گەشتی ئامادەکاری", finance: "ناوەندی پارەدان", schedule: "خشتەی بۆنە", notes: "داواکاری و تێبینی", chat: "گفتوگۆ", documents: "بەڵگەنامەکان", send: "ناردن", login: "چوونەژوورەوە", unavailable: "پۆرتاڵەکە دوای پشتڕاستکردنەوەی حجزەکەت دەردەکەوێت.", home: "سەرەکی", payments: "پارەدان", share: "بڵاوکردنەوە", noDocuments: "لە ئێستادا بەڵگەنامەیەک ئامادە نییە.", write: "نامەیەک بۆ تیمی AJN بنووسە…", requestHint: "نامەکەت دەگۆڕدرێت بۆ ئەرک و ئاگادارکردنەوەی تیم.", total: "کۆی گشتی", paid: "دراو", due: "ماوە", nextDue: "بەرواری داهاتوو" },
  tr: { title: "Gelin Portalı", welcome: "Hoş geldiniz", remaining: "etkinliğe kaldı", services: "Etkinlik hizmetleriniz", journey: "Hazırlık yolculuğu", finance: "Ödeme merkezi", schedule: "Etkinlik programı", notes: "Talepler ve notlar", chat: "Mesajlar", documents: "Belgeler", send: "Gönder", login: "Giriş", unavailable: "Panel, rezervasyon onaylandıktan sonra görünür.", home: "Ana sayfa", payments: "Ödemeler", share: "Paylaş", noDocuments: "Henüz hazır belge yok.", write: "AJN ekibine mesajınızı yazın…", requestHint: "Mesajınız ekip için takip edilebilir bir göreve dönüşür.", total: "Toplam", paid: "Ödenen", due: "Kalan", nextDue: "Sonraki vade" },
} as const;

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`/api/customer/bride${path}`, { credentials: "include", headers: init?.body ? { "content-type": "application/json" } : undefined, ...init });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw Object.assign(new Error(data.error || "تعذر التحميل"), { auth: response.status === 401 });
  return data;
}

function Countdown({ date, locale }: { date?: string; locale: Locale }) {
  const [now, setNow] = useState(Date.now());
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, []);
  const seconds = Math.max(0, Math.floor((new Date(`${date || ""}T00:00:00`).getTime() - now) / 1000));
  const labels = locale === "tr" ? ["Gün", "Saat", "Dakika", "Saniye"] : locale === "ku" ? ["ڕۆژ", "کاتژمێر", "خولەک", "چرکە"] : ["يوم", "ساعة", "دقيقة", "ثانية"];
  const values = [Math.floor(seconds / 86400), Math.floor(seconds / 3600) % 24, Math.floor(seconds / 60) % 60, seconds % 60];
  return <div className="grid grid-cols-4 gap-2 text-center">{values.map((value, index) => <div key={labels[index]} className="rounded-xl border border-background/15 bg-background/10 px-1 py-3 backdrop-blur"><b className="block text-xl tabular-nums sm:text-2xl">{String(value).padStart(2, "0")}</b><span className="mt-1 block text-[10px] opacity-70">{labels[index]}</span></div>)}</div>;
}

export default function BrideDashboard() {
  const [data, setData] = useState<Portal | null>(null);
  const [error, setError] = useState<any>(null);
  const [locale, setLocale] = useState<Locale>("ar");
  const [tab, setTab] = useState("home");
  const t = copy[locale];
  const direction = locale === "tr" ? "ltr" : "rtl";
  useEffect(() => { api<Portal>("").then(setData).catch(setError); }, []);
  if (error?.auth) return <Empty dir={direction} title={t.title} description={t.unavailable} action={<Link href="/login" className="mt-5 inline-flex rounded-lg bg-primary px-5 py-3 font-semibold text-primary-foreground">{t.login}</Link>} />;
  if (error) return <Empty dir={direction} title={t.title} description={error.message || t.unavailable} />;
  if (!data) return <main className="grid min-h-dvh place-items-center"><Clock3 className="h-6 w-6 animate-spin text-primary" /></main>;
  const booking = data.booking;
  const nav = [["home", t.home, Sparkles], ["services", t.services, Heart], ["finance", t.payments, CircleDollarSign], ["schedule", t.schedule, CalendarDays], ["documents", t.documents, FileText], ["chat", t.chat, MessageCircle], ["notes", t.notes, Palette]] as const;
  return <main className="min-h-dvh bg-muted/30 pb-8" dir={direction} lang={locale}>
    <header className="sticky top-0 z-20 border-b bg-background/90 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-4 py-3"><div><p className="text-xs text-muted-foreground">AJN</p><h1 className="font-bold">{t.title}</h1></div><div className="flex items-center gap-2"><select aria-label="اللغة" value={locale} onChange={(event) => setLocale(event.target.value as Locale)} className="h-9 rounded-md border bg-background px-2 text-xs"><option value="ar">العربية</option><option value="ku">کوردی</option><option value="tr">Türkçe</option></select><button className="grid h-9 w-9 place-items-center rounded-md border" aria-label="الإشعارات"><Bell className="h-4 w-4" /></button></div></div></header>
    <div className="mx-auto max-w-6xl px-4 py-5">
      <section className="overflow-hidden rounded-2xl bg-foreground px-5 py-6 text-background shadow-xl shadow-foreground/10 sm:px-8"><div className="grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><div><p className="text-sm opacity-70">{t.welcome}، {booking.brideName}</p><h2 className="mt-2 text-3xl font-bold text-background">{booking.brideName}{booking.groomName ? ` × ${booking.groomName}` : ""}</h2><p className="mt-3 text-sm opacity-75">{booking.packageName} · {booking.hall || "AJN"}</p><div className="mt-5 flex flex-wrap gap-x-5 gap-y-2 text-sm"><span><CalendarDays className="ml-1 inline h-4 w-4" />{booking.date || "—"}</span><span>#{booking.number}</span><span>{booking.status}</span></div></div><div><p className="mb-3 text-sm font-semibold">{t.remaining}</p><Countdown date={booking.date} locale={locale} /></div></div></section>
      <nav className="mt-4 flex gap-1 overflow-x-auto border-b pb-2">{nav.map(([key, label, Icon]) => <button key={key} onClick={() => setTab(key)} className={`flex shrink-0 items-center gap-2 rounded-md px-3 py-2 text-sm ${tab === key ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-background"}`}><Icon className="h-4 w-4" />{label}</button>)}</nav>
      {tab === "home" && <Home data={data} t={t} />}
      {tab === "services" && <Services services={data.services} t={t} />}
      {tab === "finance" && <Finance data={data} t={t} />}
      {tab === "schedule" && <Schedule schedule={data.schedule} t={t} />}
      {tab === "documents" && <Documents documents={data.documents || []} t={t} />}
      {tab === "chat" && <Chat t={t} />}
      {tab === "notes" && <RequestForm bookingId={booking.id} t={t} />}
    </div>
  </main>;
}

function Empty({ dir, title, description, action }: { dir: string; title: string; description: string; action?: React.ReactNode }) { return <main className="grid min-h-dvh place-items-center p-6 text-center" dir={dir}><div><Sparkles className="mx-auto mb-4 h-10 w-10 text-primary" /><h1 className="text-2xl font-bold">{title}</h1><p className="mt-2 text-muted-foreground">{description}</p>{action}</div></main>; }
function Home({ data, t }: { data: Portal; t: any }) { return <div className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_.6fr]"><div className="space-y-5"><Services services={data.services.slice(0, 4)} t={t} /><section className="rounded-xl border bg-card p-5"><div className="flex items-center justify-between"><h2 className="font-bold">{t.journey}</h2><span className="text-xs text-muted-foreground">{data.booking.status}</span></div><ol className="mt-5 grid gap-3 sm:grid-cols-3">{data.timeline.map((item: any) => <li key={item.key} className="flex gap-3"><span className={`grid h-6 w-6 shrink-0 place-items-center rounded-full text-xs ${item.done ? "bg-status-success text-white" : "bg-muted text-muted-foreground"}`}>{item.done && <Check className="h-4 w-4" />}</span><div><b className="text-sm">{item.title}</b><p className="text-xs text-muted-foreground">{item.employee}</p></div></li>)}</ol></section></div><aside className="rounded-xl border bg-card p-5"><h2 className="font-bold">{t.finance}</h2><dl className="mt-4 space-y-3"><Row label={t.total} value={formatCurrency(data.booking.total)} /><Row label={t.paid} value={formatCurrency(data.booking.paid)} /><Row label={t.due} value={formatCurrency(data.booking.remaining)} strong /></dl>{data.booking.dueDate && <p className="mt-4 rounded-lg bg-muted p-3 text-xs">{t.nextDue}: {data.booking.dueDate}</p>}</aside></div>; }
function Services({ services, t }: { services: any[]; t: any }) { return <section className="rounded-xl border bg-card"><div className="flex items-center justify-between border-b px-5 py-4"><h2 className="font-bold">{t.services}</h2><span className="text-xs text-muted-foreground">{services.length}</span></div><div className="divide-y">{services.map((service: any) => <div className="flex items-center justify-between gap-3 px-5 py-4" key={service.key}><div className="flex min-w-0 items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-primary/10 text-primary"><Heart className="h-4 w-4" /></span><div><b className="block text-sm">{service.title}</b><small className="text-muted-foreground">{service.team}</small></div></div><span className="text-xs text-muted-foreground">{service.deliveryDate || service.status}</span></div>)}</div></section>; }
function Finance({ data, t }: { data: Portal; t: any }) { return <section className="mt-5 grid gap-5 lg:grid-cols-2"><div className="rounded-xl border bg-card p-5"><h2 className="font-bold">{t.finance}</h2><dl className="mt-4 space-y-3"><Row label={t.total} value={formatCurrency(data.booking.total)} /><Row label={t.paid} value={formatCurrency(data.booking.paid)} /><Row label={t.due} value={formatCurrency(data.booking.remaining)} strong /></dl><button type="button" disabled className="mt-5 w-full cursor-not-allowed rounded-lg bg-muted px-4 py-3 text-sm font-semibold text-muted-foreground">الدفع الإلكتروني قريباً</button></div><div className="rounded-xl border bg-card p-5"><h2 className="font-bold">الفواتير والوصولات</h2><div className="mt-3 divide-y">{data.invoices.length ? data.invoices.map((invoice: any) => <div key={invoice.id} className="flex items-center justify-between py-3 text-sm"><span className="font-mono">{invoice.no}</span><span>{formatCurrency(invoice.remaining)} {t.due}</span><FileText className="h-4 w-4 text-primary" /></div>) : <p className="py-3 text-sm text-muted-foreground">لا توجد فواتير.</p>}</div></div></section>; }
function Schedule({ schedule, t }: { schedule: any; t: any }) { const entries = Object.entries(schedule || {}); return <section className="mt-5 rounded-xl border bg-card p-5"><h2 className="font-bold">{t.schedule}</h2>{entries.length ? <dl className="mt-4 grid gap-3 sm:grid-cols-2">{entries.map(([label, value]) => <Row key={label} label={label} value={String(value)} />)}</dl> : <p className="mt-3 text-sm text-muted-foreground">سيظهر جدول الوصول والتنفيذ بعد اعتماده من فريق AJN.</p>}</section>; }
function Documents({ documents, t }: { documents: any[]; t: any }) { return <section className="mt-5 rounded-xl border bg-card p-5"><h2 className="font-bold">{t.documents}</h2><div className="mt-3 divide-y">{documents.length ? documents.map((document) => <a key={document.id} href={document.url} target="_blank" rel="noreferrer" className="flex items-center justify-between gap-3 py-3 text-sm hover:text-primary"><span><FileText className="ml-2 inline h-4 w-4" />{document.title}</span><Download className="h-4 w-4" /></a>) : <p className="py-3 text-sm text-muted-foreground">{t.noDocuments}</p>}</div></section>; }
function Chat({ t }: { t: any }) { const [messages, setMessages] = useState<any[]>([]); const [body, setBody] = useState(""); const [sending, setSending] = useState(false); useEffect(() => { api<any>("/chat").then((value) => setMessages(value.messages || [])).catch(() => undefined); }, []); const send = async () => { if (!body.trim() || sending) return; setSending(true); try { const result = await api<any>("/chat", { method: "POST", body: JSON.stringify({ body }) }); setMessages((current) => [...current, result.message]); setBody(""); } finally { setSending(false); } }; return <section className="mt-5 rounded-xl border bg-card p-5"><h2 className="font-bold">{t.chat}</h2><div className="mt-4 max-h-80 min-h-40 space-y-2 overflow-y-auto rounded-lg bg-muted/50 p-3">{messages.length ? messages.map((message) => <div key={message.id} className={`max-w-[85%] rounded-lg px-3 py-2 text-sm ${message.senderType === "customer" ? "mr-auto bg-primary text-primary-foreground" : "bg-background"}`}>{message.body}</div>) : <p className="text-sm text-muted-foreground">ابدئي محادثة مع فريق AJN.</p>}</div><div className="mt-3 flex gap-2"><input value={body} onChange={(event) => setBody(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void send(); }} className="h-10 min-w-0 flex-1 rounded-lg border bg-background px-3 text-sm" placeholder={t.write} /><button onClick={() => void send()} disabled={sending} className="grid h-10 w-10 place-items-center rounded-lg bg-primary text-primary-foreground disabled:opacity-50" aria-label={t.send}><Send className="h-4 w-4" /></button></div></section>; }
function RequestForm({ bookingId, t }: { bookingId: number; t: any }) { const [body, setBody] = useState(""); const [sent, setSent] = useState(false); const submit = async () => { if (body.trim().length < 3) return; await api("/requests", { method: "POST", body: JSON.stringify({ bookingId, type: "note", department: "support", body }) }); setBody(""); setSent(true); }; return <section className="mt-5 max-w-2xl rounded-xl border bg-card p-5"><h2 className="font-bold">{t.notes}</h2><p className="mt-1 text-sm text-muted-foreground">{t.requestHint}</p><textarea value={body} onChange={(event) => setBody(event.target.value)} className="mt-4 min-h-32 w-full rounded-lg border bg-background p-3 text-sm" placeholder={t.write} /><button onClick={() => void submit()} className="mt-3 inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground"><Send className="h-4 w-4" />{t.send}</button>{sent && <p className="mt-3 text-sm text-status-success">تم إرسال الطلب.</p>}</section>; }
function Row({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <div className={`flex items-center justify-between gap-3 text-sm ${strong ? "font-bold" : ""}`}><dt className="text-muted-foreground">{label}</dt><dd className="text-left tabular-nums">{value}</dd></div>; }
