"use client";

import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { motion, useReducedMotion } from "framer-motion";
import {
  Bell, CalendarDays, CheckCircle2, ChevronLeft, CircleDollarSign, ClipboardCheck,
  Clock3, FileText, Flower2, Heart, Image, MessageCircle, Package, Plus, Receipt,
  Send, ShoppingBag, Sparkles, Users, WalletCards,
} from "lucide-react";
import { formatCurrency } from "@/lib/money";

type WorkspaceItem = { id: number; kind: string; title: string; status: string; data: Record<string, unknown>; created_at?: string; updated_at?: string };
type Portal = {
  customer: { id: number; name: string; role?: string };
  booking: { id: number; number: string; brideName: string; groomName: string; date?: string; time?: string; hall?: string; packageName?: string; status: string; total: number; paid: number; remaining: number; dueDate?: string };
  services: Array<{ key: string; title: string; status: string; team: string; deliveryDate?: string; preview?: string | null }>;
  timeline: Array<{ key: string; title: string; done: boolean; employee: string; time?: string | null }>;
  invoices: Array<{ id: number; no: string; total: number; paid: number; remaining: number; status: string; date?: string }>;
  schedule: Record<string, string>;
  contacts: Array<{ key: string; title: string }>;
  workspaceItems: WorkspaceItem[];
};

const labels = {
  ar: { title: "مساحة زفافنا", home: "الرئيسية", plan: "الخطة", money: "الميزانية", guests: "الضيوف", services: "الخدمات", memories: "الذكريات", chat: "المحادثات", signIn: "تسجيل الدخول", empty: "تظهر مساحة الزفاف بعد تأكيد الحجز." },
  ku: { title: "شوێنی هاوسەرگیریمان", home: "سەرەکی", plan: "پلان", money: "بودجە", guests: "میوانەکان", services: "خزمەتگوزاری", memories: "یادگارەکان", chat: "پەیوەندی", signIn: "چوونەژوورەوە", empty: "دوای پشتڕاستکردنەوەی حجزەکە شوێنەکەت دەردەکەوێت." },
  tr: { title: "Düğün alanımız", home: "Ana sayfa", plan: "Plan", money: "Bütçe", guests: "Misafirler", services: "Hizmetler", memories: "Anılar", chat: "Mesajlar", signIn: "Giriş", empty: "Alanınız rezervasyon onayından sonra açılır." },
} as const;

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`/api/customer/wedding${path}`, { credentials: "include", headers: init?.body ? { "content-type": "application/json" } : undefined, ...init });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw Object.assign(new Error(data.error || "تعذر تحميل مساحة الزفاف"), { auth: response.status === 401 });
  return data;
}

const card = "rounded-xl border border-border bg-card";
const statusTone = (status: string) => status === "done" || status === "paid" || status === "approved" ? "bg-status-success/10 text-status-success" : status === "pending" ? "bg-status-warning/10 text-status-warning" : "bg-muted text-muted-foreground";

function usePortal() {
  const [data, setData] = useState<Portal | null>(null); const [error, setError] = useState<any>(null);
  const refresh = () => api<Portal>("").then(setData).catch(setError);
  useEffect(() => { refresh(); const timer = window.setInterval(refresh, 30000); return () => window.clearInterval(timer); }, []);
  return { data, error, refresh };
}

function Countdown({ date }: { date?: string }) {
  const [now, setNow] = useState(Date.now());
  useEffect(() => { const timer = window.setInterval(() => setNow(Date.now()), 1000); return () => window.clearInterval(timer); }, []);
  const remaining = Math.max(0, new Date(`${date ?? ""}T00:00:00`).getTime() - now);
  const units = [["يوم", Math.floor(remaining / 86400000)], ["ساعة", Math.floor(remaining / 3600000) % 24], ["دقيقة", Math.floor(remaining / 60000) % 60]];
  return <div className="flex gap-2" dir="rtl">{units.map(([label, value]) => <div key={String(label)} className="min-w-15 rounded-lg bg-white/10 px-2 py-2 text-center"><b className="block text-lg tabular-nums">{String(value).padStart(2, "0")}</b><small className="text-[10px] text-white/70">{label}</small></div>)}</div>;
}

function AddItem({ bookingId, kind, onAdded }: { bookingId: number; kind: WorkspaceItem["kind"]; onAdded: () => void }) {
  const [open, setOpen] = useState(false); const [title, setTitle] = useState(""); const [amount, setAmount] = useState(""); const [category, setCategory] = useState("متفرقات"); const [saving, setSaving] = useState(false);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!title.trim()) return; setSaving(true); try { await api("/workspace/items", { method: "POST", body: JSON.stringify({ bookingId, kind, title, status: kind === "expense" ? "paid" : "pending", data: kind === "expense" ? { amount: Number(amount || 0), category } : {} }) }); setTitle(""); setAmount(""); setOpen(false); onAdded(); } finally { setSaving(false); } };
  return <>{open ? <form onSubmit={submit} className="mt-3 flex flex-wrap gap-2 rounded-lg bg-muted/60 p-3"><input autoFocus value={title} onChange={(e) => setTitle(e.target.value)} className="min-w-50 flex-1 rounded-md border bg-background px-3 py-2 text-sm" placeholder={kind === "checklist" ? "أضيفي مهمة" : kind === "guest" ? "اسم الضيف" : "أضيفي عنصراً"} />{kind === "expense" && <><input inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} className="w-28 rounded-md border bg-background px-3 py-2 text-sm" placeholder="المبلغ" /><select value={category} onChange={(e) => setCategory(e.target.value)} className="rounded-md border bg-background px-2 py-2 text-sm"><option>متفرقات</option><option>فستان</option><option>مجوهرات</option><option>سفر</option><option>دعوات</option></select></>}<button disabled={saving} className="rounded-md bg-primary px-3 py-2 text-sm font-semibold text-primary-foreground">حفظ</button><button type="button" onClick={() => setOpen(false)} className="rounded-md px-3 py-2 text-sm">إلغاء</button></form> : <button onClick={() => setOpen(true)} className="inline-flex items-center gap-1 rounded-md border border-primary/30 px-3 py-2 text-sm font-semibold text-primary"><Plus className="h-4 w-4" /> إضافة</button>}</>;
}

export default function WeddingOS() {
  const { data, error, refresh } = usePortal(); const [locale, setLocale] = useState<keyof typeof labels>("ar"); const [tab, setTab] = useState("home"); const [message, setMessage] = useState(""); const reduceMotion = useReducedMotion();
  const t = labels[locale]; const direction = locale === "tr" ? "ltr" : "rtl";
  if (error?.auth) return <Gate title={t.title} text={t.empty} action={t.signIn} dir={direction} />;
  if (error) return <Gate title={t.title} text={error.message} dir={direction} />;
  if (!data) return <main className="grid min-h-dvh place-items-center" dir={direction}><Clock3 className="h-6 w-6 animate-spin text-primary" /></main>;
  const b = data.booking; const items = data.workspaceItems || [];
  const checklist = items.filter((i) => i.kind === "checklist"); const expenses = items.filter((i) => i.kind === "expense"); const guests = items.filter((i) => i.kind === "guest"); const wishes = items.filter((i) => i.kind === "wishlist");
  const complete = checklist.filter((item) => item.status === "done").length; const personalSpend = expenses.reduce((sum, item) => sum + Number(item.data?.amount || 0), 0); const progress = checklist.length ? Math.round((complete / checklist.length) * 100) : Math.min(100, Math.round((b.paid / Math.max(1, b.total)) * 100));
  const nav = [["home", t.home, Sparkles], ["plan", t.plan, ClipboardCheck], ["money", t.money, WalletCards], ["guests", t.guests, Users], ["services", t.services, Package], ["memories", t.memories, Image], ["chat", t.chat, MessageCircle]];
  const sendMessage = async () => { if (!message.trim()) return; await api("/requests", { method: "POST", body: JSON.stringify({ bookingId: b.id, type: "note", department: "support", body: message }) }); setMessage(""); };
  return <main className="min-h-dvh bg-background text-foreground" dir={direction} lang={locale}>
    <header className="sticky top-0 z-20 border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/85"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between gap-3 px-4"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-primary text-sm font-bold text-primary-foreground">AJN</span><div><h1 className="text-sm font-bold">{t.title}</h1><p className="text-xs text-muted-foreground">{b.number}</p></div></div><div className="flex items-center gap-2"><select aria-label="اللغة" value={locale} onChange={(e) => setLocale(e.target.value as keyof typeof labels)} className="h-9 rounded-md border bg-background px-2 text-xs"><option value="ar">العربية</option><option value="ku">کوردی</option><option value="tr">Türkçe</option></select><button aria-label="الإشعارات" className="grid h-9 w-9 place-items-center rounded-md border"><Bell className="h-4 w-4" /></button></div></div></header>
    <div className="mx-auto grid max-w-7xl gap-5 px-4 py-5 lg:grid-cols-[190px_minmax(0,1fr)]">
      <nav className="flex gap-1 overflow-x-auto lg:flex-col lg:overflow-visible">{nav.map(([key, label, Icon]: any) => <button key={key} onClick={() => setTab(key)} className={`flex shrink-0 items-center gap-2 rounded-md px-3 py-2.5 text-sm transition-colors ${tab === key ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted hover:text-foreground"}`}><Icon className="h-4 w-4" />{label}</button>)}</nav>
      <section className="min-w-0">{tab === "home" && <HomeView booking={b} services={data.services} timeline={data.timeline} progress={progress} reduceMotion={reduceMotion} />}{tab === "plan" && <PlanView bookingId={b.id} items={checklist} refresh={refresh} />}{tab === "money" && <MoneyView booking={b} invoices={data.invoices} expenses={expenses} spent={personalSpend} refresh={refresh} />}{tab === "guests" && <GuestsView bookingId={b.id} items={guests} refresh={refresh} />}{tab === "services" && <ServicesView services={data.services} />}{tab === "memories" && <MemoriesView wishes={wishes} bookingId={b.id} refresh={refresh} />}{tab === "chat" && <ChatView contacts={data.contacts} message={message} setMessage={setMessage} send={sendMessage} />}</section>
    </div>
  </main>;
}

function Gate({ title, text, action, dir }: { title: string; text: string; action?: string; dir: string }) { return <main className="grid min-h-dvh place-items-center bg-background p-6 text-center" dir={dir}><div className="max-w-sm"><Heart className="mx-auto h-10 w-10 text-primary" /><h1 className="mt-4 text-xl font-bold">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{text}</p>{action && <Link href="/login" className="mt-5 inline-flex rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground">{action}</Link>}</div></main>; }
function HomeView({ booking, services, timeline, progress, reduceMotion }: any) { return <div className="space-y-5"><motion.section initial={reduceMotion ? false : { opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .2 }} className="overflow-hidden rounded-xl bg-foreground p-6 text-background"><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><p className="text-sm text-white/65">رحلة {booking.brideName} و {booking.groomName}</p><h2 className="mt-2 text-2xl font-bold text-white">كل ما يخص يومكما في مكان واحد</h2><p className="mt-3 text-sm text-white/70">{booking.packageName || "باقة الزفاف"} · {booking.hall || "القاعة بانتظار التأكيد"}</p></div><Countdown date={booking.date} /></div></motion.section><div className="grid gap-4 md:grid-cols-3"><Metric label="نسبة التجهيز" value={`${progress}%`} detail="من الخطة والحجز" icon={ClipboardCheck} /><Metric label="المتبقي بالعقد" value={formatCurrency(booking.remaining)} detail={booking.dueDate ? `استحقاق ${booking.dueDate}` : "راجعا الدفعات"} icon={WalletCards} /><Metric label="موعد الزفاف" value={booking.date || "بانتظار التحديد"} detail={booking.time || ""} icon={CalendarDays} /></div><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><section className={card}><SectionTitle title="رحلة الزفاف" icon={Sparkles} /><ol className="divide-y px-5">{timeline.map((event: any) => <li key={event.key} className="flex gap-3 py-3"><span className={`mt-0.5 grid h-6 w-6 place-items-center rounded-full ${event.done ? "bg-status-success text-white" : "bg-muted text-muted-foreground"}`}>{event.done && <CheckCircle2 className="h-4 w-4" />}</span><div className="min-w-0"><b className="block text-sm">{event.title}</b><p className="mt-0.5 text-xs text-muted-foreground">{event.employee}{event.time ? ` · ${event.time}` : ""}</p></div></li>)}</ol></section><section className={card}><SectionTitle title="الخدمات المتصلة" icon={Package} /><div className="divide-y px-5">{services.slice(0, 5).map((service: any) => <div key={service.key} className="flex items-center justify-between gap-3 py-3"><div><b className="block text-sm">{service.title}</b><small className="text-muted-foreground">{service.team}</small></div><span className={`rounded-full px-2 py-1 text-xs ${statusTone(service.status)}`}>{service.status}</span></div>)}</div></section></div></div> }
function PlanView({ bookingId, items, refresh }: any) { return <section className={card}><SectionTitle title="قائمة التجهيز الذكية" icon={ClipboardCheck} action={<AddItem bookingId={bookingId} kind="checklist" onAdded={refresh} />} /><div className="divide-y px-5">{items.length ? items.map((item: WorkspaceItem) => <div key={item.id} className="flex items-center justify-between gap-3 py-3"><div className="flex items-center gap-3"><span className={`grid h-7 w-7 place-items-center rounded-full ${item.status === "done" ? "bg-status-success text-white" : "bg-muted"}`}><CheckCircle2 className="h-4 w-4" /></span><div><b className="block text-sm">{item.title}</b><small className="text-muted-foreground">{item.status === "done" ? "مكتملة" : "بانتظار التنفيذ"}</small></div></div><button onClick={async () => { await api(`/workspace/items/${item.id}`, { method: "PATCH", body: JSON.stringify({ status: item.status === "done" ? "pending" : "done" }) }); refresh(); }} className="rounded-md border px-3 py-1.5 text-xs">{item.status === "done" ? "إعادة فتح" : "إكمال"}</button></div>) : <Empty title="ابدآ خطة التجهيز" text="أضيفا أول مهمة، أو استخدما قائمة فريق AJN المقترحة." />}</div></section> }
function MoneyView({ booking, invoices, expenses, spent, refresh }: any) { return <div className="space-y-5"><div className="grid gap-4 md:grid-cols-3"><Metric label="إجمالي العقد" value={formatCurrency(booking.total)} detail="من الحجز" icon={Receipt} /><Metric label="المدفوع" value={formatCurrency(booking.paid)} detail="يسجل من الحسابات" icon={CheckCircle2} /><Metric label="مصروفاتكما الشخصية" value={formatCurrency(spent)} detail="لا تؤثر على محاسبة AJN" icon={CircleDollarSign} /></div><div className="grid gap-5 xl:grid-cols-2"><section className={card}><SectionTitle title="الفواتير والأقساط" icon={FileText} /><div className="divide-y px-5">{invoices.length ? invoices.map((invoice: any) => <div key={invoice.id} className="flex items-center justify-between py-3 text-sm"><span className="font-mono">{invoice.no}</span><span>{formatCurrency(invoice.remaining)} متبقي</span></div>) : <Empty title="لا توجد فواتير" text="ستظهر الفواتير المعتمدة من نظام AJN هنا." />}</div></section><section className={card}><SectionTitle title="متابعة المصروفات" icon={WalletCards} action={<AddItem bookingId={booking.id} kind="expense" onAdded={refresh} />} /><div className="divide-y px-5">{expenses.length ? expenses.map((expense: WorkspaceItem) => <div key={expense.id} className="flex justify-between py-3 text-sm"><span>{expense.title}</span><b>{formatCurrency(Number(expense.data?.amount || 0))}</b></div>) : <Empty title="لا توجد مصروفات شخصية" text="تُحفظ هنا ملاحظاتكما ومصروفاتكما الخاصة فقط." />}</div></section></div></div> }
function GuestsView({ bookingId, items, refresh }: any) { return <section className={card}><SectionTitle title="قائمة الضيوف" icon={Users} action={<AddItem bookingId={bookingId} kind="guest" onAdded={refresh} />} /><div className="divide-y px-5">{items.length ? items.map((guest: WorkspaceItem) => <div key={guest.id} className="flex items-center justify-between py-3"><div><b className="block text-sm">{guest.title}</b><small className="text-muted-foreground">دعوة بانتظار الإرسال</small></div><span className="rounded-full bg-muted px-2 py-1 text-xs">ضيف</span></div>) : <Empty title="ابدآ قائمة الضيوف" text="أضيفا الأسماء الآن، ثم يمكن لفريق AJN ربطها بالدعوات وأكواد الدخول." />}</div></section> }
function ServicesView({ services }: { services: Portal["services"] }) { const links = [{ title: "مصمم باقة الزهور", href: "/design", icon: Flower2 }, { title: "متجر AJN", href: "/store", icon: ShoppingBag }]; return <div className="space-y-5"><section className={card}><SectionTitle title="خدمات الزفاف" icon={Package} /><div className="divide-y px-5">{services.map((service) => <div key={service.key} className="flex items-center justify-between gap-3 py-4"><div><b className="block text-sm">{service.title}</b><p className="mt-1 text-xs text-muted-foreground">{service.team} · {service.deliveryDate || "موعد الخدمة يحدده الفريق"}</p></div><span className={`rounded-full px-2 py-1 text-xs ${statusTone(service.status)}`}>{service.status}</span></div>)}</div></section><div className="grid gap-4 sm:grid-cols-2">{links.map(({ title, href, icon: Icon }) => <Link key={href} href={href} className={`${card} flex items-center justify-between p-4 transition-colors hover:bg-muted/40`}><span className="flex items-center gap-3 font-semibold"><Icon className="h-5 w-5 text-primary" />{title}</span><ChevronLeft className="h-4 w-4 text-muted-foreground" /></Link>)}</div></div> }
function MemoriesView({ wishes, bookingId, refresh }: any) { return <div className="grid gap-5 xl:grid-cols-2"><section className={card}><SectionTitle title="قائمة الأمنيات" icon={Heart} action={<AddItem bookingId={bookingId} kind="wishlist" onAdded={refresh} />} /><div className="divide-y px-5">{wishes.length ? wishes.map((wish: WorkspaceItem) => <div className="py-3 text-sm" key={wish.id}>{wish.title}</div>) : <Empty title="احفظا ما يلهمكما" text="باقة، كوشة، كيكة أو منتج من المتجر." />}</div></section><section className={card}><SectionTitle title="خزانة الذكريات" icon={Image} /><div className="px-5 py-8"><Empty title="الصور والملفات الخاصة" text="بعد المناسبة ستظهر الألبومات والعقود والذكريات المعتمدة من فريق AJN هنا." /></div></section></div> }
function ChatView({ contacts, message, setMessage, send }: any) { const [department, setDepartment] = useState("support"); return <section className={`${card} max-w-3xl`}><SectionTitle title="مركز التواصل" icon={MessageCircle} /><div className="flex flex-wrap gap-2 px-5 py-3">{contacts.map((contact: any) => <button key={contact.key} onClick={() => setDepartment(contact.key)} className={`rounded-full px-3 py-1.5 text-xs ${department === contact.key ? "bg-primary text-primary-foreground" : "bg-muted text-muted-foreground"}`}>{contact.title}</button>)}</div><div className="border-t p-5"><textarea value={message} onChange={(event) => setMessage(event.target.value)} className="min-h-32 w-full rounded-md border bg-background p-3 text-sm" placeholder="اكتبا رسالتكما أو طلب التعديل…" /><button onClick={send} className="mt-3 inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground"><Send className="h-4 w-4" />إرسال إلى الفريق</button></div></section> }
function Metric({ label, value, detail, icon: Icon }: any) { return <section className={`${card} p-4`}><div className="flex items-start justify-between"><div><p className="text-xs text-muted-foreground">{label}</p><b className="mt-2 block text-lg tabular-nums">{value}</b><small className="mt-1 block text-xs text-muted-foreground">{detail}</small></div><span className="grid h-9 w-9 place-items-center rounded-lg bg-primary/10 text-primary"><Icon className="h-4 w-4" /></span></div></section> }
function SectionTitle({ title, icon: Icon, action }: { title: string; icon: any; action?: React.ReactNode }) { return <div className="flex items-center justify-between gap-3 border-b px-5 py-4"><h2 className="flex items-center gap-2 text-sm font-bold"><Icon className="h-4 w-4 text-primary" />{title}</h2>{action}</div> }
function Empty({ title, text }: { title: string; text: string }) { return <div className="py-8 text-center"><p className="font-semibold text-sm">{title}</p><p className="mx-auto mt-1 max-w-sm text-xs leading-5 text-muted-foreground">{text}</p></div> }
