import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BarChart3, ChefHat, ClipboardList, Clock3, Package, Plus, QrCode, Truck, UtensilsCrossed, Users, Wallet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { adminFetch, apiErrorMessage } from "./_lib";
import { useToast } from "@/hooks/use-toast";

type Stats = { events: number; revenue: number; profit: number; pending: number; preparing: number; ready: number; onWay: number; completed: number };
type Booking = { id:number; code:string; customerName:string; mobile1?:string; eventType:string; eventDate:string; hall?:string; guestCount:number; packageName?:string; totalAmount:number; estimatedCost:number; balanceAmount:number; status:string; notes?:string };
type Menu = { id:number; code:string; name:string; category:string; cost:number; selling_price:number; preparation_minutes:number };
type PackageRow = { id:number; name:string; tier:string; price:number; details:any };
const TABS = [{ key:"dashboard",label:"لوحة التحكم",icon:BarChart3 },{key:"bookings",label:"مركز الحجوزات",icon:ClipboardList},{key:"orders",label:"الطلبات",icon:UtensilsCrossed},{key:"events",label:"المناسبات",icon:Clock3},{key:"menu",label:"قوائم الطعام",icon:UtensilsCrossed},{key:"packages",label:"الباقات",icon:Package},{key:"items",label:"الأصناف",icon:Package},{key:"kitchen",label:"المطبخ والتحضير",icon:ChefHat},{key:"delivery",label:"التوصيل",icon:Truck},{key:"team",label:"الموظفون",icon:Users},{key:"assets",label:"السيارات والمعدات",icon:QrCode},{key:"inventory",label:"المخزن والمشتريات",icon:Package},{key:"accounting",label:"الفواتير والمالية",icon:Wallet},{key:"customers",label:"العملاء",icon:Users},{key:"reports",label:"التقارير",icon:BarChart3},{key:"settings",label:"الإعدادات",icon:ClipboardList}] as const;
const EVENT_LABEL:Record<string,string>={wedding:"زفاف",engagement:"خطوبة",henna:"حنّة",graduation:"تخرّج",birthday:"عيد ميلاد",corporate:"شركة",majlis:"مجلس",funeral:"فاتحة",custom:"مخصص"};
const STATUS:Record<string,string>={confirmed:"مؤكد",preparing:"قيد التحضير",ready:"جاهز",on_the_way:"في الطريق",completed:"مكتمل",cancelled:"ملغى"};
const input="w-full rounded-lg border border-border/40 bg-background px-3 py-2 text-sm outline-none focus:border-primary/60";

export default function CateringCenterPage() {
 const [tab,setTab]=useState<(typeof TABS)[number]["key"]>("dashboard"); const qc=useQueryClient(); const {toast}=useToast();
 const dashboard=useQuery<{stats:Stats}>({queryKey:["catering","dashboard"],queryFn:()=>adminFetch("/admin/catering/dashboard")});
 const bookings=useQuery<{bookings:Booking[]}>({queryKey:["catering","bookings"],queryFn:()=>adminFetch("/admin/catering/bookings")});
 const menu=useQuery<{items:Menu[]}>({queryKey:["catering","menu"],queryFn:()=>adminFetch("/admin/catering/menu"),enabled:tab==="menu"||tab==="items"});
 const packages=useQuery<{packages:PackageRow[]}>({queryKey:["catering","packages"],queryFn:()=>adminFetch("/admin/catering/packages"),enabled:tab==="packages"});
 const refresh=()=>{qc.invalidateQueries({queryKey:["catering"]});};
 return <div dir="rtl" className="space-y-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="flex items-center gap-2 text-2xl font-bold text-foreground"><UtensilsCrossed className="h-6 w-6 text-primary"/> تجهيز حفلات الطعام</h1><p className="mt-1 text-sm text-muted-foreground">AJN Catering Center — حجز، مطبخ، مخزن، فريق، توصيل ومالية من مركز واحد.</p></div><Button onClick={()=>setTab("bookings")}><Plus className="ml-1 h-4 w-4"/>حجز تجهيز جديد</Button></div>
 <div className="flex gap-1 overflow-x-auto border-b border-border/40 pb-px">{TABS.map(t=>{const I=t.icon;return <button key={t.key} onClick={()=>setTab(t.key)} className={`flex shrink-0 items-center gap-1.5 border-b-2 px-3 py-2 text-xs font-medium ${tab===t.key?"border-primary text-primary":"border-transparent text-muted-foreground hover:text-foreground"}`}><I className="h-3.5 w-3.5"/>{t.label}</button>})}</div>
 {tab==="dashboard"?<Dashboard stats={dashboard.data?.stats} loading={dashboard.isLoading}/>:tab==="bookings"?<Bookings rows={bookings.data?.bookings??[]} refresh={refresh}/>:tab==="menu"||tab==="items"?<MenuManager rows={menu.data?.items??[]} refresh={refresh}/>:tab==="packages"?<PackageManager rows={packages.data?.packages??[]} refresh={refresh}/>:tab==="kitchen"?<Kitchen rows={bookings.data?.bookings??[]} refresh={refresh}/>:tab==="delivery"?<Delivery rows={bookings.data?.bookings??[]} refresh={refresh}/>:<OperationalPage tab={tab} rows={bookings.data?.bookings??[]} />}
 </div>;
}
function Dashboard({stats,loading}:{stats?:Stats;loading:boolean}){if(loading)return <Skeleton className="h-48 rounded-xl"/>;const cards=[["حفلات اليوم",stats?.events],["إيراد اليوم",stats?.revenue],["ربح متوقع",stats?.profit],["دفعات معلّقة",stats?.pending],["قيد التحضير",stats?.preparing],["جاهز",stats?.ready],["في الطريق",stats?.onWay],["مكتمل",stats?.completed]];return <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{cards.map(([l,v])=><div key={String(l)} className="rounded-xl border border-border/30 bg-card p-4"><div className="text-2xl font-extrabold text-foreground">{Number(v??0).toLocaleString("ar-IQ")}</div><div className="mt-1 text-xs text-muted-foreground">{l}</div></div>)}<div className="col-span-full rounded-xl border border-primary/20 bg-primary/5 p-4 text-sm text-foreground"><b>الاقتراحات الذكية:</b> يعتمد تقدير الحصص على 110% من عدد الضيوف، ويرتّب أولوية التحضير حسب وقت بداية المناسبة وحالة المطبخ.</div></div>}
function Bookings({rows,refresh}:{rows:Booking[];refresh:()=>void}){const {toast}=useToast();const [f,setF]=useState({customerName:"",mobile1:"",eventType:"wedding",eventDate:"",guestCount:"",packageName:"",totalAmount:"",estimatedCost:"",hall:"",notes:""});const create=useMutation({mutationFn:()=>adminFetch("/admin/catering/bookings",{method:"POST",body:JSON.stringify({...f,guestCount:Number(f.guestCount),totalAmount:Number(f.totalAmount)||0,estimatedCost:Number(f.estimatedCost)||0,maleCount:0,femaleCount:0,childrenCount:0,vipCount:0})}),onSuccess:()=>{setF({...f,customerName:"",mobile1:"",eventDate:"",guestCount:""});refresh();toast({title:"تم إنشاء حجز التجهيز وتوليد QR"})},onError:(e:Error)=>toast({title:"تعذر حفظ الحجز",description:apiErrorMessage(e),variant:"destructive"})});return <div className="space-y-4"><section className="rounded-xl border border-border/30 bg-card p-4"><h2 className="mb-3 font-bold text-foreground">حجز تجهيز مباشر</h2><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><input className={input} placeholder="اسم العميل *" value={f.customerName} onChange={e=>setF({...f,customerName:e.target.value})}/><input className={input} dir="ltr" placeholder="موبايل 1" value={f.mobile1} onChange={e=>setF({...f,mobile1:e.target.value})}/><select className={input} value={f.eventType} onChange={e=>setF({...f,eventType:e.target.value})}>{Object.entries(EVENT_LABEL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><input className={input} type="date" value={f.eventDate} onChange={e=>setF({...f,eventDate:e.target.value})}/><input className={input} type="number" placeholder="عدد الضيوف *" value={f.guestCount} onChange={e=>setF({...f,guestCount:e.target.value})}/><input className={input} placeholder="الباقة" value={f.packageName} onChange={e=>setF({...f,packageName:e.target.value})}/><input className={input} type="number" placeholder="سعر البيع" value={f.totalAmount} onChange={e=>setF({...f,totalAmount:e.target.value})}/><input className={input} type="number" placeholder="الكلفة التقديرية" value={f.estimatedCost} onChange={e=>setF({...f,estimatedCost:e.target.value})}/><input className={input} placeholder="القاعة" value={f.hall} onChange={e=>setF({...f,hall:e.target.value})}/><input className={input} placeholder="ملاحظات المطبخ" value={f.notes} onChange={e=>setF({...f,notes:e.target.value})}/></div><Button className="mt-3" disabled={!f.customerName||!f.eventDate||!f.guestCount||create.isPending} onClick={()=>create.mutate()}><Plus className="ml-1 h-4 w-4"/>تأكيد الحجز</Button></section><BookingsTable rows={rows}/></div>}
function BookingsTable({rows}:{rows:Booking[]}){return <div className="overflow-x-auto rounded-xl border border-border/30 bg-card"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-border/30 text-xs text-muted-foreground">{["الرقم","العميل","المناسبة","التاريخ","الضيوف","الباقة","المبلغ","الحالة"].map(x=><th key={x} className="p-3 text-right">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-b border-border/15"><td className="p-3 font-mono text-xs">{r.code}</td><td className="p-3 font-medium">{r.customerName}</td><td className="p-3">{EVENT_LABEL[r.eventType]??r.eventType}</td><td className="p-3">{String(r.eventDate).slice(0,10)}</td><td className="p-3">{r.guestCount}</td><td className="p-3">{r.packageName||"—"}</td><td className="p-3">{r.totalAmount.toLocaleString("ar-IQ")}</td><td className="p-3"><span className="rounded-full bg-primary/10 px-2 py-1 text-xs text-primary">{STATUS[r.status]??r.status}</span></td></tr>)}</tbody></table></div>}
function MenuManager({rows,refresh}:{rows:Menu[];refresh:()=>void}){const {toast}=useToast();const [f,setF]=useState({code:"",name:"",category:"rice",cost:"",sellingPrice:"",preparationMinutes:""});const save=useMutation({mutationFn:()=>adminFetch("/admin/catering/menu",{method:"POST",body:JSON.stringify({...f,cost:Number(f.cost)||0,sellingPrice:Number(f.sellingPrice)||0,preparationMinutes:Number(f.preparationMinutes)||0})}),onSuccess:()=>{setF({code:"",name:"",category:"rice",cost:"",sellingPrice:"",preparationMinutes:""});refresh()},onError:(e:Error)=>toast({title:apiErrorMessage(e),variant:"destructive"})});return <div className="space-y-4"><section className="rounded-xl border border-border/30 bg-card p-4"><h2 className="mb-3 font-bold">إضافة صنف طعام</h2><div className="grid gap-2 sm:grid-cols-3 lg:grid-cols-6"><input className={input} placeholder="الكود" value={f.code} onChange={e=>setF({...f,code:e.target.value})}/><input className={input} placeholder="اسم الصنف" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><select className={input} value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{["rice","meat","chicken","fish","soup","salad","dessert","drinks","fruit","bakery"].map(x=><option key={x}>{x}</option>)}</select><input className={input} type="number" placeholder="الكلفة" value={f.cost} onChange={e=>setF({...f,cost:e.target.value})}/><input className={input} type="number" placeholder="سعر البيع" value={f.sellingPrice} onChange={e=>setF({...f,sellingPrice:e.target.value})}/><input className={input} type="number" placeholder="دقائق التحضير" value={f.preparationMinutes} onChange={e=>setF({...f,preparationMinutes:e.target.value})}/></div><Button className="mt-3" disabled={!f.code||!f.name} onClick={()=>save.mutate()}>حفظ الصنف</Button></section><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{rows.map(x=><div key={x.id} className="rounded-xl border border-border/30 bg-card p-3"><b>{x.name}</b><p className="mt-1 text-xs text-muted-foreground">{x.code} · {x.category} · {x.preparation_minutes} دقيقة</p><p className="mt-1 text-xs">كلفة {Number(x.cost).toLocaleString("ar-IQ")} · بيع {Number(x.selling_price).toLocaleString("ar-IQ")}</p></div>)}</div></div>}
function PackageManager({rows,refresh}:{rows:PackageRow[];refresh:()=>void}){const [name,setName]=useState("");const [tier,setTier]=useState("royal");const [price,setPrice]=useState("");const save=useMutation({mutationFn:()=>adminFetch("/admin/catering/packages",{method:"POST",body:JSON.stringify({name,tier,price:Number(price)||0,details:{foods:[],desserts:[],drinks:[],fruits:[],service:[],equipment:[],decoration:[]}})}),onSuccess:()=>{setName("");setPrice("");refresh()}});return <div className="space-y-4"><section className="flex flex-wrap gap-2 rounded-xl border border-border/30 bg-card p-4"><input className={input+" max-w-64"} placeholder="اسم الباقة" value={name} onChange={e=>setName(e.target.value)}/><select className={input+" max-w-40"} value={tier} onChange={e=>setTier(e.target.value)}>{["royal","vip","gold","silver","economic","custom"].map(x=><option key={x}>{x}</option>)}</select><input className={input+" max-w-40"} type="number" placeholder="السعر" value={price} onChange={e=>setPrice(e.target.value)}/><Button disabled={!name} onClick={()=>save.mutate()}>إضافة باقة</Button></section><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{rows.map(x=><div key={x.id} className="rounded-xl border border-border/30 bg-card p-4"><b>{x.name}</b><p className="mt-1 text-xs text-muted-foreground">{x.tier.toUpperCase()} · {Number(x.price).toLocaleString("ar-IQ")} د.ع</p><p className="mt-2 text-xs text-muted-foreground">أطعمة · حلويات · مشروبات · فواكه · خدمة · معدات · ديكور</p></div>)}</div></div>}
function Kitchen({rows,refresh}:{rows:Booking[];refresh:()=>void}){return <Workflow title="مركز المطبخ" rows={rows.filter(x=>["confirmed","preparing","ready"].includes(x.status))} next="ready" refresh={refresh} note="ورقة المطبخ تعرض رقم الحجز والعميل والمناسبة والضيوف والباقة وكمية مقترحة 110%."/>}
function Delivery({rows,refresh}:{rows:Booking[];refresh:()=>void}){return <Workflow title="مركز التوصيل" rows={rows.filter(x=>["ready","on_the_way"].includes(x.status))} next="on_the_way" refresh={refresh} note="عيّن السيارة والسائق من إدارة السيارات، وامسح QR عند المغادرة والوصول والتسليم."/>}
function Workflow({title,rows,next,refresh,note}:{title:string;rows:Booking[];next:string;refresh:()=>void;note:string}){const {toast}=useToast();const m=useMutation({mutationFn:(id:number)=>adminFetch(`/admin/catering/bookings/${id}`,{method:"PATCH",body:JSON.stringify({status:next})}),onSuccess:refresh,onError:(e:Error)=>toast({title:apiErrorMessage(e),variant:"destructive"})});return <div className="space-y-3"><div className="rounded-xl border border-primary/20 bg-primary/5 p-4"><h2 className="font-bold">{title}</h2><p className="mt-1 text-xs text-muted-foreground">{note}</p></div>{rows.map(x=><div key={x.id} className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border/30 bg-card p-4"><div><b>{x.code} · {x.customerName}</b><p className="mt-1 text-xs text-muted-foreground">{x.guestCount} ضيف · {x.packageName||"قائمة مخصصة"} · {x.hall||"الموقع يحدد لاحقاً"}</p></div><Button size="sm" onClick={()=>m.mutate(x.id)}>{next==="ready"?"تعليم كجاهز":"تأكيد المغادرة"}</Button></div>)}</div>}
function OperationalPage({tab,rows}:{tab:string;rows:Booking[]}){const copy:Record<string,string>={orders:"تتبع كل طلبات التجهيز وحالاتها من مركز الحجوزات.",events:"اعرض تفاصيل المناسبة، الوقت، القاعة، GPS وعدد الضيوف.",team:"اسند الشيف ومساعده والمشرف والنُدُل وفريق التنظيف والتوصيل عبر الموظفين والفرق الحالية.",assets:"اربط السيارات والمعدات والأصول الموجودة، مع QR والتتبّع من وحدة الأصول.",inventory:"احجز المكونات من المخزن الحالي، راجع النواقص، وأنشئ طلبات الشراء ضمن وحدة المشتريات.",accounting:"الفاتورة والذمم والحركات النقدية والربحية تستخدم وحدات المبيعات والحسابات الحالية.",customers:"سجل العميل يعرض تاريخ الحجوزات وتفضيلات الطعام والحساسية والقائمة المفضلة والرصيد المستحق من خلال العميل المرتبط بالحجز.",reports:"تقارير يومية وأسبوعية وشهرية للإيراد والكلفة والربح والأصناف والشيف والتوصيل والاستهلاك.",settings:"إعداد فئات الطعام، الباقات، سياسة الحصص، أوقات التحضير والتنبيهات."};return <div className="rounded-xl border border-border/30 bg-card p-6"><h2 className="font-bold text-foreground">{TABS.find(x=>x.key===tab)?.label}</h2><p className="mt-2 text-sm text-muted-foreground">{copy[tab]}</p><p className="mt-5 text-xs text-muted-foreground">الحجوزات النشطة: {rows.filter(x=>x.status!=="completed"&&x.status!=="cancelled").length}</p></div>}
