import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, ClipboardList, Download, PackageCheck, Plus, Printer, Search, ShieldCheck, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Skeleton } from "@/components/ui/skeleton";
import { useToast } from "@/hooks/use-toast";
import { adminFetch, formatCurrency } from "./_lib";
import { custodyStatementCss, printWhenImagesReadyScript } from "./print-helpers";
import { logoSrc, usePublicSettings } from "@/lib/public-settings";

type Staff = { id: number; fullName?: string; username?: string; department?: string | null };
type Group = { id: number; groupId: string; name: string; staff_id: number; employeeName: string; department?: string | null; group_type: string; status: string; asset_count: number; next_inspection_date?: string | null };
type Asset = { product_id: number; name: string; barcode?: string | null; serial_number?: string | null; asset_status?: string | null; current_value?: string | null; is_active: boolean };
type AssetCatalog = { productId: number; productName: string; assetCode: string; assetStatus: string; serialNumber?: string | null; currentValue: number; custody?: unknown[] };
type Detail = { group: Group; assets: Asset[]; reservations: any[]; history: any[] };

const TYPES = ["Photography Equipment", "Sound Equipment", "Kosha Equipment", "Lighting Equipment", "Vehicle Equipment", "General Equipment", "Custom"];
const typeLabel: Record<string, string> = { "Photography Equipment": "معدات تصوير", "Sound Equipment": "معدات صوت", "Kosha Equipment": "معدات كوشة", "Lighting Equipment": "معدات إضاءة", "Vehicle Equipment": "معدات مركبة", "General Equipment": "معدات عامة", Custom: "مخصص", general: "معدات عامة" };

export default function CustodyGroupsPage() {
  const qc = useQueryClient(); const { toast } = useToast();
  const settingsQuery = usePublicSettings();
  const [selected, setSelected] = useState<number | null>(null); const [search, setSearch] = useState("");
  const [form, setForm] = useState({ name: "", staffId: "", groupType: "Photography Equipment", description: "", nextInspectionDate: "", notes: "" });
  const groups = useQuery<{ data: Group[] }>({ queryKey: ["custody-groups"], queryFn: () => adminFetch("/admin/custody-groups") });
  const staff = useQuery<Staff[]>({ queryKey: ["admin", "staff"], queryFn: () => adminFetch("/admin/staff") });
  const detail = useQuery<Detail>({ queryKey: ["custody-group", selected], queryFn: () => adminFetch(`/admin/custody-groups/${selected}`), enabled: !!selected });
  const catalog = useQuery<{ data: AssetCatalog[] }>({ queryKey: ["admin", "assets", "custody"], queryFn: () => adminFetch("/admin/enterprise/assets") });
  const refresh = () => { qc.invalidateQueries({ queryKey: ["custody-groups"] }); qc.invalidateQueries({ queryKey: ["custody-group", selected] }); };
  const create = useMutation({ mutationFn: () => adminFetch("/admin/custody-groups", { method: "POST", body: JSON.stringify({ ...form, staffId: Number(form.staffId) }) }), onSuccess: (row: Group) => { setSelected(row.id); setForm({ name: "", staffId: "", groupType: "Photography Equipment", description: "", nextInspectionDate: "", notes: "" }); refresh(); toast({ title: "تم إنشاء مجموعة عهدة الموظف" }); }, onError: (e: any) => toast({ title: "تعذر إنشاء المجموعة", description: e?.message, variant: "destructive" }) });
  const update = useMutation({ mutationFn: (body: any) => adminFetch(`/admin/custody-groups/${selected}`, { method: "PATCH", body: JSON.stringify(body) }), onSuccess: () => { refresh(); toast({ title: "تم تحديث مجموعة العهدة" }); }, onError: (e: any) => toast({ title: "تعذر التحديث", description: e?.message, variant: "destructive" }) });
  const addAsset = useMutation({ mutationFn: (productId: number) => adminFetch(`/admin/custody-groups/${selected}/assets`, { method: "POST", body: JSON.stringify({ productId }) }), onSuccess: () => { refresh(); toast({ title: "تمت إضافة الأصل إلى العهدة" }); }, onError: (e: any) => toast({ title: "لا يمكن إضافة الأصل", description: e?.message, variant: "destructive" }) });
  const removeAsset = useMutation({ mutationFn: (productId: number) => adminFetch(`/admin/custody-groups/${selected}/assets?productId=${productId}`, { method: "DELETE" }), onSuccess: () => { refresh(); toast({ title: "تمت إزالة الأصل من العهدة" }); }, onError: (e: any) => toast({ title: "لا يمكن إزالة الأصل", description: e?.message, variant: "destructive" }) });
  const filtered = useMemo(() => (groups.data?.data ?? []).filter((g) => `${g.name} ${g.employeeName} ${g.groupId}`.toLowerCase().includes(search.toLowerCase())), [groups.data, search]);
  const candidates = useMemo(() => (catalog.data?.data ?? []).filter((a) => a.assetStatus === "active" && !(a.custody ?? []).length && !detail.data?.assets.some((x) => Number(x.product_id) === a.productId)).slice(0, 20), [catalog.data, detail.data]);
  const esc = (value: unknown) => String(value ?? "").replace(/[&<>\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[char] ?? char));
  const printStatement = () => { if (!detail.data) return; const g = detail.data.group; const rows = detail.data.assets.filter((a) => a.is_active).map((a) => `<tr><td>${esc(a.name)}</td><td dir="ltr">AJN-A${String(a.product_id).padStart(6, "0")}</td><td>${esc(a.serial_number || "—")}</td><td>${esc(a.asset_status || "active")}</td></tr>`).join(""); const win = window.open("", "_blank", "width=960,height=760"); if (!win) return; win.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>كشف عهدة موظف</title><style>${custodyStatementCss()}</style></head><body><main class="report-sheet custody-statement"><header class="report-head"><img class="report-logo" src="${esc(logoSrc(settingsQuery.data))}" alt="AJN"/><div><div class="report-company">مجموعة علي جان نهاد</div><div class="report-title">كشف عهدة موظف</div></div><div class="report-meta">رقم المجموعة: ${esc(g.groupId)}<br/>تاريخ الطباعة: ${new Date().toLocaleDateString("ar-IQ")}</div></header><section class="report-summary"><div class="report-stat">الموظف<strong>${esc(g.employeeName)}</strong></div><div class="report-stat">القسم<strong>${esc(g.department || "—")}</strong></div><div class="report-stat">نوع العهدة<strong>${esc(typeLabel[g.group_type] || g.group_type)}</strong></div><div class="report-stat">عدد الأصول<strong>${detail.data.assets.filter((a) => a.is_active).length}</strong></div></section><table class="report-table"><thead><tr><th>الأصل</th><th>رمز الأصل</th><th>الرقم التسلسلي</th><th>الحالة</th></tr></thead><tbody>${rows}</tbody></table><section class="signatures"><div>توقيع الموظف المسؤول</div><div>توقيع أمين المستودع</div></section><footer class="report-footer">كشف مسؤولية المعدات · يحتفظ الأصل بسجل الإهلاك والصيانة والـ QR الأصلي.</footer></main>${printWhenImagesReadyScript()}</body></html>`); win.document.close(); };
  const exportExcel = () => { if (!detail.data) return; const out = [["الأصل", "رمز الأصل", "الرقم التسلسلي", "الحالة"], ...detail.data.assets.filter((a) => a.is_active).map((a) => [a.name, `AJN-A${String(a.product_id).padStart(6, "0")}`, a.serial_number || "", a.asset_status || "active"])]; const csv = out.map((r) => r.map((v) => `"${String(v).replace(/"/g, '""')}"`).join(",")).join("\r\n"); const link = document.createElement("a"); link.href = URL.createObjectURL(new Blob(["\ufeff" + csv], { type: "text/csv;charset=utf-8" })); link.download = `${detail.data.group.groupId}-custody.csv`; link.click(); URL.revokeObjectURL(link.href); };

  return <div dir="rtl" className="space-y-5">
    <header className="flex flex-wrap items-start justify-between gap-3 border-b border-border/40 pb-4">
      <div><div className="mb-1 flex items-center gap-2 text-primary"><ShieldCheck className="h-5 w-5" /><span className="text-xs font-bold tracking-wide">إدارة الأصول الثابتة</span></div><h1 className="text-2xl font-bold">مجموعات عهدة الموظفين</h1><p className="mt-1 text-sm text-muted-foreground">اربط الأصول الحالية بعهدة ثابتة للموظف؛ لا تُنشأ منتجات أو أصول جديدة.</p></div>
      <div className="flex gap-2"><Button variant="outline" disabled={!detail.data} onClick={exportExcel}><Download className="h-4 w-4" /> Excel</Button><Button variant="outline" disabled={!detail.data} onClick={printStatement}><Printer className="h-4 w-4" /> A4 / PDF / طباعة</Button></div>
    </header>

    <div className="grid gap-5 xl:grid-cols-[minmax(300px,0.85fr)_minmax(0,1.45fr)]">
      <aside className="space-y-4">
        <section className="rounded-xl border border-border/40 bg-card p-4"><h2 className="mb-3 flex items-center gap-2 font-bold"><Plus className="h-4 w-4 text-primary" /> إنشاء مجموعة معدات الموظف</h2><div className="space-y-3"><div><Label>اسم المجموعة</Label><Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="حقيبة تصوير حسن علي" /></div><div><Label>الموظف</Label><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={form.staffId} onChange={(e) => setForm({ ...form, staffId: e.target.value })}><option value="">اختر الموظف</option>{staff.data?.map((s) => <option key={s.id} value={s.id}>{s.fullName || s.username}</option>)}</select></div><div><Label>نوع المجموعة</Label><select className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm" value={form.groupType} onChange={(e) => setForm({ ...form, groupType: e.target.value })}>{TYPES.map((t) => <option key={t} value={t}>{typeLabel[t]}</option>)}</select></div><div><Label>الفحص القادم</Label><Input type="date" value={form.nextInspectionDate} onChange={(e) => setForm({ ...form, nextInspectionDate: e.target.value })} /></div><Textarea value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} placeholder="ملاحظات العهدة" /><Button className="w-full" disabled={!form.name.trim() || !form.staffId || create.isPending} onClick={() => create.mutate()}>{create.isPending ? "جاري الحفظ…" : "إنشاء مجموعة العهدة"}</Button></div></section>
        <section className="rounded-xl border border-border/40 bg-card p-3"><div className="relative mb-3"><Search className="absolute right-3 top-2.5 h-4 w-4 text-muted-foreground" /><Input className="pr-9" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="بحث باسم الموظف أو المجموعة" /></div>{groups.isLoading ? <Skeleton className="h-40" /> : <div className="max-h-[480px] space-y-2 overflow-auto">{filtered.map((g) => <button key={g.id} type="button" onClick={() => setSelected(g.id)} className={`w-full rounded-lg border p-3 text-right transition-colors ${selected === g.id ? "border-primary bg-primary/5" : "border-border/40 hover:border-primary/40"}`}><div className="flex justify-between gap-2"><b>{g.name}</b><span className={`rounded-full px-2 py-0.5 text-[11px] ${g.status === "active" ? "bg-emerald-500/10 text-emerald-600" : "bg-muted text-muted-foreground"}`}>{g.status === "active" ? "نشطة" : "مؤرشفة"}</span></div><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><UserRound className="h-3 w-3" /> {g.employeeName} · {g.asset_count} أصل</p></button>)}</div>}</section>
      </aside>

      <main className="min-w-0 rounded-xl border border-border/40 bg-card p-4">
        {!selected ? <div className="grid min-h-80 place-items-center text-center text-muted-foreground"><div><ClipboardList className="mx-auto mb-3 h-10 w-10 opacity-50" /><p className="font-medium">اختر مجموعة لعرض تفاصيل العهدة</p><p className="mt-1 text-sm">ستظهر الأصول والحجز الحالي وسجل العهدة هنا.</p></div></div> : detail.isLoading ? <Skeleton className="h-96" /> : detail.data && <>
          <div className="flex flex-wrap items-start justify-between gap-3 border-b border-border/40 pb-4"><div><p className="text-xs font-mono text-muted-foreground">{detail.data.group.groupId}</p><h2 className="text-xl font-bold">{detail.data.group.name}</h2><p className="mt-1 text-sm text-muted-foreground">{detail.data.group.employeeName} · {detail.data.group.department || "بدون قسم"} · {typeLabel[detail.data.group.group_type] || detail.data.group.group_type}</p></div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => update.mutate({ status: detail.data!.group.status === "active" ? "archived" : "active" })}><Archive className="h-4 w-4" /> {detail.data.group.status === "active" ? "أرشفة" : "تفعيل"}</Button></div></div>
          <section className="mt-5"><div className="mb-3 flex items-center justify-between"><h3 className="flex items-center gap-2 font-bold"><PackageCheck className="h-4 w-4 text-primary" /> أصول العهدة الثابتة</h3><span className="text-xs text-muted-foreground">لا تُزال بعد انتهاء الحجز</span></div><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="border-b text-right text-xs text-muted-foreground"><tr><th className="pb-2">الأصل</th><th className="pb-2">الرمز / QR</th><th className="pb-2">التسلسلي</th><th className="pb-2">الحالة</th><th className="pb-2">القيمة</th><th className="pb-2" /></tr></thead><tbody>{detail.data.assets.filter((a) => a.is_active).map((a) => <tr key={a.product_id} className="border-b border-border/30"><td className="py-3 font-medium">{a.name}</td><td className="py-3 font-mono text-xs">AJN-A{String(a.product_id).padStart(6, "0")}</td><td className="py-3">{a.serial_number || "—"}</td><td className="py-3">{a.asset_status || "active"}</td><td className="py-3">{formatCurrency(Number(a.current_value || 0))}</td><td className="py-3"><Button variant="ghost" size="sm" disabled={removeAsset.isPending} onClick={() => removeAsset.mutate(Number(a.product_id))}>إزالة</Button></td></tr>)}</tbody></table></div></section>
          <section className="mt-5 rounded-lg border border-dashed border-border p-3"><h3 className="mb-2 text-sm font-bold">إضافة أصل قائم من إدارة الأصول</h3><div className="flex flex-wrap gap-2">{candidates.length ? candidates.map((a) => <Button key={a.productId} variant="outline" size="sm" disabled={addAsset.isPending} onClick={() => addAsset.mutate(a.productId)}><Plus className="h-3.5 w-3.5" /> {a.productName} <span className="font-mono text-[10px]">{a.assetCode}</span></Button>) : <span className="text-sm text-muted-foreground">لا توجد أصول نشطة متاحة للإضافة.</span>}</div></section>
          <section className="mt-5 grid gap-4 lg:grid-cols-2"><div className="rounded-lg bg-muted/40 p-3"><h3 className="mb-2 font-bold">حجز حالي</h3>{detail.data.reservations.length ? detail.data.reservations.map((r) => <p key={r.id} className="border-b border-border/30 py-2 text-sm">{r.status === "checked_out" ? "خرجت للحجز" : "محجوز للحجز"} · حجز #{r.booking_id}</p>) : <p className="text-sm text-muted-foreground">لا توجد حجوزات نشطة.</p>}</div><div className="rounded-lg bg-muted/40 p-3"><h3 className="mb-2 font-bold">سجل العهدة</h3>{detail.data.history.slice(0, 4).map((h) => <p key={h.id} className="border-b border-border/30 py-2 text-sm">{h.action} <span className="text-xs text-muted-foreground">· {new Date(h.created_at).toLocaleString("ar-IQ")}</span></p>)}{!detail.data.history.length && <p className="text-sm text-muted-foreground">لا يوجد سجل بعد.</p>}</div></section>
        </>}
      </main>
    </div>
  </div>;
}
