import { useMemo, useRef, useState } from "react";
import type { ReactNode } from "react";
import { useQuery } from "@tanstack/react-query";
import { ChevronDown, FileDown, Printer, SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { downloadElementPdf } from "@/lib/pdf";
import { logoSrc, usePublicSettings } from "@/lib/public-settings";
import { adminFetch, formatCurrency } from "./_lib";
import { depreciationReportCss, printWhenImagesReadyScript } from "./print-helpers";

type Asset = { productId:number; assetCode:string; name:string; category:string|null; categoryId:number|null; assetType:string|null; warehouse:string|null; warehouseId:number|null; purchaseDate:string|null; purchasePrice:number; currentValue:number; depreciationAmount:number; depreciationMethod:string; annualRate:number; usageCount:number; status:string };
type Choice = { id:number; name:string };
type Payload = { data:Asset[]; categories:Choice[]; warehouses:Choice[]; filters:Record<string,string> };
const methods:Record<string,string>={straight_line:"القسط الثابت",declining_balance:"الرصيد المتناقص",usage:"حسب الاستخدام",manual:"يدوي"};
const statuses:Record<string,string>={active:"نشط",reserved:"محجوز",maintenance:"صيانة",transferred:"منقول",lost:"مفقود",retired:"مستبعد",locked:"مقفل",sold:"تم البيع",disposed:"تم الاستبعاد"};
const esc=(v:unknown)=>String(v??"—").replace(/[&<>\"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]||c));
const date=(v:string|null)=>v?new Date(v).toLocaleDateString("ar-IQ"):"—";
const money=(v:number)=>formatCurrency(v);

function selectedFilters(filters:Record<string,string>, categories:Choice[], warehouses:Choice[]) {
  const pick=(list:Choice[], id:string)=>list.find(x=>String(x.id)===id)?.name;
  return [
    filters.categoryId&&`فئة الإهلاك: ${pick(categories,filters.categoryId)||filters.categoryId}`,
    filters.assetType&&`نوع الأصل: ${filters.assetType}`,
    filters.method&&`الطريقة: ${methods[filters.method]||filters.method}`,
    filters.status&&`الحالة: ${statuses[filters.status]||filters.status}`,
    filters.warehouseId&&`المستودع: ${pick(warehouses,filters.warehouseId)||filters.warehouseId}`,
    filters.from&&`من: ${filters.from}`,
    filters.to&&`إلى: ${filters.to}`,
    filters.assetId&&`أصل محدد: ${filters.assetId}`,
  ].filter(Boolean).join(" · ") || "جميع الأصول";
}

function reportMarkup(rows:Asset[], filters:Record<string,string>, categories:Choice[], warehouses:Choice[], logo:string, thermal:boolean, printedBy="المستخدم الحالي") {
  const total=rows.reduce((s,x)=>s+x.purchasePrice,0), depreciation=rows.reduce((s,x)=>s+x.depreciationAmount,0), current=rows.reduce((s,x)=>s+x.currentValue,0);
  const filterText=selectedFilters(filters,categories,warehouses), issued=new Date().toLocaleString("ar-IQ");
  if(thermal) return `<div class="receipt depreciation-thermal"><div class="r-head">${logo?`<img class="r-logo" src="${esc(logo)}" alt="AJN">`:""}<div class="r-company">AJN</div><div class="r-sub">تقرير إهلاك الأصول</div><div class="r-sub">${esc(issued)}</div></div><hr class="rule"><div class="kv"><span>الفئة / الفلاتر</span><span class="v">${esc(filterText)}</span></div><div class="kv"><span>عدد الأصول</span><span class="v num">${rows.length}</span></div><div class="kv"><span>القيمة الأصلية</span><span class="v num">${esc(money(total))}</span></div><div class="kv"><span>الإهلاك المتراكم</span><span class="v num">${esc(money(depreciation))}</span></div><div class="grand"><span>القيمة الحالية</span><span class="num">${esc(money(current))}</span></div><hr class="rule dashed">${rows.map(a=>`<div class="asset"><b>${esc(a.name)}</b><div class="line"><span>${esc(a.assetCode)}</span><span>${esc(statuses[a.status]||a.status)}</span></div><div class="line"><span>الأصلية: ${esc(money(a.purchasePrice))}</span><span>الإهلاك: ${esc(money(a.depreciationAmount))}</span></div><div class="line"><span>الحالية: ${esc(money(a.currentValue))}</span><span>الاستخدام: ${esc(a.usageCount)}</span></div></div>`).join("")}<div class="thanks">طُبع بواسطة ${esc(printedBy)}</div></div>`;
  return `<div class="report-sheet depreciation-sheet"><header class="report-head"><div><img class="report-logo" src="${esc(logo)}" alt="AJN"></div><div><div class="report-company">مجموعة علي جان نهاد · AJN</div><div class="report-title">تقرير إهلاك الأصول</div></div><div class="report-meta">تاريخ الإصدار: ${esc(issued)}<br>طُبع بواسطة: ${esc(printedBy)}</div></header><div class="filter-note"><b>الفلاتر المحددة:</b> ${esc(filterText)}</div><section class="report-summary"><div class="report-stat">عدد الأصول<strong>${rows.length}</strong></div><div class="report-stat">القيمة الأصلية<strong>${esc(money(total))}</strong></div><div class="report-stat">الإهلاك المتراكم<strong>${esc(money(depreciation))}</strong></div><div class="report-stat">القيمة الحالية<strong>${esc(money(current))}</strong></div><div class="report-stat">القيمة المتبقية<strong>${esc(money(current))}</strong></div></section><table class="report-table"><thead><tr><th>رقم الأصل</th><th>اسم الأصل</th><th>الفئة</th><th>تاريخ الشراء</th><th>القيمة الأصلية</th><th>طريقة الإهلاك</th><th>النسبة</th><th>الإهلاك المتراكم</th><th>القيمة الحالية</th><th>الاستخدامات</th><th>الحالة</th></tr></thead><tbody>${rows.map(a=>`<tr><td class="num">${esc(a.assetCode)}</td><td>${esc(a.name)}</td><td>${esc(a.category)}</td><td class="num">${esc(date(a.purchaseDate))}</td><td class="num">${esc(money(a.purchasePrice))}</td><td>${esc(methods[a.depreciationMethod]||a.depreciationMethod)}</td><td class="num">${esc(a.annualRate)}%</td><td class="num">${esc(money(a.depreciationAmount))}</td><td class="num">${esc(money(a.currentValue))}</td><td class="num">${esc(a.usageCount)}</td><td>${esc(statuses[a.status]||a.status)}</td></tr>`).join("")||"<tr><td colspan=\"11\">لا توجد أصول مطابقة للفلاتر المحددة.</td></tr>"}</tbody></table><footer class="report-footer">تاريخ الطباعة: ${esc(issued)} · تقرير داخلي للأصول</footer><div class="print-page"><span>AJN · تقرير إهلاك الأصول</span><span class="page-counter"></span></div></div>`;
}

export default function DepreciationPage(){
  const {data:settings}=usePublicSettings(); const reportRef=useRef<HTMLDivElement|null>(null); const [preview,setPreview]=useState<"a4"|"80mm"|null>(null);
  const [filters,setFilters]=useState({categoryId:"",assetType:"",method:"",status:"",warehouseId:"",from:"",to:"",assetId:""});
  const search=useMemo(()=>new URLSearchParams(Object.entries(filters).filter(([,v])=>v)),[filters]);
  const query=useQuery<Payload>({queryKey:["asset-depreciation-report",search.toString()],queryFn:()=>adminFetch(`/admin/assets/depreciation/report?${search}`)});
  const rows=query.data?.data??[], categories=query.data?.categories??[], warehouses=query.data?.warehouses??[];
  const logo=logoSrc(settings); const set=(key:keyof typeof filters,value:string)=>setFilters(p=>({...p,[key]:value}));
  const audit=async(kind:"print_a4"|"print_80mm"|"export_a4"|"export_80mm")=>adminFetch("/admin/assets/depreciation/report-audit",{method:"POST",body:JSON.stringify({reportType:"assets",action:kind,paperSize:kind.endsWith("80mm")?"80mm":"A4",filters,assetCount:rows.length})});
  const runPrint=async(kind:"a4"|"80mm")=>{await audit(kind==="a4"?"print_a4":"print_80mm"); const win=window.open("","_blank","width=960,height=760"); if(!win) return; win.document.write(`<!doctype html><html dir="rtl"><head><meta charset="utf-8"><title>تقرير إهلاك الأصول</title><style>${depreciationReportCss(kind)}</style></head><body>${reportMarkup(rows,filters,categories,warehouses,logo,kind==="80mm")}${printWhenImagesReadyScript()}</body></html>`);win.document.close();};
  const exportPdf=async(kind:"a4"|"80mm")=>{await audit(kind==="a4"?"export_a4":"export_80mm"); if(!reportRef.current)return; const height=Math.max(100,Math.ceil(reportRef.current.scrollHeight*25.4/96)); await downloadElementPdf(reportRef.current,`ajn-depreciation-${new Date().toISOString().slice(0,10)}-${kind}.pdf`,{format:kind==="a4"?"a4":[80,height],margin:kind==="a4"?10:0,pagebreakMode:["css","legacy"],scale:2});};
  const markup=preview?reportMarkup(rows,filters,categories,warehouses,logo,preview==="80mm"):"";
  return <div className="space-y-5" dir="rtl"><header className="flex flex-wrap items-end justify-between gap-3"><div><h1 className="text-2xl font-bold">إهلاك الأصول</h1><p className="mt-1 text-sm text-muted-foreground">تقرير تشغيلي للقيمة والإهلاك حسب الفلاتر الحالية.</p></div><DropdownMenu dir="rtl"><DropdownMenuTrigger asChild><Button className="gap-2"><Printer className="h-4 w-4"/> طباعة تقرير الإهلاك <ChevronDown className="h-4 w-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem onSelect={()=>runPrint("a4")}><Printer/> طباعة A4</DropdownMenuItem><DropdownMenuItem onSelect={()=>runPrint("80mm")}><Printer/> طباعة حرارية 80mm</DropdownMenuItem><DropdownMenuItem onSelect={()=>exportPdf("a4")}><FileDown/> تحميل PDF A4</DropdownMenuItem><DropdownMenuItem onSelect={()=>exportPdf("80mm")}><FileDown/> تحميل PDF 80mm</DropdownMenuItem></DropdownMenuContent></DropdownMenu></header>
    <section className="grid gap-3 rounded-xl border border-border bg-card p-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="فئة الإهلاك"><select value={filters.categoryId} onChange={e=>set("categoryId",e.target.value)}><option value="">كل الفئات</option>{categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="نوع الأصل"><input value={filters.assetType} onChange={e=>set("assetType",e.target.value)} placeholder="مثال: صوتيات"/></Field><Field label="طريقة الإهلاك"><select value={filters.method} onChange={e=>set("method",e.target.value)}><option value="">كل الطرق</option>{Object.entries(methods).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="الحالة"><select value={filters.status} onChange={e=>set("status",e.target.value)}><option value="">كل الحالات</option>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="المستودع"><select value={filters.warehouseId} onChange={e=>set("warehouseId",e.target.value)}><option value="">كل المستودعات</option>{warehouses.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></Field><Field label="من تاريخ الشراء"><input type="date" value={filters.from} onChange={e=>set("from",e.target.value)}/></Field><Field label="إلى تاريخ الشراء"><input type="date" value={filters.to} onChange={e=>set("to",e.target.value)}/></Field><Field label="أصل محدد"><input inputMode="numeric" value={filters.assetId} onChange={e=>set("assetId",e.target.value)} placeholder="رقم الأصل"/></Field></section>
    <section className="overflow-hidden rounded-xl border border-border bg-card"><div className="flex items-center justify-between border-b border-border px-4 py-3"><span className="font-semibold">الأصول المطابقة</span><span className="text-sm text-muted-foreground">{rows.length} أصل</span></div><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-sm"><thead className="bg-muted/50 text-right text-xs text-muted-foreground"><tr>{["الأصل","الفئة","المستودع","الأصلية","الإهلاك","الحالية","الطريقة","الاستخدام","الحالة"].map(x=><th className="px-4 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{query.isLoading?<tr><td colSpan={9} className="p-8 text-center text-muted-foreground">جارٍ تحميل التقرير…</td></tr>:rows.map(a=><tr className="border-t border-border" key={a.productId}><td className="px-4 py-3"><b>{a.name}</b><small className="block text-muted-foreground">{a.assetCode}</small></td><td className="px-4 py-3">{a.category||"—"}</td><td className="px-4 py-3">{a.warehouse||"—"}</td><td className="px-4 py-3">{money(a.purchasePrice)}</td><td className="px-4 py-3">{money(a.depreciationAmount)}</td><td className="px-4 py-3 font-medium">{money(a.currentValue)}</td><td className="px-4 py-3">{methods[a.depreciationMethod]||a.depreciationMethod}</td><td className="px-4 py-3">{a.usageCount}</td><td className="px-4 py-3">{statuses[a.status]||a.status}</td></tr>)}{!rows.length&&!query.isLoading&&<tr><td colSpan={9} className="p-8 text-center text-muted-foreground">لا توجد أصول مطابقة للفلاتر.</td></tr>}</tbody></table></div></section>
    <div ref={reportRef} className="fixed -left-[100000px] top-0 bg-white" style={{width:preview==="80mm"?"80mm":"210mm"}}><style>{depreciationReportCss(preview??"a4")}</style><div dangerouslySetInnerHTML={{__html:markup||reportMarkup(rows,filters,categories,warehouses,logo,false)}}/></div>
    {preview&&<div className="fixed inset-0 z-50 overflow-auto bg-black/60 p-4"><div className="mx-auto max-w-5xl rounded-xl bg-white p-4 text-black"><div className="mb-3 flex items-center justify-between"><b>معاينة قبل الطباعة</b><div className="flex gap-2"><Button size="sm" onClick={()=>runPrint(preview)}>طباعة</Button><Button size="sm" variant="outline" onClick={()=>setPreview(null)}>إغلاق</Button></div></div><div className="overflow-auto" dangerouslySetInnerHTML={{__html:`<style>${depreciationReportCss(preview)}</style>${markup}`}}/></div></div>}
    <Button variant="outline" className="gap-2" onClick={()=>setPreview("a4")}><SlidersHorizontal className="h-4 w-4"/> معاينة التقرير</Button></div>;
}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="grid gap-1 text-sm"><span className="text-muted-foreground">{label}</span><span className="[&_input]:h-10 [&_input]:w-full [&_input]:rounded-md [&_input]:border [&_input]:border-input [&_input]:bg-background [&_input]:px-3 [&_select]:h-10 [&_select]:w-full [&_select]:rounded-md [&_select]:border [&_select]:border-input [&_select]:bg-background [&_select]:px-3">{children}</span></label>}
