import { useMemo, useState, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BarChart3, Check, Download, FileSpreadsheet, Plus, Printer, Search, Settings2, Wallet, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { useToast } from "@/hooks/use-toast";
import { adminFetch, apiErrorMessage } from "./_lib";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Textarea } from "@/components/ui/textarea";

type Staff = { id: number; fullName: string; username: string; department?: string };
type Advance = {
  id: number; advanceNo: string; employeeId: number; employeeName: string; department: string;
  requestDate: string; advanceType: string; amount: number; repaidAmount: number; remainingAmount: number;
  monthlyDeduction: number; reason: string; notes?: string | null; status: string; dueDate?: string | null;
  approvedByName?: string; approvedAt?: string | null; financialTransactionId?: number | null;
};
type Dashboard = { cards: Record<string, number>; monthly: { month: string; advances: number; repayments: number }[]; departments: { department: string; count: number; outstanding: number }[] };

const IQD = new Intl.NumberFormat("ar-IQ", { style: "currency", currency: "IQD", maximumFractionDigits: 0 });
const today = () => new Date().toISOString().slice(0, 10);
const labels: Record<string, string> = { salary_advance: "سلفة راتب", cash_withdrawal: "سحب نقدي", emergency_loan: "قرض طارئ", pending: "معلّق", approved: "معتمد", rejected: "مرفوض", cancelled: "ملغي", paid: "مصروف", completed: "مكتمل" };
const statusClass: Record<string, string> = { pending: "bg-amber-500/15 text-amber-700 dark:text-amber-300", paid: "bg-blue-500/15 text-blue-700 dark:text-blue-300", completed: "bg-emerald-500/15 text-emerald-700 dark:text-emerald-300", rejected: "bg-red-500/15 text-red-700 dark:text-red-300", cancelled: "bg-zinc-500/15 text-zinc-600 dark:text-zinc-300" };

function downloadReport(format: "csv" | "excel") {
  fetch(`/api/admin/employee-advances/report?format=${format}`, { credentials: "include" })
    .then((r) => { if (!r.ok) throw new Error("تعذر تصدير التقرير"); return r.blob(); })
    .then((blob) => { const url = URL.createObjectURL(blob); const a = document.createElement("a"); a.href = url; a.download = `employee-advances.${format === "excel" ? "xls" : "csv"}`; a.click(); URL.revokeObjectURL(url); })
    .catch(() => undefined);
}

export default function EmployeeAdvancesPage() {
  const qc = useQueryClient();
  const { toast } = useToast();
  const [query, setQuery] = useState("");
  const [status, setStatus] = useState("");
  const [employeeId, setEmployeeId] = useState(() => new URLSearchParams(window.location.search).get("employeeId") ?? "");
  const [requestOpen, setRequestOpen] = useState(false);
  const [repayment, setRepayment] = useState<Advance | null>(null);
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [pendingAction, setPendingAction] = useState<{ row: Advance; action: "approve" | "reject" | "cancel" } | null>(null);
  const [actionReason, setActionReason] = useState("");
  const [form, setForm] = useState({ employeeId: "", requestDate: today(), advanceType: "salary_advance", amount: "", monthlyDeduction: "", reason: "", notes: "", attachmentUrl: "", dueDate: "" });
  const [payment, setPayment] = useState({ amount: "", paymentDate: today(), method: "cash", notes: "" });

  const params = useMemo(() => new URLSearchParams(Object.entries({ q: query, status, employeeId }).filter(([, value]) => value !== "") as [string, string][]).toString(), [query, status, employeeId]);
  const advances = useQuery({ queryKey: ["employee-advances", params], queryFn: () => adminFetch<Advance[]>(`/admin/employee-advances${params ? `?${params}` : ""}`) });
  const dashboard = useQuery({ queryKey: ["employee-advances", "dashboard"], queryFn: () => adminFetch<Dashboard>("/admin/employee-advances/dashboard") });
  const staff = useQuery({ queryKey: ["admin", "staff"], queryFn: () => adminFetch<Staff[]>("/admin/staff") });
  const settings = useQuery({ queryKey: ["employee-advances", "settings"], queryFn: () => adminFetch<any>("/admin/employee-advances/settings") });
  const refresh = () => { qc.invalidateQueries({ queryKey: ["employee-advances"] }); qc.invalidateQueries({ queryKey: ["admin", "staff"] }); };
  const create = useMutation({ mutationFn: () => adminFetch("/admin/employee-advances", { method: "POST", body: JSON.stringify({ ...form, employeeId: Number(form.employeeId), amount: Number(form.amount), monthlyDeduction: Number(form.monthlyDeduction || 0), attachmentUrl: form.attachmentUrl || null, dueDate: form.dueDate || null }) }), onSuccess: () => { refresh(); setRequestOpen(false); setForm({ employeeId: "", requestDate: today(), advanceType: "salary_advance", amount: "", monthlyDeduction: "", reason: "", notes: "", attachmentUrl: "", dueDate: "" }); toast({ title: "تم إرسال طلب السلفة" }); }, onError: (e) => toast({ title: apiErrorMessage(e), variant: "destructive" }) });
  const action = useMutation({ mutationFn: ({ id, action, body }: { id: number; action: string; body?: unknown }) => adminFetch(`/admin/employee-advances/${id}/${action}`, { method: "POST", body: JSON.stringify(body ?? {}) }), onSuccess: (data: any, vars) => { refresh(); if (vars.action === "approve") toast({ title: "تم اعتماد وصرف السلفة", description: data?.transaction ? `رقم الحركة: ${data.transaction.transactionNo} | الرصيد: ${IQD.format(Number(data.transaction.balanceAfter ?? 0))}` : undefined }); else toast({ title: "تم تحديث السلفة" }); }, onError: (e) => toast({ title: apiErrorMessage(e), variant: "destructive" }) });
  const repay = useMutation({ mutationFn: () => adminFetch(`/admin/employee-advances/${repayment!.id}/repay`, { method: "POST", body: JSON.stringify({ ...payment, amount: Number(payment.amount) }) }), onSuccess: () => { refresh(); setRepayment(null); toast({ title: "تم تسجيل التسديد" }); }, onError: (e) => toast({ title: apiErrorMessage(e), variant: "destructive" }) });
  const saveSettings = useMutation({ mutationFn: (data: FormData) => adminFetch("/admin/employee-advances/settings", { method: "PUT", body: JSON.stringify(Object.fromEntries(data.entries())) }), onSuccess: () => { refresh(); setSettingsOpen(false); toast({ title: "تم حفظ حدود السلف" }); }, onError: (e) => toast({ title: apiErrorMessage(e), variant: "destructive" }) });

  const cards = dashboard.data?.cards ?? {};
  const chartMax = Math.max(1, ...(dashboard.data?.monthly ?? []).flatMap((m) => [m.advances, m.repayments]));
  return <div className="space-y-5" dir="rtl">
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <div><div className="flex items-center gap-2"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/15 text-primary"><Wallet className="h-5 w-5" /></span><div><h1 className="text-2xl font-bold">سلف الموظفين</h1><p className="text-sm text-muted-foreground">إدارة السلف والسحب النقدي والتسديدات وربطها بالصندوق.</p></div></div></div>
      <div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => setSettingsOpen(true)}><Settings2 className="ms-1 h-4 w-4" />الحدود</Button><Button variant="outline" size="sm" onClick={() => window.print()}><Printer className="ms-1 h-4 w-4" />طباعة / PDF</Button><Button variant="outline" size="sm" onClick={() => downloadReport("excel")}><FileSpreadsheet className="ms-1 h-4 w-4" />Excel</Button><Button size="sm" onClick={() => setRequestOpen(true)}><Plus className="ms-1 h-4 w-4" />طلب سلفة</Button></div>
    </div>

    <div className="grid grid-cols-2 gap-3 lg:grid-cols-6">
      <Metric title="السلف النشطة" value={String(cards.totalActiveAdvances ?? 0)} /><Metric title="المبالغ المستحقة" value={IQD.format(cards.totalOutstanding ?? 0)} /><Metric title="المسدّد" value={IQD.format(cards.totalRepaid ?? 0)} /><Metric title="طلبات معلّقة" value={String(cards.totalPendingRequests ?? 0)} /><Metric title="أعلى سلفة" value={IQD.format(cards.highestAdvance ?? 0)} /><Metric title="متأخرات" value={String(cards.overdueRepayments ?? 0)} danger={(cards.overdueRepayments ?? 0) > 0} />
    </div>

    <div className="grid gap-4 xl:grid-cols-3 print:hidden"><section className="rounded-xl border border-border/50 bg-card p-4 xl:col-span-2"><div className="mb-4 flex items-center gap-2 font-semibold"><BarChart3 className="h-4 w-4 text-primary" />السلف والتسديدات الشهرية</div><div className="flex h-40 items-end gap-3 overflow-x-auto pb-5">{(dashboard.data?.monthly ?? []).length ? dashboard.data!.monthly.map((m) => <div key={m.month} className="min-w-16 flex-1 text-center text-[10px] text-muted-foreground"><div className="flex h-28 items-end justify-center gap-1"><div title={`سلف ${IQD.format(m.advances)}`} className="w-4 rounded-t bg-primary" style={{ height: `${Math.max(3, (m.advances / chartMax) * 100)}%` }} /><div title={`تسديد ${IQD.format(m.repayments)}`} className="w-4 rounded-t bg-emerald-500" style={{ height: `${Math.max(3, (m.repayments / chartMax) * 100)}%` }} /></div>{m.month}</div>) : <p className="m-auto text-sm text-muted-foreground">لا توجد بيانات شهرية بعد.</p>}</div><div className="flex gap-4 text-xs text-muted-foreground"><span><i className="me-1 inline-block h-2 w-2 rounded bg-primary" />سلف</span><span><i className="me-1 inline-block h-2 w-2 rounded bg-emerald-500" />تسديدات</span></div></section><section className="rounded-xl border border-border/50 bg-card p-4"><h2 className="mb-3 font-semibold">إحصاء الأقسام</h2><div className="space-y-3">{(dashboard.data?.departments ?? []).slice(0, 5).map((d) => <div key={d.department}><div className="flex justify-between text-xs"><span>{d.department}</span><span>{IQD.format(d.outstanding)}</span></div><div className="mt-1 h-2 rounded bg-muted"><div className="h-2 rounded bg-primary" style={{ width: `${Math.min(100, (d.outstanding / Math.max(1, cards.totalOutstanding ?? 1)) * 100)}%` }} /></div></div>)}</div></section></div>

    <section className="rounded-xl border border-border/50 bg-card p-4"><div className="mb-4 grid gap-2 md:grid-cols-4"><label className="relative"><Search className="absolute right-3 top-2.5 h-4 w-4 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="بحث بالموظف أو رقم السلفة" className="w-full rounded-lg border border-border bg-background py-2 pr-9 ps-3 text-sm" /></label><select value={employeeId} onChange={(e) => setEmployeeId(e.target.value)} className="rounded-lg border border-border bg-background px-3 py-2 text-sm"><option value="">كل الموظفين</option>{staff.data?.map((s) => <option key={s.id} value={s.id}>{s.fullName || s.username}</option>)}</select><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-lg border border-border bg-background px-3 py-2 text-sm"><option value="">كل الحالات</option>{["pending", "paid", "completed", "rejected", "cancelled"].map((key) => <option key={key} value={key}>{labels[key]}</option>)}</select><Button variant="outline" onClick={() => { setQuery(""); setStatus(""); setEmployeeId(""); }}><X className="ms-1 h-4 w-4" />مسح الفلاتر</Button></div>
      {advances.isLoading ? <div className="space-y-2">{[1, 2, 3].map((x) => <Skeleton key={x} className="h-16" />)}</div> : <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-right text-sm"><thead className="border-b text-xs text-muted-foreground"><tr><th className="p-2">الرقم / الموظف</th><th className="p-2">النوع والتاريخ</th><th className="p-2">المبلغ</th><th className="p-2">المسدّد / المتبقي</th><th className="p-2">الخصم الشهري</th><th className="p-2">الحالة</th><th className="p-2">إجراء</th></tr></thead><tbody>{advances.data?.map((row) => <tr key={row.id} className="border-b border-border/50 last:border-0"><td className="p-2"><b>{row.employeeName}</b><div className="text-xs text-muted-foreground">{row.advanceNo}</div></td><td className="p-2"><div>{labels[row.advanceType] ?? row.advanceType}</div><div className="text-xs text-muted-foreground">{row.requestDate}</div></td><td className="p-2 font-medium">{IQD.format(row.amount)}<div className="max-w-40 truncate text-xs font-normal text-muted-foreground">{row.reason}</div></td><td className="p-2"><div className="text-emerald-600 dark:text-emerald-400">{IQD.format(row.repaidAmount)}</div><div className="text-xs text-muted-foreground">متبقي {IQD.format(row.remainingAmount)}</div></td><td className="p-2">{IQD.format(row.monthlyDeduction)}</td><td className="p-2"><span className={`rounded-full px-2 py-1 text-xs ${statusClass[row.status] ?? "bg-muted"}`}>{labels[row.status] ?? row.status}</span></td><td className="p-2"><div className="flex gap-1">{row.status === "pending" && <><Button size="sm" className="h-7" onClick={() => { setActionReason(""); setPendingAction({ row, action: "approve" }); }}><Check className="h-3.5 w-3.5" />اعتماد</Button><Button size="sm" variant="outline" className="h-7" onClick={() => { setActionReason(""); setPendingAction({ row, action: "reject" }); }}>رفض</Button></>}{row.remainingAmount > 0 && ["paid", "approved"].includes(row.status) && <Button size="sm" variant="outline" className="h-7" onClick={() => { setRepayment(row); setPayment({ amount: String(Math.min(row.monthlyDeduction || row.remainingAmount, row.remainingAmount)), paymentDate: today(), method: "cash", notes: "" }); }}>تسديد</Button>}{["pending", "rejected"].includes(row.status) && <Button size="sm" variant="ghost" className="h-7 text-destructive" onClick={() => { setActionReason(""); setPendingAction({ row, action: "cancel" }); }}>إلغاء</Button>}</div></td></tr>)}</tbody></table>{!advances.data?.length && <p className="py-12 text-center text-sm text-muted-foreground">لا توجد سلف تطابق البحث.</p>}</div>}</section>
    <Dialog open={!!pendingAction} onOpenChange={(open) => !open && setPendingAction(null)}><DialogContent dir="rtl"><DialogHeader><DialogTitle>{pendingAction?.action === "approve" ? "اعتماد وصرف السلفة" : pendingAction?.action === "reject" ? "رفض طلب السلفة" : "إلغاء طلب السلفة"}</DialogTitle><DialogDescription>{pendingAction && `${pendingAction.row.employeeName} · ${pendingAction.row.advanceNo} · ${IQD.format(pendingAction.row.amount)}`}</DialogDescription></DialogHeader>{pendingAction?.action !== "approve" && <label className="grid gap-1 text-sm"><span>{pendingAction?.action === "reject" ? "سبب الرفض" : "سبب الإلغاء"}</span><Textarea value={actionReason} onChange={(event) => setActionReason(event.target.value)} placeholder="اكتب السبب لحفظه في سجل النشاط" /></label>}<DialogFooter><Button variant="outline" onClick={() => setPendingAction(null)}>إلغاء</Button><Button variant={pendingAction?.action === "cancel" ? "destructive" : "default"} disabled={action.isPending || (pendingAction?.action !== "approve" && actionReason.trim().length < 3)} onClick={() => { if (!pendingAction) return; action.mutate({ id: pendingAction.row.id, action: pendingAction.action, body: pendingAction.action === "approve" ? {} : { reason: actionReason.trim() } }, { onSuccess: () => setPendingAction(null) }); }}>{pendingAction?.action === "approve" ? "تأكيد الاعتماد والصرف" : pendingAction?.action === "reject" ? "تأكيد الرفض" : "تأكيد الإلغاء"}</Button></DialogFooter></DialogContent></Dialog>
    {requestOpen && <Modal title="طلب سلفة موظف" onClose={() => setRequestOpen(false)}><form className="grid gap-3 md:grid-cols-2" onSubmit={(e) => { e.preventDefault(); create.mutate(); }}><SelectField label="الموظف" value={form.employeeId} onChange={(v) => setForm({ ...form, employeeId: v })} options={[{ value: "", label: "اختر الموظف" }, ...(staff.data ?? []).map((s) => ({ value: String(s.id), label: s.fullName || s.username }))]} required /><SelectField label="النوع" value={form.advanceType} onChange={(v) => setForm({ ...form, advanceType: v })} options={Object.entries(labels).filter(([key]) => ["salary_advance", "cash_withdrawal", "emergency_loan"].includes(key)).map(([value, label]) => ({ value, label }))} /><Field label="تاريخ الطلب" type="date" value={form.requestDate} onChange={(v) => setForm({ ...form, requestDate: v })} /><Field label="المبلغ (IQD)" type="number" value={form.amount} onChange={(v) => setForm({ ...form, amount: v })} required /><Field label="الخصم الشهري" type="number" value={form.monthlyDeduction} onChange={(v) => setForm({ ...form, monthlyDeduction: v })} /><Field label="تاريخ الاستحقاق" type="date" value={form.dueDate} onChange={(v) => setForm({ ...form, dueDate: v })} /><div className="md:col-span-2"><Field label="السبب" value={form.reason} onChange={(v) => setForm({ ...form, reason: v })} required /></div><div className="md:col-span-2"><Field label="ملاحظات" value={form.notes} onChange={(v) => setForm({ ...form, notes: v })} /></div><div className="md:col-span-2"><Field label="رابط مرفق (اختياري)" value={form.attachmentUrl} onChange={(v) => setForm({ ...form, attachmentUrl: v })} /></div><Button type="submit" className="md:col-span-2" disabled={create.isPending}>{create.isPending ? "جارٍ الحفظ…" : "إرسال الطلب"}</Button></form></Modal>}
    {repayment && <Modal title={`تسديد ${repayment.advanceNo}`} onClose={() => setRepayment(null)}><form className="grid gap-3" onSubmit={(e) => { e.preventDefault(); repay.mutate(); }}><p className="rounded-lg bg-muted p-3 text-sm">المتبقي الحالي: <b>{IQD.format(repayment.remainingAmount)}</b></p><Field label="المبلغ" type="number" value={payment.amount} onChange={(v) => setPayment({ ...payment, amount: v })} required /><Field label="التاريخ" type="date" value={payment.paymentDate} onChange={(v) => setPayment({ ...payment, paymentDate: v })} /><SelectField label="طريقة التسديد" value={payment.method} onChange={(v) => setPayment({ ...payment, method: v })} options={[{ value: "cash", label: "نقد" }, { value: "bank", label: "بنك" }, { value: "transfer", label: "تحويل" }, { value: "main_cashbox", label: "الصندوق الرئيسي" }]} /><Field label="ملاحظات" value={payment.notes} onChange={(v) => setPayment({ ...payment, notes: v })} /><Button type="submit" disabled={repay.isPending}>{repay.isPending ? "جارٍ التسجيل…" : "تأكيد التسديد"}</Button></form></Modal>}
    {settingsOpen && <Modal title="حدود وسياسات السلف" onClose={() => setSettingsOpen(false)}><form className="grid gap-3" onSubmit={(e) => { e.preventDefault(); saveSettings.mutate(new FormData(e.currentTarget)); }}><Field name="maxAdvanceAmount" label="أقصى مبلغ للسلفة (0 = بلا حد)" type="number" defaultValue={settings.data?.maxAdvanceAmount ?? "0"} /><Field name="maxSalaryPercentage" label="أقصى نسبة من الراتب" type="number" defaultValue={settings.data?.maxSalaryPercentage ?? "100"} /><Field name="maxActiveAdvances" label="أقصى عدد سلف نشطة" type="number" defaultValue={settings.data?.maxActiveAdvances ?? "1"} /><Field name="minimumEmploymentDays" label="الحد الأدنى لأيام الخدمة" type="number" defaultValue={settings.data?.minimumEmploymentDays ?? "0"} /><Field name="managerApprovalAmount" label="حد الاعتماد الإداري" type="number" defaultValue={settings.data?.managerApprovalAmount ?? "0"} /><Button type="submit" disabled={saveSettings.isPending}>حفظ السياسات</Button></form></Modal>}
  </div>;
}

function Metric({ title, value, danger }: { title: string; value: string; danger?: boolean }) { return <div className={`rounded-xl border p-3 ${danger ? "border-red-500/30 bg-red-500/5" : "border-border/50 bg-card"}`}><div className="text-xs text-muted-foreground">{title}</div><div className={`mt-1 text-lg font-bold ${danger ? "text-red-600" : ""}`}>{value}</div></div>; }
function Modal({ title, onClose, children }: { title: string; onClose: () => void; children: ReactNode }) { return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4" onMouseDown={onClose}><div className="max-h-[90dvh] w-full max-w-lg overflow-y-auto rounded-2xl border border-border bg-card p-5 shadow-xl" onMouseDown={(e) => e.stopPropagation()}><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">{title}</h2><button onClick={onClose}><X className="h-5 w-5" /></button></div>{children}</div></div>; }
function Field({ label, value, defaultValue, onChange, type = "text", required, name }: { label: string; value?: string; defaultValue?: string | number; onChange?: (value: string) => void; type?: string; required?: boolean; name?: string }) { return <label className="grid gap-1 text-sm"><span className="text-muted-foreground">{label}</span><input name={name} type={type} value={value} defaultValue={defaultValue} onChange={(e) => onChange?.(e.target.value)} required={required} className="rounded-lg border border-border bg-background px-3 py-2 outline-none focus:ring-2 focus:ring-primary/30" /></label>; }
function SelectField({ label, value, onChange, options, required }: { label: string; value: string; onChange: (value: string) => void; options: { value: string; label: string }[]; required?: boolean }) { return <label className="grid gap-1 text-sm"><span className="text-muted-foreground">{label}</span><select value={value} onChange={(e) => onChange(e.target.value)} required={required} className="rounded-lg border border-border bg-background px-3 py-2">{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
