import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "wouter";
import { AlertTriangle, BellRing, BrainCircuit, CalendarDays, Check, CircleDollarSign, ClipboardList, RefreshCw, Search, Settings2, ShieldAlert, Sparkles, Users, Warehouse, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useToast } from "@/hooks/use-toast";
import { adminFetch, apiErrorMessage, formatCurrency, type AdminMe } from "./_lib";

type Priority = "critical" | "high" | "medium" | "low";
type Alert = { id: string; priority: Priority; category: string; title: string; body: string; href: string; entityType?: string; entityId?: number };
type Event = { id: number; bookingNo: string; customerName: string; eventDate: string; eventTime: string | null; stage: string; timeline: Array<{ label: string; complete: boolean }>; score: { planning: number; financial: number; execution: number; satisfaction: number; staff: number; overall: number } };
type BrainData = { generatedAt: string; riskLevel: Priority; alerts: Alert[]; recommendations: Array<Alert & { recommendation: string }>; events: Event[]; metrics: { upcomingEvents: number; pendingCollections: number; lateTasks: number; lowStock: number; warehouseStatus: string; cashbox: number; todayRevenue: number; monthlyRevenue: number; payrollPending: number; absent: number; present: number; topEmployee: { name: string; completed: number } | null; topService: { name: string; total: number; revenue: number } | null; customerSatisfaction: number; netProfitForecast: number }; workload: Array<{ id: number; name: string; open_tasks: number }>; dailyBrief: { todayEvents: number; pendingPayments: number; lateTasks: number; warehouseAlerts: number; employeesAbsent: number; profitExpectedToday: number; estimatedWorkload: number } };
type Settings = { alertsEnabled: boolean; recommendationsEnabled: boolean; dailyBriefEnabled: boolean; executiveSummaryEnabled: boolean; warehouseAnalysisEnabled: boolean; payrollAnalysisEnabled: boolean; accountingAnalysisEnabled: boolean; customerAnalysisEnabled: boolean };

const priorityStyle: Record<Priority, string> = { critical: "border-destructive/45 bg-destructive/10 text-destructive", high: "border-status-warning/45 bg-status-warning/10 text-status-warning", medium: "border-primary/35 bg-primary/10 text-primary", low: "border-border/40 bg-muted/40 text-muted-foreground" };
const priorityLabel: Record<Priority, string> = { critical: "حرج", high: "عالٍ", medium: "متوسط", low: "منخفض" };
const scoreStyle = (value: number) => value >= 80 ? "text-status-success" : value >= 60 ? "text-status-warning" : "text-destructive";

function Metric({ label, value, icon: Icon, href }: { label: string; value: string; icon: typeof BrainCircuit; href?: string }) {
  const body = <><Icon className="h-4 w-4 text-primary" /><p className="mt-5 text-xl font-bold tabular-nums text-foreground">{value}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></>;
  return href ? <Link href={href} className="rounded-2xl border border-border/40 bg-card p-4 shadow-sm transition-colors hover:border-primary/45 hover:bg-primary/[0.035]">{body}</Link> : <div className="rounded-2xl border border-border/40 bg-card p-4 shadow-sm">{body}</div>;
}

export default function EventBrainPage({ me }: { me: AdminMe }) {
  const { toast } = useToast(); const client = useQueryClient(); const [search, setSearch] = useState(""); const [searchOpen, setSearchOpen] = useState(false);
  const canSettings = me.role === "admin" || me.role === "manager" || me.permissions.includes("ai_settings_manage");
  const brain = useQuery({ queryKey: ["admin", "event-brain"], queryFn: () => adminFetch<BrainData>("/admin/event-brain/dashboard"), refetchInterval: 60_000 });
  const settings = useQuery({ queryKey: ["admin", "event-brain", "settings"], queryFn: () => adminFetch<any>("/admin/event-brain/settings"), enabled: canSettings });
  const searchQuery = useQuery({ queryKey: ["admin", "event-brain", "search", search], queryFn: () => adminFetch<{ intent: string; results: Array<{ id: number; reference?: string; title: string; amount: number; detail: string }> }>(`/admin/event-brain/search?q=${encodeURIComponent(search)}`), enabled: search.trim().length >= 2 });
  const refresh = useMutation({ mutationFn: () => adminFetch<BrainData>("/admin/event-brain/refresh", { method: "POST" }), onSuccess: (data) => { client.setQueryData(["admin", "event-brain"], data); toast({ title: "تم تحديث تحليل عقل الفعاليات" }); }, onError: (error: Error) => toast({ title: "تعذر تحديث التحليل", description: error.message, variant: "destructive" }) });
  const feedback = useMutation({ mutationFn: ({ insightId, action }: { insightId: string; action: "accepted" | "ignored" }) => adminFetch("/admin/event-brain/feedback", { method: "POST", body: JSON.stringify({ insightId, action }) }), onSuccess: (_row, variables) => toast({ title: variables.action === "accepted" ? "تم اعتماد التوصية" : "تم تجاهل التوصية" }) });
  const notify = useMutation({ mutationFn: (alert: Alert) => adminFetch("/admin/event-brain/notify", { method: "POST", body: JSON.stringify(alert) }), onSuccess: () => toast({ title: "تم إرسال التنبيه للمديرين" }), onError: (error: Error) => toast({ title: "تعذر إرسال التنبيه", description: error.message, variant: "destructive" }) });
  const saveSettings = useMutation({ mutationFn: (values: Settings) => adminFetch("/admin/event-brain/settings", { method: "PUT", body: JSON.stringify(values) }), onSuccess: () => { client.invalidateQueries({ queryKey: ["admin", "event-brain", "settings"] }); toast({ title: "تم حفظ إعدادات عقل الفعاليات" }); } });
  const data = brain.data;
  const formSettings = useMemo<Settings>(() => ({ alertsEnabled: settings.data?.alerts_enabled ?? true, recommendationsEnabled: settings.data?.recommendations_enabled ?? true, dailyBriefEnabled: settings.data?.daily_brief_enabled ?? true, executiveSummaryEnabled: settings.data?.executive_summary_enabled ?? true, warehouseAnalysisEnabled: settings.data?.warehouse_analysis_enabled ?? true, payrollAnalysisEnabled: settings.data?.payroll_analysis_enabled ?? true, accountingAnalysisEnabled: settings.data?.accounting_analysis_enabled ?? true, customerAnalysisEnabled: settings.data?.customer_analysis_enabled ?? true }), [settings.data]);
  if (brain.isLoading) return <div className="space-y-4" dir="rtl"><Skeleton className="h-36 rounded-3xl" /><div className="grid grid-cols-2 gap-3">{Array.from({ length: 8 }).map((_, i) => <Skeleton key={i} className="h-28 rounded-2xl" />)}</div></div>;
  if (!data) return <div className="rounded-2xl border border-destructive/30 bg-destructive/5 p-6 text-center" dir="rtl"><p className="font-semibold">تعذر تحميل عقل الفعاليات</p><p className="mt-1 text-sm text-muted-foreground">{apiErrorMessage(brain.error)}</p><Button className="mt-4" onClick={() => brain.refetch()}>إعادة المحاولة</Button></div>;
  return <main className="space-y-5" dir="rtl">
    <section className="relative overflow-hidden rounded-3xl border border-primary/25 bg-gradient-to-bl from-primary/15 via-card to-card p-5 sm:p-7"><div className="absolute -left-6 -top-7 h-32 w-32 rounded-full bg-primary/10 blur-2xl" /><div className="relative flex flex-wrap items-start justify-between gap-4"><div><div className="inline-flex items-center gap-2 rounded-full bg-primary/12 px-3 py-1 text-xs font-semibold text-primary"><BrainCircuit className="h-3.5 w-3.5" /> تحليل تشغيلي مباشر</div><h1 className="mt-3 text-2xl font-bold tracking-tight text-foreground sm:text-3xl">عقل الفعاليات</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">يقرأ مؤشرات AJN الحالية ليعطي تنبيهات قابلة للتنفيذ قبل أن تتحول إلى مشكلة تشغيلية.</p></div><div className="flex flex-wrap gap-2"><span className={`rounded-xl border px-3 py-2 text-sm font-semibold ${priorityStyle[data.riskLevel]}`}>مستوى المخاطر: {priorityLabel[data.riskLevel]}</span><Button size="sm" variant="outline" onClick={() => refresh.mutate()} disabled={refresh.isPending} className="gap-1.5"><RefreshCw className={`h-4 w-4 ${refresh.isPending ? "animate-spin" : ""}`} /> تحديث التحليل</Button></div></div></section>
    <section className="grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-6"><Metric label="فعاليات قادمة" value={data.metrics.upcomingEvents.toLocaleString("ar-IQ")} icon={CalendarDays} href="/admin/kosha-bookings" /><Metric label="تحصيلات معلقة" value={formatCurrency(data.metrics.pendingCollections)} icon={CircleDollarSign} href="/admin/accounting?tab=receivables" /><Metric label="مهام متأخرة" value={data.metrics.lateTasks.toLocaleString("ar-IQ")} icon={ClipboardList} href="/admin/tasks" /><Metric label="تنبيهات مستودع" value={data.metrics.lowStock.toLocaleString("ar-IQ")} icon={Warehouse} href="/admin/inventory-alerts" /><Metric label="حاضرون اليوم" value={data.metrics.present.toLocaleString("ar-IQ")} icon={Users} href="/admin/attendance" /><Metric label="إيراد اليوم" value={formatCurrency(data.metrics.todayRevenue)} icon={Sparkles} href="/admin/finance/master-cash" /></section>
    <section className="rounded-2xl border border-border/40 bg-card p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-semibold">اسأل بيانات AJN</h2><p className="text-xs text-muted-foreground">اكتب سؤالاً مثل: من عليه مبلغ متبقٍ؟ أو من لديه مهام أكثر؟</p></div><Button size="sm" variant="outline" onClick={() => setSearchOpen((value) => !value)} className="gap-1.5"><Search className="h-4 w-4" /> بحث ذكي</Button></div>{searchOpen && <div className="mt-4"><input autoFocus value={search} onChange={(event) => setSearch(event.target.value)} placeholder="ابحث عن دفعات، مهام، ورد، مخزون أو صيانة…" className="h-11 w-full rounded-xl border border-border/45 bg-background px-3 text-sm outline-none focus:border-primary/60" />{searchQuery.isFetching && <p className="mt-2 text-xs text-muted-foreground">جارٍ البحث…</p>}{searchQuery.data && <div className="mt-3 grid gap-2 sm:grid-cols-2">{searchQuery.data.results.map((row) => <div key={row.id} className="rounded-xl bg-background/70 p-3"><p className="font-medium">{row.title}</p><p className="mt-1 text-xs text-muted-foreground">{row.reference ? `${row.reference} · ` : ""}{row.detail}</p>{Number.isFinite(Number(row.amount)) && <p className="mt-2 text-sm font-semibold text-primary">{row.amount.toLocaleString("ar-IQ")}</p>}</div>)}</div>}</div>}</section>
    <Tabs defaultValue="alerts" className="space-y-4"><TabsList className="w-full justify-start overflow-x-auto"><TabsTrigger value="alerts">التنبيهات ({data.alerts.length})</TabsTrigger><TabsTrigger value="recommendations">التوصيات</TabsTrigger><TabsTrigger value="events">خط زمني للفعاليات</TabsTrigger><TabsTrigger value="brief">ملخص اليوم</TabsTrigger>{canSettings && <TabsTrigger value="settings">الإعدادات</TabsTrigger>}</TabsList>
      <TabsContent value="alerts" className="space-y-3">{data.alerts.length === 0 ? <div className="rounded-2xl border border-status-success/30 bg-status-success/5 p-6 text-center text-sm text-status-success">لا توجد تنبيهات تشغيلية نشطة حالياً.</div> : data.alerts.map((alert) => <article key={alert.id} className={`rounded-2xl border p-4 ${priorityStyle[alert.priority]}`}><div className="flex gap-3"><ShieldAlert className="mt-0.5 h-5 w-5 shrink-0" /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">{alert.title}</h3><span className="rounded-full bg-background/45 px-2 py-0.5 text-[11px]">{priorityLabel[alert.priority]}</span></div><p className="mt-1 text-sm leading-6 opacity-90">{alert.body}</p><div className="mt-3 flex flex-wrap gap-2"><Link href={alert.href} className="rounded-lg bg-background/60 px-3 py-1.5 text-xs font-semibold hover:bg-background">فتح المصدر</Link><Button size="sm" variant="ghost" className="h-8 gap-1 text-xs" onClick={() => notify.mutate(alert)} disabled={notify.isPending}><BellRing className="h-3.5 w-3.5" /> إشعار</Button></div></div></div></article>)}</TabsContent>
      <TabsContent value="recommendations" className="grid gap-3 lg:grid-cols-2">{data.recommendations.map((item) => <article key={item.id} className="rounded-2xl border border-border/40 bg-card p-4"><div className="flex gap-3"><Sparkles className="mt-0.5 h-5 w-5 text-primary" /><div className="min-w-0 flex-1"><h3 className="font-semibold">{item.title}</h3><p className="mt-1 text-sm text-muted-foreground">{item.recommendation}</p><p className="mt-3 text-xs text-muted-foreground">{item.body}</p><div className="mt-4 flex gap-2"><Button size="sm" onClick={() => feedback.mutate({ insightId: item.id, action: "accepted" })} disabled={feedback.isPending} className="gap-1"><Check className="h-3.5 w-3.5" /> اعتماد</Button><Button size="sm" variant="outline" onClick={() => feedback.mutate({ insightId: item.id, action: "ignored" })} disabled={feedback.isPending} className="gap-1"><X className="h-3.5 w-3.5" /> تجاهل</Button><Link href={item.href} className="ms-auto self-center text-xs text-primary hover:underline">فتح المصدر</Link></div></div></div></article>)}</TabsContent>
      <TabsContent value="events" className="space-y-4">{data.events.map((event) => <article key={event.id} className="rounded-2xl border border-border/40 bg-card p-4 sm:p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">{event.bookingNo} · {event.customerName}</h3><p className="mt-1 text-xs text-muted-foreground">{event.eventDate}{event.eventTime ? ` · ${event.eventTime}` : ""} · المرحلة: {event.stage}</p></div><span className={`text-xl font-bold tabular-nums ${scoreStyle(event.score.overall)}`}>{event.score.overall}%</span></div><div className="mt-4 flex gap-1 overflow-x-auto pb-2">{event.timeline.map((step, index) => <div key={step.label} className="flex min-w-24 flex-1 items-center gap-1"><div className={`h-2.5 w-2.5 shrink-0 rounded-full ${step.complete ? "bg-primary" : "bg-muted"}`} /><span className={`whitespace-nowrap text-[11px] ${step.complete ? "text-foreground" : "text-muted-foreground"}`}>{step.label}</span>{index < event.timeline.length - 1 && <span className="h-px min-w-4 flex-1 bg-border" />}</div>)}</div><div className="mt-4 grid grid-cols-5 gap-2 text-center text-xs">{Object.entries(event.score).filter(([key]) => key !== "overall").map(([key, value]) => <div key={key} className="rounded-lg bg-background/65 p-2"><p className={`font-bold ${scoreStyle(value)}`}>{value}%</p><p className="mt-1 text-muted-foreground">{{ planning: "تخطيط", financial: "مالي", execution: "تنفيذ", satisfaction: "رضا", staff: "فريق" }[key]}</p></div>)}</div></article>)}</TabsContent>
      <TabsContent value="brief" className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[["فعاليات اليوم", data.dailyBrief.todayEvents, CalendarDays], ["دفعات تحتاج متابعة", data.dailyBrief.pendingPayments, AlertTriangle], ["غياب الموظفين", data.dailyBrief.employeesAbsent, Users], ["عبء العمل", data.dailyBrief.estimatedWorkload, ClipboardList]].map(([label, value, Icon]: any) => <div key={label} className="rounded-2xl border border-border/40 bg-card p-4"><Icon className="h-5 w-5 text-primary" /><p className="mt-4 text-2xl font-bold">{Number(value).toLocaleString("ar-IQ")}</p><p className="mt-1 text-xs text-muted-foreground">{label}</p></div>)}<div className="rounded-2xl border border-primary/30 bg-primary/5 p-4 sm:col-span-2"><p className="text-sm font-semibold">توقع إيراد اليوم</p><p className="mt-3 text-2xl font-bold text-primary">{formatCurrency(data.dailyBrief.profitExpectedToday)}</p><p className="mt-1 text-xs text-muted-foreground">يتحدث من الحركات المالية المنفذة فقط.</p></div></TabsContent>
      {canSettings && <TabsContent value="settings"><SettingsPanel initial={formSettings} saving={saveSettings.isPending} onSave={(values) => saveSettings.mutate(values)} /></TabsContent>}
    </Tabs>
  </main>;
}

function SettingsPanel({ initial, saving, onSave }: { initial: Settings; saving: boolean; onSave: (values: Settings) => void }) { const [values, setValues] = useState(initial); const labels: Array<[keyof Settings, string]> = [["alertsEnabled", "تنبيهات الذكاء"], ["recommendationsEnabled", "التوصيات الذكية"], ["dailyBriefEnabled", "الملخص اليومي"], ["executiveSummaryEnabled", "الملخص التنفيذي"], ["warehouseAnalysisEnabled", "تحليل المستودع"], ["payrollAnalysisEnabled", "تحليل الرواتب"], ["accountingAnalysisEnabled", "تحليل المحاسبة"], ["customerAnalysisEnabled", "تحليل العملاء"]]; return <section className="rounded-2xl border border-border/40 bg-card p-4"><h3 className="font-semibold">إعدادات عقل الفعاليات</h3><div className="mt-4 grid gap-2 sm:grid-cols-2">{labels.map(([key, label]) => <label key={key} className="flex items-center justify-between rounded-xl bg-background/60 px-3 py-3 text-sm"><span>{label}</span><input type="checkbox" checked={values[key]} onChange={(event) => setValues({ ...values, [key]: event.target.checked })} className="h-4 w-4 accent-primary" /></label>)}</div><Button className="mt-4" onClick={() => onSave(values)} disabled={saving}><Settings2 className="ms-1 h-4 w-4" /> حفظ الإعدادات</Button></section>; }
