import { useEffect, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useLocation } from "wouter";
import { CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Crown, FileDown, Loader2, Plus, Search, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { useToast } from "@/hooks/use-toast";
import { adminFetch, formatCurrency } from "./_lib";
import { EditKoshaBookingModal } from "./koshas";
import { BookingQuickView, managerDetailQuery } from "@/components/kosha-bookings/booking-quick-view";
import { BookingActivityIndicators, BookingStatusBadge, KoshaThumbnail, PaymentStatusBadge } from "@/components/kosha-bookings/booking-presentation";
import { bookingIdentity, bookingLabels, displayEventDate, displayEventTime, paymentLabels } from "@/lib/kosha-manager";
import type { KoshaManagerBooking, KoshaManagerList } from "@/lib/kosha-manager-contract";

const quickFilters=[["","الكل"],["today","اليوم"],["tomorrow","غداً"],["week","هذا الأسبوع"],["upcoming","القادمة"],["unpaid","غير المدفوعة"],["in_progress","قيد التنفيذ"],["completed","مكتملة"]];
const field="h-11 min-w-0 rounded-xl border border-[#e8e4dd] bg-white px-3 text-sm outline-none focus:border-[#b69764] focus:ring-2 focus:ring-[#b69764]/20";
export default function AdminKoshaBookingsPage(){
  const client=useQueryClient();const {toast}=useToast();const [,navigate]=useLocation();
  const [search,setSearch]=useState("");const [debounced,setDebounced]=useState("");
  const [filters,setFilters]=useState<Record<string,string>>({});const [page,setPage]=useState(1);const [pageSize,setPageSize]=useState(10);
  const [view,setView]=useState<KoshaManagerBooking|null>(null);const [editing,setEditing]=useState<KoshaManagerBooking|null>(null);const [loadingEdit,setLoadingEdit]=useState<string|null>(null);
  useEffect(()=>{const id=setTimeout(()=>{setDebounced(search);setPage(1);},300);return()=>clearTimeout(id);},[search]);
  const params=new URLSearchParams({...filters,search:debounced,page:String(page),pageSize:String(pageSize)});
  const query=useQuery({queryKey:["admin","kosha-manager","list",params.toString()],queryFn:()=>adminFetch<KoshaManagerList>(`/admin/kosha-bookings/manager-view?${params}`),staleTime:30_000,refetchOnWindowFocus:true});
  const data=query.data;
  const filter=(key:string,value:string)=>{setFilters(f=>({...f,[key]:value}));setPage(1);};
  const reset=()=>{setSearch("");setDebounced("");setFilters({});setPage(1);};
  const edit=async(b:KoshaManagerBooking)=>{setLoadingEdit(bookingIdentity(b));try{const detail=await client.fetchQuery({...managerDetailQuery(b),staleTime:0});setView(null);setEditing(detail.booking);}catch(error){toast({title:"تعذر فتح التعديل",description:error instanceof Error?error.message:"تعذر تحميل تفاصيل الحجز",variant:"destructive"});}finally{setLoadingEdit(null);}};
  const full=(b:KoshaManagerBooking)=>navigate(`/admin/bookings/${b.source==="service"?"service":"kosha"}/${b.id}`);
  const exportPage=()=>{
    if(!data)return;
    const clean=(v:unknown)=>`"${String(v??"").replace(/^[=+@-]/,"'$&").replaceAll('"','""')}"`;
    const rows=[["الحجز","الكوشة","الزبون","الهاتف","تاريخ المناسبة","الإجمالي","المدفوع","المتبقي","حالة الدفع","الحالة"],...data.items.map(b=>[b.number,b.koshaName,b.customerName,b.phone,b.eventDate,b.totalAmount,b.paidAmount,b.remainingAmount,paymentLabels[b.paymentStatus]||b.paymentStatus,bookingLabels[b.status]||b.status])];
    const url=URL.createObjectURL(new Blob(["\ufeff"+rows.map(r=>r.map(clean).join(",")).join("\r\n")],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=`kosha-bookings-page-${data.page}.csv`;a.click();URL.revokeObjectURL(url);
  };
  const actions=(b:KoshaManagerBooking)=><div className="flex items-center gap-1"><Button size="sm" variant="outline" className="rounded-lg" onClick={()=>setView(b)}>تفاصيل</Button><Button size="sm" variant="ghost" disabled={loadingEdit!==null} onClick={()=>void edit(b)}>{loadingEdit===bookingIdentity(b)?<Loader2 className="h-4 w-4 animate-spin"/>:"تعديل"}</Button></div>;
  return <div dir="rtl" className="min-w-0 space-y-5 rounded-[22px] bg-[#faf9f6] p-3 text-slate-900 md:p-5"><header className="flex flex-wrap items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="flex h-12 w-12 items-center justify-center rounded-2xl border border-[#e9dfca] bg-[#f5eddf] text-[#a17b40]"><Crown strokeWidth={1.5}/></span><div><h1 className="text-2xl font-semibold">حجوزات الكوشات</h1><p className="mt-1 text-sm text-slate-500">إدارة حجوزات الكوشات ومتابعة التنفيذ من الحجز إلى التسليم</p></div></div><div className="flex gap-2"><Button asChild className="rounded-xl"><Link href="/admin/bookings"><Plus size={17}/>حجز كوشة جديدة</Link></Button><Button variant="outline" className="rounded-xl" onClick={exportPage} disabled={!data?.items.length}><FileDown size={16}/>CSV الصفحة</Button></div></header>
    <section aria-label="ملخص الحجوزات" className="grid grid-cols-2 gap-3 lg:grid-cols-5">{[{key:"total",label:"إجمالي الحجوزات",Icon:Crown,color:"text-[#a17b40]"},{key:"completed",label:"مكتملة",Icon:CheckCircle2,color:"text-emerald-700"},{key:"inProgress",label:"قيد التنفيذ",Icon:Loader2,color:"text-blue-700"},{key:"upcoming",label:"قادمة",Icon:CalendarDays,color:"text-amber-700"},{key:"cancelled",label:"ملغاة",Icon:XCircle,color:"text-rose-700"}].map(({key,label,Icon,color})=><div key={key} className="flex items-center justify-between gap-3 rounded-2xl border border-[#eee9e2] bg-white p-4"><div><p className="text-xs text-slate-500">{label}</p>{data?<p className="mt-2 text-2xl font-semibold tabular-nums">{data.stats[key as keyof typeof data.stats]}</p>:<Skeleton className="mt-2 h-8 w-12"/>}</div><Icon className={color} size={22} strokeWidth={1.5}/></div>)}</section>
    <section aria-label="فلاتر الحجوزات" className="space-y-3 rounded-2xl border border-[#eee9e2] bg-white p-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><label className="relative sm:col-span-2"><span className="sr-only">البحث في الحجوزات</span><Search className="absolute right-3 top-3.5 text-slate-400" size={17}/><input className={`${field} w-full pr-10`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="ابحث بالاسم أو الهاتف أو رقم الحجز…"/></label><select aria-label="الكوشة" className={field} value={filters.koshaId||""} onChange={e=>filter("koshaId",e.target.value)}><option value="">كل أنواع الكوشات</option>{data?.koshas.map(k=><option key={k.id} value={k.id}>{k.name}</option>)}</select><select aria-label="حالة الحجز" className={field} value={filters.status||""} onChange={e=>filter("status",e.target.value)}><option value="">كل الحالات</option>{Object.entries(bookingLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select aria-label="حالة الدفع" className={field} value={filters.paymentStatus||""} onChange={e=>filter("paymentStatus",e.target.value)}><option value="">حالة الدفع</option>{Object.entries(paymentLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div><div className="flex flex-wrap items-center gap-3"><label className="flex items-center gap-2 text-xs text-slate-500">من<input type="date" className={field} value={filters.dateFrom||""} onChange={e=>filter("dateFrom",e.target.value)}/></label><label className="flex items-center gap-2 text-xs text-slate-500">إلى<input type="date" className={field} value={filters.dateTo||""} onChange={e=>filter("dateTo",e.target.value)}/></label><Button variant="ghost" onClick={reset}>إعادة تعيين</Button></div><div className="flex gap-2 overflow-x-auto pb-1">{quickFilters.map(([value,label])=><button type="button" key={value} aria-pressed={(filters.quick||"")===value} onClick={()=>filter("quick",value)} className={`min-h-10 shrink-0 rounded-xl px-3 text-sm transition-colors ${(filters.quick||"")===value?"bg-[#f8e8eb] font-medium text-[#963b51]":"bg-[#faf9f6] text-slate-600 hover:bg-[#f1ede6]"}`}>{label}</button>)}</div></section>
    {query.isError?<section role="alert" className="space-y-3 rounded-2xl border border-rose-100 bg-white p-6"><h2 className="font-semibold">تعذر تحميل الحجوزات</h2><p className="text-sm text-slate-500">{query.error.message}</p><Button onClick={()=>query.refetch()} variant="outline">إعادة المحاولة</Button></section>:query.isPending?<div className="space-y-3" aria-label="جارٍ تحميل الحجوزات">{Array.from({length:5},(_,i)=><Skeleton key={i} className="h-20 rounded-2xl"/>)}</div>:data&&!data.items.length?<section className="rounded-2xl border bg-white py-12 text-center"><Crown className="mx-auto mb-4 text-[#b39768]"/><h2 className="font-semibold">لا توجد حجوزات مطابقة</h2><p className="my-3 text-sm text-slate-500">جرّب تغيير البحث أو الفلاتر.</p><Button variant="outline" onClick={reset}>إعادة تعيين الفلاتر</Button></section>:data&&<>
    <div className="hidden overflow-x-auto rounded-2xl border border-[#eee9e2] bg-white lg:block"><table className="w-full min-w-[1120px] text-right text-sm"><thead className="bg-[#f7f5f1] text-xs font-medium text-slate-500"><tr>{["الكوشة","الزبون","الهاتف","الموعد","الإجمالي","المدفوع","المتبقي","حالة الدفع","الحالة","آخر تحديث","إجراءات"].map(h=><th key={h} className="whitespace-nowrap px-3 py-4 font-medium">{h}</th>)}</tr></thead><tbody>{data.items.map(b=><tr key={bookingIdentity(b)} className="border-t border-[#f2eee8] transition-colors hover:bg-[#fdfbf8]"><td className="px-3 py-3"><KoshaThumbnail booking={b}/></td><td className="px-3 py-3"><p className="min-w-24 max-w-44 break-words font-medium">{b.customerName}</p><BookingActivityIndicators booking={b} onClick={()=>setView(b)}/></td><td className="px-3 py-3"><bdi className="whitespace-nowrap text-xs">{b.phone||"—"}</bdi></td><td className="px-3 py-3"><p className="whitespace-nowrap text-xs">{displayEventDate(b.eventDate)}</p><p className="mt-1 text-xs text-slate-500">{displayEventTime(b.eventTime)}</p></td><td className="whitespace-nowrap px-3 py-3 text-xs font-semibold">{b.paymentStatus==="pending_pricing"?"بانتظار التسعير":formatCurrency(b.totalAmount)}</td><td className="whitespace-nowrap px-3 py-3 text-xs text-emerald-800">{formatCurrency(b.paidAmount)}</td><td className="whitespace-nowrap px-3 py-3 text-xs font-semibold">{formatCurrency(b.remainingAmount)}</td><td className="px-3 py-3"><PaymentStatusBadge status={b.paymentStatus}/></td><td className="px-3 py-3"><BookingStatusBadge status={b.status}/>{b.executionStage&&b.status!=="cancelled"&&<p className="mt-1"><BookingStatusBadge status={b.executionStage} execution/></p>}</td><td className="px-3 py-3 text-xs text-slate-500">{displayEventDate(b.updatedAt)}</td><td className="px-3 py-3">{actions(b)}</td></tr>)}</tbody></table></div>
    <div className="grid gap-3 sm:grid-cols-2 lg:hidden">{data.items.map(b=><article key={bookingIdentity(b)} className="space-y-4 rounded-[20px] border border-[#eee9e2] bg-white p-4"><KoshaThumbnail booking={b}/><div><h2 className="break-words font-semibold">{b.customerName}</h2><p className="mt-1 text-sm text-slate-500"><bdi>{b.phone||"—"}</bdi></p></div><p className="text-sm">{displayEventDate(b.eventDate)} · {displayEventTime(b.eventTime)}</p><div className="grid grid-cols-2 gap-3 rounded-xl bg-[#faf9f6] p-3 text-xs"><div className="space-y-1"><span className="text-slate-500">الإجمالي</span><p className="font-semibold">{b.paymentStatus==="pending_pricing"?"بانتظار التسعير":formatCurrency(b.totalAmount)}</p></div><div className="space-y-1"><span className="text-slate-500">المتبقي</span><p className="font-semibold">{formatCurrency(b.remainingAmount)}</p></div></div><div className="flex flex-wrap gap-2"><PaymentStatusBadge status={b.paymentStatus}/><BookingStatusBadge status={b.status}/></div><BookingActivityIndicators booking={b} onClick={()=>setView(b)}/>{actions(b)}</article>)}</div>
    <footer className="flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-[#eee9e2] bg-white p-4 text-sm"><p className="text-slate-500">عرض {(data.page-1)*data.pageSize+1}–{Math.min(data.page*data.pageSize,data.total)} من {data.total} حجز</p><div className="flex items-center gap-2"><select aria-label="عدد الحجوزات في الصفحة" className={field} value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1);}}>{[10,25,50].map(n=><option key={n} value={n}>{n}</option>)}</select><Button size="icon" variant="outline" aria-label="الصفحة السابقة" disabled={data.page<=1} onClick={()=>setPage(data.page-1)}><ChevronRight size={16}/></Button><span>{data.page} / {Math.ceil(data.total/data.pageSize)}</span><Button size="icon" variant="outline" aria-label="الصفحة التالية" disabled={data.page*data.pageSize>=data.total} onClick={()=>setPage(data.page+1)}><ChevronLeft size={16}/></Button></div></footer></>}
    {view&&<BookingQuickView booking={view} onClose={()=>setView(null)} onEdit={b=>void edit(b)} onFull={full}/>}
    {editing&&<EditKoshaBookingModal booking={editing} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);void client.invalidateQueries({queryKey:["admin","kosha-manager"]});void client.invalidateQueries({queryKey:["admin","kosha-bookings"]});}}/>}
  </div>;
}
