import { useMemo, useState } from "react";
import { Link, useParams } from "wouter";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, Download, Printer, QrCode } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import { adminFetch, formatCurrency } from "./_lib";
import { EmptyState } from "./_layout";
import { useToast } from "@/hooks/use-toast";

type KoshaOption = { id: number; name: string; financialCode?: string | null; mainImage?: string | null };
type FinanceResponse = {
  kosha: KoshaOption;
  period: { from: string | null; to: string | null; basis: string };
  summary: {
    totalInvestment: number; lifetimeInvestment: number; bookingRevenue: number;
    collectedRevenue: number; customerRemaining: number; operatingCosts: number;
    bookingCosts: number; bookingProfit: number; recoveredInvestment: number;
    remainingInvestment: number; recoveryPercent: number; bookingCount: number;
    upcomingBookingCount: number; supplierPayable: number;
    lifetimeBookingRevenue: number;
  };
  statement: Array<{ date: string; description: string; category: string | null; amount: number; sourceKey: string; sourceType: string; reference: string; supplierName: string; bookingId: number | null; status: string; impact: string }>;
  bookings: Array<{ id: number; trackingCode: string | null; customerName: string; eventDate: string; totalAmount: number; collectedCurrent: number; remainingCurrent: number }>;
  operations: {
    projects: Array<{ id: number; plannedBudget: number; actualCost: number; remainingBudget: number; budgetVariance: number; stage: string; createdOn: string; expectedCompletionDate: string | null; notes: string | null }>;
    assetAssignments: Array<{ id: number; productId: number; quantity: string; shared: boolean; storageLocation: string | null; notes: string | null; assignedAt: string }>;
    maintenanceRecords: Array<{ id: number; productId: number | null; maintenanceType: string; maintenanceDate: string; description: string; parts: string[]; nextMaintenanceDate: string | null; expenseId: number | null }>;
    damageReports: Array<{ id: number; productId: number | null; bookingId: number | null; incidentType: string | null; reason: string | null; description: string; estimatedRepairCost: string | null; estimatedReplacementCost: string | null; status: string; createdAt: string }>;
    timeline: Array<{ id: number; action: string; userName: string; metadata: Record<string, unknown>; createdAt: string }>;
    upcomingPreparations: Array<{ bookingId: number; bookingNo: string; customerName: string; eventDate: string; workOrderId: number | null; workOrderStatus: string | null; checklistTotal: number; checklistComplete: number; missingChecklist: string[]; assignedAssets: Array<{ productId: number; name: string; checkedOut: boolean; returned: boolean }> }>;
  };
};

const tabs = [
  ["overview", "نظرة عامة"], ["materials", "المواد"], ["purchases", "المشتريات"],
  ["expenses", "المصاريف"], ["assets", "الأصول"], ["maintenance", "الصيانة"],
  ["bookings", "الحجوزات"], ["booking-costs", "تكاليف الحجوزات"], ["damage", "التلف والفقدان"],
  ["account", "حساب الكوشة"], ["investment", "الاستثمار"], ["timeline", "السجل"],
] as const;

function currentMonthStart() { return new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10); }
function downloadStatement(rows: FinanceResponse["statement"], code: string) {
  const csv = [
    ["التاريخ", "البيان", "التصنيف", "المرجع", "الحجز", "المورد", "المبلغ", "الأثر"],
    ...rows.map((row) => [row.date, row.description, row.category ?? "", row.reference, row.bookingId ?? "", row.supplierName, row.amount, row.impact]),
  ].map((row) => row.map((cell) => `"${String(cell ?? "").replaceAll('"', '""')}"`).join(",")).join("\r\n");
  const url = URL.createObjectURL(new Blob(["\uFEFF", csv], { type: "text/csv;charset=utf-8" }));
  const link = document.createElement("a"); link.href = url; link.download = `${code}-statement.csv`; link.click(); URL.revokeObjectURL(url);
}

export default function KoshaFinancePage() {
  const queryClient = useQueryClient();
  const { toast } = useToast();
  const params = useParams<{ id?: string }>();
  const id = Number(params.id ?? 0);
  const [tab, setTab] = useState<(typeof tabs)[number][0]>("overview");
  const [from, setFrom] = useState(currentMonthStart());
  const [to, setTo] = useState(new Date().toISOString().slice(0, 10));
  const koshasQuery = useQuery<KoshaOption[]>({ queryKey: ["admin", "koshas", "finance-picker"], queryFn: () => adminFetch("/admin/koshas") });
  const financeQuery = useQuery<FinanceResponse>({
    queryKey: ["admin", "kosha-finance", id, from, to],
    queryFn: () => adminFetch(`/admin/kosha-finance/${id}?from=${encodeURIComponent(from)}&to=${encodeURIComponent(to)}`),
    enabled: id > 0,
  });
  const productsQuery = useQuery<Array<{ id: number; name: string; nameAr?: string; barcode?: string | null }>>({ queryKey: ["admin", "products-all"], queryFn: () => adminFetch("/admin/products?limit=500"), enabled: id > 0 });
  const saveOperation = useMutation({
    mutationFn: ({ path, method = "POST", payload }: { path: string; method?: string; payload: Record<string, unknown> }) => adminFetch(path, { method, body: JSON.stringify(payload) }),
    onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ["admin", "kosha-finance", id] }); toast({ title: "تم حفظ السجل" }); },
    onError: (error: Error) => toast({ title: "تعذر الحفظ", description: error.message, variant: "destructive" }),
  });
  const [passportQr, setPassportQr] = useState<{ dataUrl: string; targetUrl: string } | null>(null);
  const passportQrMutation = useMutation({
    mutationFn: () => adminFetch<{ dataUrl: string; targetUrl: string }>(`/admin/kosha-finance/${id}/passport-qr`, { method: "POST", body: "{}" }),
    onSuccess: (qr) => setPassportQr(qr),
    onError: (error: Error) => toast({ title: "تعذر إنشاء رمز الجواز", description: error.message, variant: "destructive" }),
  });
  const visibleRows = useMemo(() => {
    const rows = financeQuery.data?.statement ?? [];
    if (tab === "purchases" || tab === "materials" || tab === "assets") return rows.filter((row) => row.sourceType === "purchase_invoice_item");
    if (tab === "expenses" || tab === "maintenance" || tab === "damage") return rows.filter((row) => row.sourceType === "expense");
    if (tab === "bookings") return rows.filter((row) => row.sourceType === "kosha_booking");
    if (tab === "booking-costs") return rows.filter((row) => row.category === "booking");
    if (tab === "investment") return rows.filter((row) => row.category === "investment");
    if (tab === "account" || tab === "timeline") return rows;
    return [];
  }, [financeQuery.data, tab]);

  if (!id) return <div dir="rtl" className="space-y-5">
    <div><h1 className="text-2xl font-bold">حسابات الكوشات</h1><p className="text-sm text-muted-foreground">اختر كوشة لعرض ملخصها المالي وكشف حسابها.</p></div>
    {koshasQuery.isLoading ? <Skeleton className="h-40 w-full rounded-xl" /> : koshasQuery.isError ? <p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">تعذر تحميل الكوشات. أعد المحاولة.</p> : (koshasQuery.data ?? []).length === 0 ? <EmptyState message="لا توجد كوشات" /> : <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{koshasQuery.data!.map((kosha) => <Link key={kosha.id} href={`/admin/kosha-finance/${kosha.id}`} className="rounded-xl border bg-card p-4 transition hover:border-primary/40"><p className="text-xs text-muted-foreground">{kosha.financialCode ?? `KOSHA-${kosha.id}`}</p><h2 className="mt-1 font-semibold">{kosha.name}</h2><span className="mt-3 inline-block text-sm text-primary">فتح الحساب ←</span></Link>)}</div>}
  </div>;

  if (financeQuery.isLoading) return <div dir="rtl" className="space-y-4"><Skeleton className="h-20 rounded-xl" /><Skeleton className="h-64 rounded-xl" /></div>;
  if (financeQuery.isError || !financeQuery.data) return <div dir="rtl" className="space-y-4"><Link href="/admin/kosha-finance"><Button variant="outline" size="sm"><ArrowRight className="ml-2 h-4 w-4" /> رجوع</Button></Link><p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 p-4 text-sm text-destructive">تعذر تحميل الحساب المالي لهذه الكوشة. أعد المحاولة أو تحقق من صلاحية الحسابات.</p></div>;
  const data = financeQuery.data;
  const metrics: Array<[string, number, string]> = [
    ["إجمالي الاستثمار", data.summary.lifetimeInvestment, "تراكمي منذ تسجيل الروابط المالية"],
    ["إيراد الحجوزات", data.summary.bookingRevenue, "حجوزات مناسبات الفترة المحددة"],
    ["المتحصل من العملاء", data.summary.collectedRevenue, "صافي الحركات المالية المعتمدة للحجوزات"],
    ["المتبقي على العملاء", data.summary.customerRemaining, "الرصيد الحالي لحجوزات الفترة"],
    ["المتبقي للموردين", data.summary.supplierPayable, "من الفواتير المرتبطة بعد الحركات المعتمدة"],
    ["تكاليف الحجز", data.summary.bookingCosts, "بنود معتمدة ومصنفة للفترة"],
    ["تشغيل الكوشة", data.summary.operatingCosts, "بنود معتمدة ومصنفة للفترة"],
    ["ربح الحجوزات", data.summary.bookingProfit, "الإيراد ناقص تكاليف الحجز المباشرة"],
    ["المسترد من الاستثمار", data.summary.recoveredInvestment, "تراكمي بعد التكاليف التشغيلية والمباشرة"],
    ["باقي استرداد الاستثمار", data.summary.remainingInvestment, `${data.summary.recoveryPercent}% مسترد`],
  ];
  return <div dir="rtl" className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-center gap-3"><Link href="/admin/kosha-finance"><Button variant="outline" size="icon" aria-label="رجوع"><ArrowRight className="h-4 w-4" /></Button></Link><div><p className="text-xs font-medium text-primary">{data.kosha.financialCode ?? `KOSHA-${data.kosha.id}`}</p><h1 className="text-2xl font-bold">{data.kosha.name} · حساب الكوشة</h1></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" disabled={passportQrMutation.isPending} onClick={() => passportQrMutation.mutate()}><QrCode className="ml-2 h-4 w-4" /> {passportQrMutation.isPending ? "جارٍ إنشاء الرمز" : "جواز وQR"}</Button><Button variant="outline" size="sm" onClick={() => window.print()}><Printer className="ml-2 h-4 w-4" /> طباعة</Button><Button variant="outline" size="sm" onClick={() => downloadStatement(data.statement, data.kosha.financialCode ?? `kosha-${id}`)}><Download className="ml-2 h-4 w-4" /> Excel / CSV</Button></div></div>
    {passportQr && <div className="flex flex-wrap items-center gap-4 rounded-xl border bg-card p-3"><img src={passportQr.dataUrl} alt={`QR ${data.kosha.name}`} className="h-28 w-28 rounded-md border bg-white p-1" /><div className="min-w-0"><p className="font-semibold">جواز الكوشة</p><p className="text-xs text-muted-foreground">يمسح الموظف الرمز ثم يسجل الدخول لعرض بيانات التشغيل.</p><a className="text-xs text-primary underline" href={passportQr.targetUrl} target="_blank" rel="noreferrer">فتح عرض الموظف</a></div></div>}
    <div className="flex flex-wrap items-end gap-3 rounded-xl border bg-card p-3"><label className="grid gap-1 text-xs text-muted-foreground">من<input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="rounded-md border bg-background px-3 py-2 text-sm text-foreground" /></label><label className="grid gap-1 text-xs text-muted-foreground">إلى<input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="rounded-md border bg-background px-3 py-2 text-sm text-foreground" /></label><p className="pb-2 text-xs text-muted-foreground">نتائج التشغيل حسب تاريخ المناسبة وتاريخ تسجيل التكلفة؛ الاستثمار تراكمي.</p></div>
    <nav aria-label="تبويبات حساب الكوشة" className="flex gap-2 overflow-x-auto border-b pb-2">{tabs.map(([key, label]) => <button key={key} onClick={() => setTab(key)} className={`shrink-0 rounded-lg px-3 py-2 text-sm ${tab === key ? "bg-primary text-primary-foreground" : "border bg-card text-muted-foreground hover:text-foreground"}`}>{label}</button>)}</nav>
    {tab === "overview" ? <>
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, note]) => <div key={label} className="rounded-xl border bg-card p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-xl font-bold tabular-nums">{formatCurrency(value)}</p><p className="mt-1 text-xs text-muted-foreground">{note}</p></div>)}</div>
      <div className="grid gap-3 sm:grid-cols-3"><Stat label="حجوزات الفترة" value={data.summary.bookingCount.toLocaleString("ar-IQ")} /><Stat label="حجوزات قادمة" value={data.summary.upcomingBookingCount.toLocaleString("ar-IQ")} /><Stat label="مواد/مشتريات مرتبطة" value={data.statement.filter((row) => row.sourceType === "purchase_invoice_item").length.toLocaleString("ar-IQ")} /></div>
      <PreparationPanel rows={data.operations.upcomingPreparations} />
      {(data.operations.maintenanceRecords.some((row) => !!row.nextMaintenanceDate && row.nextMaintenanceDate <= new Date().toISOString().slice(0, 10)) || data.operations.damageReports.some((row) => row.status !== "resolved")) && <section className="rounded-xl border border-status-warning/40 bg-status-warning/5 p-4"><h2 className="font-semibold">تنبيهات المتابعة</h2><div className="mt-2 space-y-1 text-sm">{data.operations.maintenanceRecords.filter((row) => !!row.nextMaintenanceDate && row.nextMaintenanceDate <= new Date().toISOString().slice(0, 10)).map((row) => <p key={`maintenance-${row.id}`}>موعد صيانة مستحق: {row.maintenanceType} ({row.nextMaintenanceDate})</p>)}{data.operations.damageReports.filter((row) => row.status !== "resolved").map((row) => <p key={`damage-${row.id}`}>بلاغ تلف/فقدان مفتوح: {row.description} · {row.status}</p>)}</div></section>}
      <Statement rows={data.statement.slice(0, 10)} />
    </> : tab === "bookings" ? <div className="rounded-xl border bg-card p-4"><h2 className="mb-3 font-semibold">حجوزات الفترة</h2>{data.bookings.length ? <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead><tr className="border-b text-right text-muted-foreground">{["الحجز", "العميل", "تاريخ المناسبة", "قيمة الحجز", "المتحصل الحالي", "المتبقي"].map((h) => <th key={h} className="p-2">{h}</th>)}</tr></thead><tbody>{data.bookings.map((row) => <tr key={row.id} className="border-b last:border-0"><td className="p-2">{row.trackingCode ?? `KB-${row.id}`}</td><td className="p-2">{row.customerName}</td><td className="p-2">{row.eventDate}</td><td className="p-2">{formatCurrency(row.totalAmount)}</td><td className="p-2">{formatCurrency(row.collectedCurrent)}</td><td className="p-2">{formatCurrency(row.remainingCurrent)}</td></tr>)}</tbody></table></div> : <EmptyState message="لا توجد حجوزات في هذه الفترة" />}</div> : <OperationalTab key={tab} mode={tab} data={data} products={productsQuery.data ?? []} saving={saveOperation.isPending} save={(path, payload, method) => saveOperation.mutate({ path, payload, method })} />}
  </div>;
}

function Stat({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-lg font-bold">{value}</p></div>; }

function PreparationPanel({ rows }: { rows: FinanceResponse["operations"]["upcomingPreparations"] }) {
  return <section className="rounded-xl border bg-card p-4"><h2 className="mb-3 font-semibold">تجهيز الحجوزات القادمة</h2>{rows.length ? <div className="space-y-2">{rows.map((row) => <article key={row.bookingId} className="rounded-lg border p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><b>{row.bookingNo} · {row.customerName}</b><p className="text-xs text-muted-foreground">موعد المناسبة: {row.eventDate}</p></div>{row.workOrderId ? <Link className="rounded-md border px-3 py-2 text-xs font-semibold text-primary" href={`/staff/koshas/work-orders/${row.workOrderId}`}>فتح أمر التجهيز</Link> : <Link className="rounded-md border px-3 py-2 text-xs font-semibold text-primary" href={`/admin/koshat-tasks?bookingId=${row.bookingId}`}>إنشاء طلب تجهيز</Link>}</div>{row.workOrderId ? <><p className="mt-2 text-sm">قائمة الفحص: {row.checklistComplete} من {row.checklistTotal} مكتمل</p>{row.missingChecklist.length > 0 && <p className="mt-1 text-xs text-status-warning">قائمة غير مكتملة: {row.missingChecklist.join("، ")}</p>}{row.assignedAssets.length > 0 && <p className="mt-1 text-xs text-muted-foreground">الأصول المسندة: {row.assignedAssets.map((asset) => `${asset.name} (${asset.checkedOut ? "خرج" : asset.returned ? "عاد" : "مسند"})`).join("، ")}</p>}</> : <p className="mt-2 text-xs text-muted-foreground">يفتح نموذج إنشاء أمر العمل الحالي؛ اختر الفريق لإكمال الإسناد.</p>}</article>)}</div> : <EmptyState message="لا توجد حجوزات قادمة لهذه الكوشة" />}</section>;
}

function OperationalTab({ mode, data, products, saving, save }: { mode: string; data: FinanceResponse; products: Array<{ id: number; name: string; nameAr?: string; barcode?: string | null }>; saving: boolean; save: (path: string, payload: Record<string, unknown>, method?: string) => void }) {
  const base = `/admin/kosha-finance/${data.kosha.id}`;
  const input = "w-full rounded-md border bg-background px-3 py-2 text-sm";
  const [project, setProject] = useState({ plannedBudget: "", expectedCompletionDate: "", notes: "" });
  const [asset, setAsset] = useState({ productId: "", quantity: "1", shared: false, storageLocation: "" });
  const [maintenance, setMaintenance] = useState({ maintenanceType: "maintenance", maintenanceDate: new Date().toISOString().slice(0, 10), description: "", nextMaintenanceDate: "", expenseId: "" });
  const [damage, setDamage] = useState({ incidentType: "damage", reason: "", description: "", bookingId: "", estimatedRepairCost: "", estimatedReplacementCost: "" });
  const labels: Record<string, string> = { draft: "مسودة", materials_required: "المواد المطلوبة", purchasing: "جاري الشراء", materials_received: "تم استلام المواد", assembly: "جاري التركيب", inspection: "الفحص", ready: "جاهزة للحجز" };
  if (mode === "materials") return <div className="space-y-4"><section className="rounded-xl border bg-card p-4"><h2 className="mb-3 font-semibold">المواد المسندة للمخزن والكوشة</h2>{data.operations.assetAssignments.length ? <div className="divide-y rounded-lg border">{data.operations.assetAssignments.map((row) => <div key={row.id} className="p-3 text-sm">{products.find((product) => product.id === row.productId)?.nameAr || products.find((product) => product.id === row.productId)?.name || `منتج #${row.productId}`} · {row.quantity} {row.shared ? "· مشترك" : "· مخصص"} · {row.storageLocation || "بدون موقع"}</div>)}</div> : <EmptyState message="لا توجد مواد مسندة" />}</section><section className="rounded-xl border bg-card p-4"><h2 className="mb-3 font-semibold">المشتريات المسجلة</h2><Statement rows={data.statement.filter((row) => row.sourceType === "purchase_invoice_item")} /></section></div>;
  if (mode === "purchases") return <section className="rounded-xl border bg-card p-4"><h2 className="mb-3 font-semibold">بنود الشراء</h2><Statement rows={data.statement.filter((row) => row.sourceType === "purchase_invoice_item")} /></section>;
  if (mode === "assets") return <section className="space-y-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">الأصول والمواد المسندة</h2><form className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5" onSubmit={(event) => { event.preventDefault(); save(`${base}/assets`, asset); setAsset({ productId: "", quantity: "1", shared: false, storageLocation: "" }); }}><select required className={input} value={asset.productId} onChange={(e) => setAsset({ ...asset, productId: e.target.value })}><option value="">اختر منتج المخزن</option>{products.map((product) => <option key={product.id} value={product.id}>{product.nameAr || product.name}{product.barcode ? ` · ${product.barcode}` : ""}</option>)}</select><input required type="number" min="0.001" step="0.001" value={asset.quantity} onChange={(e) => setAsset({ ...asset, quantity: e.target.value })} className={input} aria-label="الكمية" /><input value={asset.storageLocation} onChange={(e) => setAsset({ ...asset, storageLocation: e.target.value })} className={input} placeholder="موقع التخزين" /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={asset.shared} onChange={(e) => setAsset({ ...asset, shared: e.target.checked })} /> أصل مشترك</label><Button disabled={saving}>إسناد</Button></form>{data.operations.assetAssignments.length ? <div className="divide-y rounded-lg border">{data.operations.assetAssignments.map((row) => <div key={row.id} className="flex flex-wrap items-center justify-between gap-2 p-3 text-sm"><span>{products.find((product) => product.id === row.productId)?.nameAr || products.find((product) => product.id === row.productId)?.name || `منتج #${row.productId}`} · {row.quantity} · {row.shared ? "مشترك" : "مخصص"}</span><span className="text-muted-foreground">{row.storageLocation || "بدون موقع"}</span><Button type="button" size="sm" variant="outline" disabled={saving} onClick={() => save(`${base}/assets/${row.id}`, {}, "DELETE")}>إنهاء الإسناد</Button></div>)}</div> : <EmptyState message="لا توجد أصول مسندة بعد" />}</section>;
  if (mode === "maintenance") return <section className="space-y-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">سجل الصيانة</h2><p className="text-xs text-muted-foreground">اربط المصروف المعتمد من تبويب المصاريف؛ المبلغ يبقى في سجل AJN المالي ولا يُكرر هنا.</p><form className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3" onSubmit={(event) => { event.preventDefault(); save(`${base}/maintenance`, maintenance); setMaintenance({ maintenanceType: "maintenance", maintenanceDate: new Date().toISOString().slice(0, 10), description: "", nextMaintenanceDate: "", expenseId: "" }); }}><select className={input} value={maintenance.maintenanceType} onChange={(e) => setMaintenance({ ...maintenance, maintenanceType: e.target.value })}><option value="maintenance">صيانة عامة</option><option value="repair">إصلاح</option><option value="cleaning">تنظيف</option><option value="painting">صبغ</option><option value="electrical">كهرباء</option></select><input required type="date" className={input} value={maintenance.maintenanceDate} onChange={(e) => setMaintenance({ ...maintenance, maintenanceDate: e.target.value })} /><input required className={input} placeholder="وصف العمل" value={maintenance.description} onChange={(e) => setMaintenance({ ...maintenance, description: e.target.value })} /><input type="date" className={input} aria-label="موعد الصيانة القادمة" value={maintenance.nextMaintenanceDate} onChange={(e) => setMaintenance({ ...maintenance, nextMaintenanceDate: e.target.value })} /><input type="number" min="1" className={input} placeholder="معرف مصروف معتمد (اختياري)" value={maintenance.expenseId} onChange={(e) => setMaintenance({ ...maintenance, expenseId: e.target.value })} /><Button disabled={saving}>إضافة سجل صيانة</Button></form>{data.operations.maintenanceRecords.length ? <div className="divide-y rounded-lg border">{data.operations.maintenanceRecords.map((row) => <div key={row.id} className="p-3 text-sm"><div className="flex justify-between gap-2"><b>{row.maintenanceType} · {row.maintenanceDate}</b><span className="text-muted-foreground">مصروف #{row.expenseId ?? "—"}</span></div><p className="mt-1">{row.description}</p>{row.nextMaintenanceDate ? <p className="text-xs text-muted-foreground">الصيانة القادمة: {row.nextMaintenanceDate}</p> : null}</div>)}</div> : <EmptyState message="لا توجد سجلات صيانة" />}</section>;
  if (mode === "damage") return <section className="space-y-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">التلف والفقدان</h2><form className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3" onSubmit={(event) => { event.preventDefault(); save(`${base}/damage`, damage); setDamage({ incidentType: "damage", reason: "", description: "", bookingId: "", estimatedRepairCost: "", estimatedReplacementCost: "" }); }}><select className={input} value={damage.incidentType} onChange={(e) => setDamage({ ...damage, incidentType: e.target.value })}><option value="damage">تلف</option><option value="missing">مفقود</option><option value="loss">فقدان</option></select><input required className={input} placeholder="السبب" value={damage.reason} onChange={(e) => setDamage({ ...damage, reason: e.target.value })} /><input required className={input} minLength={5} placeholder="وصف الحالة" value={damage.description} onChange={(e) => setDamage({ ...damage, description: e.target.value })} /><input type="number" min="0" className={input} placeholder="تقدير الإصلاح" value={damage.estimatedRepairCost} onChange={(e) => setDamage({ ...damage, estimatedRepairCost: e.target.value })} /><input type="number" min="0" className={input} placeholder="تقدير الاستبدال" value={damage.estimatedReplacementCost} onChange={(e) => setDamage({ ...damage, estimatedReplacementCost: e.target.value })} /><input required type="number" min="1" className={input} placeholder="رقم الحجز (مطلوب)" value={damage.bookingId} onChange={(e) => setDamage({ ...damage, bookingId: e.target.value })} /><Button disabled={saving}>تسجيل البلاغ</Button></form>{data.operations.damageReports.length ? <div className="divide-y rounded-lg border">{data.operations.damageReports.map((row) => <div key={row.id} className="flex flex-wrap items-center justify-between gap-3 p-3 text-sm"><div><b>{row.incidentType} · {row.status}</b><p>{row.description}</p><p className="text-xs text-muted-foreground">{row.reason}{row.bookingId ? ` · حجز #${row.bookingId}` : ""}</p></div><select className="rounded border bg-background px-2 py-1" aria-label="حالة البلاغ" value={row.status} onChange={(e) => save(`${base}/damage/${row.id}`, { status: e.target.value }, "PATCH")}><option value="reported">مسجل</option><option value="under_review">قيد المراجعة</option><option value="repairing">قيد الإصلاح</option><option value="replaced">تم الاستبدال</option><option value="resolved">تم الحل</option></select></div>)}</div> : <EmptyState message="لا توجد بلاغات تلف أو فقدان" />}</section>;
  if (mode === "investment") return <section className="space-y-4 rounded-xl border bg-card p-4"><h2 className="font-semibold">أوامر إنشاء الكوشة</h2><p className="text-xs text-muted-foreground">تُحسب الكلفة الفعلية من بنود الاستثمار المرتبطة صراحةً برقم أمر الإنشاء. السجلات السابقة غير المرتبطة لا تُنسب تلقائياً.</p><form className="grid gap-2 sm:grid-cols-2 lg:grid-cols-4" onSubmit={(event) => { event.preventDefault(); save(`${base}/projects`, project); setProject({ plannedBudget: "", expectedCompletionDate: "", notes: "" }); }}><input required type="number" min="0" className={input} placeholder="الميزانية المخططة" value={project.plannedBudget} onChange={(e) => setProject({ ...project, plannedBudget: e.target.value })} /><input type="date" className={input} aria-label="تاريخ الإنجاز المتوقع" value={project.expectedCompletionDate} onChange={(e) => setProject({ ...project, expectedCompletionDate: e.target.value })} /><input className={input} placeholder="ملاحظات" value={project.notes} onChange={(e) => setProject({ ...project, notes: e.target.value })} /><Button disabled={saving}>إنشاء أمر</Button></form>{data.operations.projects.length ? <div className="divide-y rounded-lg border">{data.operations.projects.map((row) => <div key={row.id} className="grid gap-2 p-3 text-sm sm:grid-cols-2"><b>أمر #{row.id}</b><span>{labels[row.stage] ?? row.stage}</span><span>الميزانية: {formatCurrency(row.plannedBudget)}</span><span>الفعلي المرتبط: {formatCurrency(row.actualCost)}</span><span>المتبقي: {formatCurrency(row.remainingBudget)}</span>{row.budgetVariance > 0 && <span className="font-semibold text-destructive">تجاوز الميزانية: {formatCurrency(row.budgetVariance)}</span>}<select aria-label="مرحلة أمر الإنشاء" value={row.stage} onChange={(e) => save(`${base}/projects/${row.id}`, { stage: e.target.value }, "PATCH")} className="rounded border bg-background px-2 py-1 sm:col-span-2">{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div>)}</div> : <EmptyState message="لا توجد أوامر إنشاء مسجلة" />}</section>;
  if (mode === "timeline") return <section className="divide-y rounded-xl border bg-card">{data.operations.timeline.length ? data.operations.timeline.map((row) => <article key={row.id} className="p-4"><div className="flex flex-wrap justify-between gap-2"><b>{row.action}</b><span className="text-xs text-muted-foreground">{row.createdAt}</span></div><p className="mt-1 text-sm text-muted-foreground">بواسطة {row.userName || "مستخدم النظام"}</p></article>) : <EmptyState message="لا توجد أحداث مسجلة للكوشة بعد" />}</section>;
  if (mode === "booking-costs" || mode === "expenses" || mode === "account") return <Statement rows={mode === "expenses" ? data.statement.filter((row) => row.sourceType === "expense") : mode === "booking-costs" ? data.statement.filter((row) => row.category === "booking") : data.statement} />;
  return <EmptyState message="لا توجد سجلات مطابقة" />;
}
function Statement({ rows }: { rows: FinanceResponse["statement"] }) {
  if (!rows.length) return <div className="rounded-xl border bg-card p-4"><EmptyState message="لا توجد حركات ضمن الاختيار الحالي" /></div>;
  return <div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b bg-muted/30 text-right text-muted-foreground">{["التاريخ", "البيان", "التصنيف", "المرجع", "الحجز", "المورد", "المبلغ", "الأثر"].map((h) => <th key={h} className="px-3 py-2.5">{h}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row.sourceKey} className="border-b last:border-0"><td className="px-3 py-2.5">{row.date}</td><td className="px-3 py-2.5">{row.description}</td><td className="px-3 py-2.5">{row.category ?? "—"}</td><td className="px-3 py-2.5">{row.reference}</td><td className="px-3 py-2.5">{row.bookingId ?? "—"}</td><td className="px-3 py-2.5">{row.supplierName || "—"}</td><td className="px-3 py-2.5 font-semibold">{formatCurrency(row.amount)}</td><td className="px-3 py-2.5">{row.impact === "credit" ? "إيراد" : "مصروف"}</td></tr>)}</tbody></table></div>;
}
