import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Landmark, Pencil, Plus, Printer, Trash2, Wallet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import { adminFetch, apiErrorMessage, formatCurrency } from "./_lib";

type Repayment = { id: number; repaymentNo: string; paymentDate: string; amount: number; paymentMethod: string; referenceNo?: string | null; notes?: string | null; status: string };
type Loan = { id: number; loanNo: string; lenderName: string; lenderPhone?: string | null; originalAmount: number; totalRepaid: number; remainingAmount: number; receivedDate: string; paymentMethod: string; referenceNo?: string | null; notes?: string | null; status: string; repayments: Repayment[] };
type LoansResponse = { loans: Loan[] };
type LoanForm = { lenderName: string; lenderPhone: string; amount: string; receivedDate: string; paymentMethod: string; referenceNo: string; notes: string };
type RepaymentForm = Omit<LoanForm, "lenderName" | "lenderPhone" | "receivedDate"> & { paymentDate: string };

const today = () => new Date().toISOString().slice(0, 10);
const blankLoanForm = (): LoanForm => ({ lenderName: "", lenderPhone: "", amount: "", receivedDate: today(), paymentMethod: "cash", referenceNo: "", notes: "" });
const blankRepaymentForm = (): RepaymentForm => ({ amount: "", paymentDate: today(), paymentMethod: "cash", referenceNo: "", notes: "" });
const statusLabel: Record<string, string> = { pending: "بانتظار الموافقة", active: "نشط", partially_repaid: "مسدد جزئياً", fully_repaid: "مسدد بالكامل", rejected: "مرفوض", cancelled: "ملغي", executed: "منفذ" };
const paymentMethodLabel: Record<string, string> = { cash: "نقد", transfer: "تحويل", card: "بطاقة", pos: "نقطة بيع", other: "أخرى" };

function escapeHtml(value: unknown) {
  return String(value ?? "").replace(/[&<>'\"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char] ?? char));
}

function printLoan(loan: Loan) {
  const popup = window.open("", "_blank", "noopener,noreferrer");
  if (!popup) return;
  const row = (label: string, value: unknown) => `<div class="row"><span>${escapeHtml(label)}</span><strong>${escapeHtml(value || "—")}</strong></div>`;
  const repayments = loan.repayments.length
    ? loan.repayments.map((repayment) => `<tr><td>${escapeHtml(repayment.repaymentNo)}</td><td>${escapeHtml(repayment.paymentDate)}</td><td>${escapeHtml(formatCurrency(repayment.amount))}</td><td>${escapeHtml(statusLabel[repayment.status] ?? repayment.status)}</td></tr>`).join("")
    : '<tr><td colspan="4">لا توجد دفعات سداد مسجلة</td></tr>';
  popup.document.write(`<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8" /><title>كشف قرض ${escapeHtml(loan.loanNo)}</title><style>body{font-family:Tahoma,Arial,sans-serif;color:#172033;margin:34px;background:#fff}h1{margin:0 0 6px;font-size:24px}.sub{color:#667085;margin-bottom:24px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.row{border:1px solid #e5e7eb;border-radius:8px;padding:11px;display:flex;justify-content:space-between;gap:16px}.row span{color:#667085}table{width:100%;border-collapse:collapse;margin-top:24px}th,td{padding:10px;border:1px solid #e5e7eb;text-align:right}th{background:#f8fafc}.note{margin-top:18px;border:1px solid #e5e7eb;border-radius:8px;padding:12px;white-space:pre-wrap}.footer{margin-top:28px;color:#667085;font-size:12px}@media print{body{margin:12mm}}</style></head><body><h1>كشف قرض وتمويل</h1><div class="sub">مجموعة علي جان نهاد • ${escapeHtml(loan.loanNo)}</div><section class="grid">${row("اسم المقرض", loan.lenderName)}${row("رقم الهاتف", loan.lenderPhone)}${row("تاريخ الاستلام", loan.receivedDate)}${row("طريقة الدفع", paymentMethodLabel[loan.paymentMethod] ?? loan.paymentMethod)}${row("المبلغ الأصلي", formatCurrency(loan.originalAmount))}${row("إجمالي المسدد", formatCurrency(loan.totalRepaid))}${row("الالتزام المتبقي", formatCurrency(loan.remainingAmount))}${row("الحالة", statusLabel[loan.status] ?? loan.status)}${row("رقم المرجع", loan.referenceNo)}</section><div class="note"><strong>الملاحظات</strong><br />${escapeHtml(loan.notes || "لا توجد ملاحظات")}</div><h2>سجل السداد</h2><table><thead><tr><th>رقم السداد</th><th>التاريخ</th><th>المبلغ</th><th>الحالة</th></tr></thead><tbody>${repayments}</tbody></table><div class="footer">تمت الطباعة في ${escapeHtml(new Date().toLocaleString("ar-IQ"))}</div></body></html>`);
  popup.document.close();
  popup.focus();
  window.setTimeout(() => popup.print(), 150);
}

export function CompanyLoansPanel({ embedded = false }: { embedded?: boolean }) {
  const qc = useQueryClient();
  const { toast } = useToast();
  const [open, setOpen] = useState(false);
  const [editLoan, setEditLoan] = useState<Loan | null>(null);
  const [repayLoan, setRepayLoan] = useState<Loan | null>(null);
  const [form, setForm] = useState<LoanForm>(blankLoanForm);
  const [repayment, setRepayment] = useState<RepaymentForm>(blankRepaymentForm);
  const query = useQuery({ queryKey: ["company-loans"], queryFn: () => adminFetch<LoansResponse>("/admin/loans") });
  const refresh = () => qc.invalidateQueries({ queryKey: ["company-loans"] });
  const payload = () => ({ ...form, amount: Number(form.amount), lenderPhone: form.lenderPhone || null, referenceNo: form.referenceNo || null, notes: form.notes || null });
  const create = useMutation({ mutationFn: () => adminFetch("/admin/loans", { method: "POST", body: JSON.stringify(payload()) }), onSuccess: () => { refresh(); setOpen(false); setForm(blankLoanForm()); toast({ title: "تم إرسال استلام القرض للموافقات المالية" }); }, onError: (error) => toast({ title: apiErrorMessage(error), variant: "destructive" }) });
  const update = useMutation({ mutationFn: () => adminFetch(`/admin/loans/${editLoan!.id}`, { method: "PUT", body: JSON.stringify(payload()) }), onSuccess: () => { refresh(); setEditLoan(null); setForm(blankLoanForm()); toast({ title: "تم تعديل طلب القرض والموافقة المالية المرتبطة" }); }, onError: (error) => toast({ title: apiErrorMessage(error), variant: "destructive" }) });
  const cancel = useMutation({ mutationFn: ({ id, reason }: { id: number; reason: string }) => adminFetch(`/admin/loans/${id}`, { method: "DELETE", body: JSON.stringify({ reason }) }), onSuccess: () => { refresh(); toast({ title: "تم إلغاء طلب القرض وحفظ سجله للمراجعة" }); }, onError: (error) => toast({ title: apiErrorMessage(error), variant: "destructive" }) });
  const repay = useMutation({ mutationFn: () => adminFetch(`/admin/loans/${repayLoan!.id}/repayments`, { method: "POST", body: JSON.stringify({ ...repayment, amount: Number(repayment.amount), referenceNo: repayment.referenceNo || null, notes: repayment.notes || null }) }), onSuccess: () => { refresh(); setRepayLoan(null); setRepayment(blankRepaymentForm()); toast({ title: "تم إرسال سداد القرض للموافقات المالية" }); }, onError: (error) => toast({ title: apiErrorMessage(error), variant: "destructive" }) });
  const totals = useMemo(() => (query.data?.loans ?? []).reduce((acc, loan) => ({ original: acc.original + loan.originalAmount, repaid: acc.repaid + loan.totalRepaid, remaining: acc.remaining + loan.remainingAmount }), { original: 0, repaid: 0, remaining: 0 }), [query.data]);
  const startEdit = (loan: Loan) => { setEditLoan(loan); setForm({ lenderName: loan.lenderName, lenderPhone: loan.lenderPhone ?? "", amount: String(loan.originalAmount), receivedDate: loan.receivedDate, paymentMethod: loan.paymentMethod, referenceNo: loan.referenceNo ?? "", notes: loan.notes ?? "" }); };
  const startCancel = (loan: Loan) => { const reason = window.prompt(`سبب إلغاء طلب القرض ${loan.loanNo}:`); if (reason?.trim()) cancel.mutate({ id: loan.id, reason: reason.trim() }); };

  return <div className="space-y-5" dir="rtl">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-primary/15 text-primary"><Landmark className="h-5 w-5" /></span><div>{embedded ? <h2 className="text-xl font-bold">القروض والتمويل</h2> : <h1 className="text-2xl font-bold">القروض والتمويل</h1>}<p className="text-sm text-muted-foreground">التزامات الشركة؛ لا تُسجّل إيراداً أو مصروفاً تشغيلياً.</p></div></div><Button onClick={() => { setForm(blankLoanForm()); setOpen(true); }}><Plus className="ms-1 h-4 w-4" />استلام قرض</Button></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric title="القروض" value={String(query.data?.loans.length ?? 0)} /><Metric title="إجمالي الاقتراض" value={formatCurrency(totals.original)} /><Metric title="إجمالي المسدد" value={formatCurrency(totals.repaid)} /><Metric title="الالتزام المتبقي" value={formatCurrency(totals.remaining)} /></div>
    <section className="overflow-x-auto rounded-xl border border-border/50 bg-card p-4"><p className="mb-3 text-xs text-muted-foreground">يمكن تعديل أو إلغاء طلب القرض قبل اعتماده فقط؛ الإلغاء يحفظ السجل ويرفض طلبه المالي، ولا يحذف أي حركة حسابية.</p>{query.isError ? <p className="py-12 text-center text-sm text-destructive">{apiErrorMessage(query.error)}</p> : <><table className="w-full min-w-[860px] text-right text-sm"><thead className="border-b text-xs text-muted-foreground"><tr><th className="p-2">القرض / المقرض</th><th className="p-2">التاريخ</th><th className="p-2">الأصلي</th><th className="p-2">المسدد</th><th className="p-2">المتبقي</th><th className="p-2">الحالة</th><th className="p-2">إجراء</th></tr></thead><tbody>{query.data?.loans.map((loan) => <tr key={loan.id} className="border-b border-border/50"><td className="p-2"><b>{loan.lenderName}</b><div className="text-xs text-muted-foreground">{loan.loanNo}</div></td><td className="p-2">{loan.receivedDate}</td><td className="p-2">{formatCurrency(loan.originalAmount)}</td><td className="p-2 text-emerald-600">{formatCurrency(loan.totalRepaid)}</td><td className="p-2 font-bold">{formatCurrency(loan.remainingAmount)}</td><td className="p-2"><span className="rounded-full bg-muted px-2 py-1 text-xs">{statusLabel[loan.status] ?? loan.status}</span></td><td className="p-2"><div className="flex flex-wrap gap-1"><Button size="sm" variant="outline" onClick={() => printLoan(loan)}><Printer className="ms-1 h-3.5 w-3.5" />طباعة</Button>{loan.status === "pending" && <><Button size="sm" variant="outline" onClick={() => startEdit(loan)}><Pencil className="ms-1 h-3.5 w-3.5" />تعديل</Button><Button size="sm" variant="destructive" onClick={() => startCancel(loan)} disabled={cancel.isPending}><Trash2 className="ms-1 h-3.5 w-3.5" />إلغاء</Button></>}{loan.remainingAmount > 0 && loan.status !== "pending" && loan.status !== "cancelled" && loan.status !== "rejected" && <Button size="sm" variant="outline" onClick={() => { setRepayLoan(loan); setRepayment({ amount: String(loan.remainingAmount), paymentDate: today(), paymentMethod: "cash", referenceNo: "", notes: "" }); }}><Wallet className="ms-1 h-3.5 w-3.5" />سداد</Button>}</div></td></tr>)}</tbody></table>{!query.isLoading && !query.data?.loans.length && <p className="py-12 text-center text-sm text-muted-foreground">لا توجد قروض مسجلة حالياً.</p>}</>}</section>
    <LoanDialog open={open} title="استلام قرض جديد" submit="إرسال للموافقات المالية" busy={create.isPending} form={form} setForm={setForm} onClose={() => setOpen(false)} onSubmit={() => create.mutate()} />
    <LoanDialog open={!!editLoan} title={editLoan ? `تعديل قرض ${editLoan.loanNo}` : ""} submit="حفظ التعديل" busy={update.isPending} form={form} setForm={setForm} onClose={() => { setEditLoan(null); setForm(blankLoanForm()); }} onSubmit={() => update.mutate()} />
    <LoanDialog open={!!repayLoan} title={repayLoan ? `سداد قرض ${repayLoan.loanNo}` : ""} submit="إرسال السداد للموافقات" busy={repay.isPending} form={repayment} setForm={setRepayment} onClose={() => setRepayLoan(null)} onSubmit={() => repay.mutate()} repayment />
  </div>;
}

function Metric({ title, value }: { title: string; value: string }) { return <div className="rounded-xl border border-border/50 bg-card p-3"><div className="text-xs text-muted-foreground">{title}</div><div className="mt-1 text-lg font-bold">{value}</div></div>; }
function LoanDialog({ open, title, submit, busy, form, setForm, onClose, onSubmit, repayment = false }: { open: boolean; title: string; submit: string; busy: boolean; form: LoanForm | RepaymentForm; setForm: (form: any) => void; onClose: () => void; onSubmit: () => void; repayment?: boolean }) { const set = (key: string, value: string) => setForm({ ...form, [key]: value }); return <Dialog open={open} onOpenChange={(value) => !value && onClose()}><DialogContent dir="rtl"><DialogHeader><DialogTitle>{title}</DialogTitle></DialogHeader><form className="grid gap-3 md:grid-cols-2" onSubmit={(event) => { event.preventDefault(); onSubmit(); }}>{!repayment && <><Field label="اسم المقرض" value={(form as LoanForm).lenderName} onChange={(value) => set("lenderName", value)} required /><Field label="رقم الهاتف" value={(form as LoanForm).lenderPhone} onChange={(value) => set("lenderPhone", value)} /></>}<Field label="المبلغ (IQD)" type="number" value={form.amount} onChange={(value) => set("amount", value)} required /><Field label={repayment ? "تاريخ السداد" : "تاريخ الاستلام"} type="date" value={repayment ? (form as RepaymentForm).paymentDate : (form as LoanForm).receivedDate} onChange={(value) => set(repayment ? "paymentDate" : "receivedDate", value)} required /><label className="grid gap-1 text-sm"><span>طريقة الدفع</span><select value={form.paymentMethod} onChange={(event) => set("paymentMethod", event.target.value)} className="rounded-lg border bg-background px-3 py-2"><option value="cash">نقد</option><option value="transfer">تحويل</option><option value="card">بطاقة</option><option value="pos">نقطة بيع</option><option value="other">أخرى</option></select></label><Field label="رقم المرجع" value={form.referenceNo} onChange={(value) => set("referenceNo", value)} /><label className="grid gap-1 text-sm md:col-span-2"><span>ملاحظات</span><textarea value={form.notes} onChange={(event) => set("notes", event.target.value)} className="min-h-20 rounded-lg border bg-background p-3" /></label><Button type="submit" className="md:col-span-2" disabled={busy}>{busy ? "جارٍ الحفظ…" : submit}</Button></form></DialogContent></Dialog>; }
function Field({ label, value, onChange, type = "text", required = false }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }) { return <label className="grid gap-1 text-sm"><span>{label}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} required={required} className="rounded-lg border bg-background px-3 py-2" /></label>; }

export default function CompanyLoansPage() { return <CompanyLoansPanel />; }
