import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Landmark, Plus, Wallet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import { adminFetch, apiErrorMessage, formatCurrency } from "./_lib";

type Repayment = { id: number; repaymentNo: string; paymentDate: string; amount: number; status: string };
type Loan = { id: number; loanNo: string; lenderName: string; lenderPhone?: string | null; originalAmount: number; totalRepaid: number; remainingAmount: number; receivedDate: string; status: string; repayments: Repayment[] };
type LoansResponse = { loans: Loan[] };
const today = () => new Date().toISOString().slice(0, 10);
const statusLabel: Record<string, string> = { pending: "بانتظار الموافقة", active: "نشط", partially_repaid: "مسدد جزئياً", fully_repaid: "مسدد بالكامل", rejected: "مرفوض", cancelled: "ملغي", executed: "منفذ" };

export default function CompanyLoansPage() {
  const qc = useQueryClient(); const { toast } = useToast();
  const [open, setOpen] = useState(false); const [repayLoan, setRepayLoan] = useState<Loan | null>(null);
  const [form, setForm] = useState({ lenderName: "", lenderPhone: "", amount: "", receivedDate: today(), paymentMethod: "cash", referenceNo: "", notes: "" });
  const [repayment, setRepayment] = useState({ amount: "", paymentDate: today(), paymentMethod: "cash", referenceNo: "", notes: "" });
  const query = useQuery({ queryKey: ["company-loans"], queryFn: () => adminFetch<LoansResponse>("/admin/loans") });
  const refresh = () => qc.invalidateQueries({ queryKey: ["company-loans"] });
  const create = useMutation({ mutationFn: () => adminFetch("/admin/loans", { method: "POST", body: JSON.stringify({ ...form, amount: Number(form.amount), lenderPhone: form.lenderPhone || null, referenceNo: form.referenceNo || null, notes: form.notes || null }) }), onSuccess: () => { refresh(); setOpen(false); setForm({ lenderName: "", lenderPhone: "", amount: "", receivedDate: today(), paymentMethod: "cash", referenceNo: "", notes: "" }); toast({ title: "تم إرسال استلام القرض للموافقات المالية" }); }, onError: (e) => toast({ title: apiErrorMessage(e), variant: "destructive" }) });
  const repay = useMutation({ mutationFn: () => adminFetch(`/admin/loans/${repayLoan!.id}/repayments`, { method: "POST", body: JSON.stringify({ ...repayment, amount: Number(repayment.amount), referenceNo: repayment.referenceNo || null, notes: repayment.notes || null }) }), onSuccess: () => { refresh(); setRepayLoan(null); toast({ title: "تم إرسال سداد القرض للموافقات المالية" }); }, onError: (e) => toast({ title: apiErrorMessage(e), variant: "destructive" }) });
  const totals = useMemo(() => (query.data?.loans ?? []).reduce((a, l) => ({ original: a.original + l.originalAmount, repaid: a.repaid + l.totalRepaid, remaining: a.remaining + l.remainingAmount }), { original: 0, repaid: 0, remaining: 0 }), [query.data]);
  return <div className="space-y-5" dir="rtl">
    <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-primary/15 text-primary"><Landmark className="h-5 w-5" /></span><div><h1 className="text-2xl font-bold">القروض والتمويل</h1><p className="text-sm text-muted-foreground">التزامات الشركة؛ لا تُسجّل إيراداً أو مصروفاً تشغيلياً.</p></div></div><Button onClick={() => setOpen(true)}><Plus className="ms-1 h-4 w-4" />استلام قرض</Button></div>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4"><Metric title="القروض" value={String(query.data?.loans.length ?? 0)} /><Metric title="إجمالي الاقتراض" value={formatCurrency(totals.original)} /><Metric title="إجمالي المسدد" value={formatCurrency(totals.repaid)} /><Metric title="الالتزام المتبقي" value={formatCurrency(totals.remaining)} /></div>
    <section className="overflow-x-auto rounded-xl border border-border/50 bg-card p-4">{query.isError ? <p className="py-12 text-center text-sm text-destructive">{apiErrorMessage(query.error)}</p> : <><table className="w-full min-w-[760px] text-right text-sm"><thead className="border-b text-xs text-muted-foreground"><tr><th className="p-2">القرض / المقرض</th><th className="p-2">التاريخ</th><th className="p-2">الأصلي</th><th className="p-2">المسدد</th><th className="p-2">المتبقي</th><th className="p-2">الحالة</th><th className="p-2">إجراء</th></tr></thead><tbody>{query.data?.loans.map((loan) => <tr key={loan.id} className="border-b border-border/50"><td className="p-2"><b>{loan.lenderName}</b><div className="text-xs text-muted-foreground">{loan.loanNo}</div></td><td className="p-2">{loan.receivedDate}</td><td className="p-2">{formatCurrency(loan.originalAmount)}</td><td className="p-2 text-emerald-600">{formatCurrency(loan.totalRepaid)}</td><td className="p-2 font-bold">{formatCurrency(loan.remainingAmount)}</td><td className="p-2"><span className="rounded-full bg-muted px-2 py-1 text-xs">{statusLabel[loan.status] ?? loan.status}</span></td><td className="p-2">{loan.remainingAmount > 0 && loan.status !== "pending" && <Button size="sm" variant="outline" onClick={() => { setRepayLoan(loan); setRepayment({ amount: String(loan.remainingAmount), paymentDate: today(), paymentMethod: "cash", referenceNo: "", notes: "" }); }}><Wallet className="ms-1 h-3.5 w-3.5" />سداد</Button>}</td></tr>)}</tbody></table>{!query.isLoading && !query.data?.loans.length && <p className="py-12 text-center text-sm text-muted-foreground">لا توجد قروض مسجلة بعد.</p>}</>}</section>
    <LoanDialog open={open} title="استلام قرض جديد" submit="إرسال للموافقات المالية" busy={create.isPending} form={form} setForm={setForm} onClose={() => setOpen(false)} onSubmit={() => create.mutate()} />
    <LoanDialog open={!!repayLoan} title={repayLoan ? `سداد قرض ${repayLoan.loanNo}` : ""} submit="إرسال السداد للموافقات" busy={repay.isPending} form={repayment} setForm={setRepayment} onClose={() => setRepayLoan(null)} onSubmit={() => repay.mutate()} repayment />
  </div>;
}
function Metric({ title, value }: { title: string; value: string }) { return <div className="rounded-xl border border-border/50 bg-card p-3"><div className="text-xs text-muted-foreground">{title}</div><div className="mt-1 text-lg font-bold">{value}</div></div>; }
function LoanDialog({ open, title, submit, busy, form, setForm, onClose, onSubmit, repayment = false }: any) { const set = (key: string, value: string) => setForm({ ...form, [key]: value }); return <Dialog open={open} onOpenChange={(v) => !v && onClose()}><DialogContent dir="rtl"><DialogHeader><DialogTitle>{title}</DialogTitle></DialogHeader><form className="grid gap-3 md:grid-cols-2" onSubmit={(e) => { e.preventDefault(); onSubmit(); }}>{!repayment && <><Field label="اسم المقرض" value={form.lenderName} onChange={(v: string) => set("lenderName", v)} required /><Field label="رقم الهاتف" value={form.lenderPhone} onChange={(v: string) => set("lenderPhone", v)} /></>}<Field label="المبلغ (IQD)" type="number" value={form.amount} onChange={(v: string) => set("amount", v)} required /><Field label={repayment ? "تاريخ السداد" : "تاريخ الاستلام"} type="date" value={repayment ? form.paymentDate : form.receivedDate} onChange={(v: string) => set(repayment ? "paymentDate" : "receivedDate", v)} required /><label className="grid gap-1 text-sm"><span>طريقة الدفع</span><select value={form.paymentMethod} onChange={(e) => set("paymentMethod", e.target.value)} className="rounded-lg border bg-background px-3 py-2"><option value="cash">نقد</option><option value="transfer">تحويل</option><option value="card">بطاقة</option><option value="other">أخرى</option></select></label><Field label="رقم المرجع" value={form.referenceNo} onChange={(v: string) => set("referenceNo", v)} /><label className="grid gap-1 text-sm md:col-span-2"><span>ملاحظات</span><textarea value={form.notes} onChange={(e) => set("notes", e.target.value)} className="min-h-20 rounded-lg border bg-background p-3" /></label><Button type="submit" className="md:col-span-2" disabled={busy}>{busy ? "جارٍ الحفظ…" : submit}</Button></form></DialogContent></Dialog>; }
function Field({ label, value, onChange, type = "text", required }: any) { return <label className="grid gap-1 text-sm"><span>{label}</span><input type={type} value={value} onChange={(e) => onChange(e.target.value)} required={required} className="rounded-lg border bg-background px-3 py-2" /></label>; }
