import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { CheckCircle2, Landmark, Loader2, Wallet } from "lucide-react";
import { Button } from "@/components/ui/button";
import { adminFetch, apiErrorMessage } from "./_lib";
import { useToast } from "@/hooks/use-toast";

type Employee = { id: number; fullName: string; username: string; department?: string; jobTitle?: string | null; baseSalary?: number | string; hiredAt?: string | null; salaryType?: string; workingDaysPerWeek?: number | string; dailyWorkingHours?: number | string; overtimeRate?: number | string; transportationAllowance?: number | string; foodAllowance?: number | string; housingAllowance?: number | string; phoneAllowance?: number | string; otherFixedAllowances?: number | string; fixedDeduction?: number | string; paymentMethod?: string; salaryStatus?: string };
type Form = Record<string, string | boolean | string[]>;
const n = (value: unknown) => String(value ?? 0);
const initial = (employee: Employee): Form => ({ basicSalary: n(employee.baseSalary), salaryType: employee.salaryType ?? "monthly", department: employee.department ?? "general", jobTitle: employee.jobTitle ?? "", employmentType: "full_time", hiringDate: String(employee.hiredAt ?? "").slice(0, 10), firstPayrollDate: "", payrollStatus: employee.salaryStatus ?? "active", workingDaysPerWeek: n(employee.workingDaysPerWeek ?? 6), workingHoursPerDay: n(employee.dailyWorkingHours ?? 8), monthlyWorkingHours: "", shiftStart: "", shiftEnd: "", weeklyDaysOff: ["fri"], transportationAllowance: n(employee.transportationAllowance), foodAllowance: n(employee.foodAllowance), housingAllowance: n(employee.housingAllowance), phoneAllowance: n(employee.phoneAllowance), riskAllowance: "0", otherAllowance: n(employee.otherFixedAllowances), overtimeHourRate: n(employee.overtimeRate), weekendHourRate: "0", holidayHourRate: "0", maxMonthlyOvertime: "0", fixedDeduction: n(employee.fixedDeduction), taxDeduction: "0", insuranceDeduction: "0", retirementDeduction: "0", lateDeduction: "0", absenceDeduction: "0", otherDeduction: "0", monthlyBonus: "0", performanceBonus: "0", commission: "0", annualBonus: "0", otherBonus: "0", paymentMethod: employee.paymentMethod ?? "cash", bankName: "", accountNumber: "", iban: "", generatePayrollAutomatically: false, enableOvertime: true, enableAttendanceIntegration: true, enableAdvanceDeduction: true, enableBonuses: true, enablePenalties: true });

export function SalarySettingsTab({ employee, onSaved }: { employee: Employee; onSaved: () => void }) {
  const { toast } = useToast(); const [form, setForm] = useState<Form>(() => initial(employee));
  const details = useQuery({ queryKey: ["staff", employee.id, "salary-settings"], queryFn: () => adminFetch<any>(`/admin/staff/${employee.id}/salary-settings`) });
  useEffect(() => { const s = details.data?.settings; if (!s) return; setForm((f) => ({ ...f, ...s, basicSalary: n(employee.baseSalary), hiringDate: String(employee.hiredAt ?? "").slice(0, 10), workingHoursPerDay: n(employee.dailyWorkingHours ?? 8), overtimeHourRate: n(employee.overtimeRate), otherAllowance: n(employee.otherFixedAllowances), payrollStatus: employee.salaryStatus ?? "active", paymentMethod: employee.paymentMethod ?? "cash", weeklyDaysOff: s.weeklyDaysOff ?? [] })); }, [details.data, employee]);
  const set = (key: string, value: string | boolean | string[]) => setForm((f) => ({ ...f, [key]: value }));
  const estimate = useMemo(() => {
    const value = (key: string) => Number(form[key] ?? 0) || 0;
    const allowances = ["transportationAllowance", "foodAllowance", "housingAllowance", "phoneAllowance", "riskAllowance", "otherAllowance"].reduce((sum, key) => sum + value(key), 0);
    const bonuses = ["monthlyBonus", "performanceBonus", "commission", "annualBonus", "otherBonus"].reduce((sum, key) => sum + value(key), 0);
    const deductions = ["fixedDeduction", "taxDeduction", "insuranceDeduction", "retirementDeduction", "lateDeduction", "absenceDeduction", "otherDeduction"].reduce((sum, key) => sum + value(key), 0);
    return { allowances, bonuses, deductions, net: Math.max(0, value("basicSalary") + allowances + bonuses - deductions) };
  }, [form]);
  const save = useMutation({ mutationFn: () => adminFetch(`/admin/staff/${employee.id}/salary-settings`, { method: "PATCH", body: JSON.stringify(form) }), onSuccess: () => { toast({ title: "تم حفظ إعدادات الراتب" }); onSaved(); details.refetch(); }, onError: (error) => toast({ title: "تعذر حفظ إعدادات الراتب", description: apiErrorMessage(error), variant: "destructive" }) });
  const approve = useMutation({ mutationFn: () => adminFetch(`/admin/staff/${employee.id}/salary-settings/approve`, { method: "POST" }), onSuccess: () => { toast({ title: "تم اعتماد تغييرات الراتب" }); details.refetch(); }, onError: (error) => toast({ title: "تعذر الاعتماد", description: apiErrorMessage(error), variant: "destructive" }) });
  const money = new Intl.NumberFormat("ar-IQ", { style: "currency", currency: "IQD", maximumFractionDigits: 0 });
  if (details.isLoading) return <div className="h-64 animate-pulse rounded-xl bg-muted" />;
  return <div className="space-y-5" dir="rtl"><div className="rounded-xl bg-primary/5 p-4"><div className="flex items-start justify-between gap-3"><div className="flex gap-2"><Wallet className="mt-0.5 h-5 w-5 text-primary" /><div><h4 className="font-semibold">إعدادات الراتب</h4><p className="text-xs text-muted-foreground">تتحكم هذه البيانات في حساب راتب الموظف ودفعه.</p></div></div>{details.data?.settings?.approvalStatus === "pending" && <Button size="sm" variant="outline" onClick={() => approve.mutate()} disabled={approve.isPending}><CheckCircle2 className="ms-1 h-4 w-4" />اعتماد التغييرات</Button>}</div><div className="mt-4 grid grid-cols-2 gap-2 text-xs sm:grid-cols-3"><Summary label="الأساسي" value={money.format(Number(form.basicSalary) || 0)} /><Summary label="البدلات" value={money.format(estimate.allowances)} /><Summary label="الخصومات" value={money.format(estimate.deductions)} /><Summary label="المكافآت" value={money.format(estimate.bonuses)} /><Summary label="الدفع" value={paymentLabel(String(form.paymentMethod))} /><Summary label="الصافي التقديري" value={money.format(estimate.net)} strong /></div></div>
    <Group title="المعلومات الأساسية"><Input label="الراتب الأساسي *" type="number" value={form.basicSalary} onChange={(v) => set("basicSalary", v)} /><Select label="نوع الراتب *" value={String(form.salaryType)} onChange={(v) => set("salaryType", v)} options={[["monthly","شهري"],["weekly","أسبوعي"],["daily","يومي"],["hourly","بالساعة"]]} /><Input label="القسم" value={form.department} onChange={(v) => set("department", v)} /><Input label="المسمى الوظيفي" value={form.jobTitle} onChange={(v) => set("jobTitle", v)} /><Select label="نوع التوظيف" value={String(form.employmentType)} onChange={(v) => set("employmentType", v)} options={[["full_time","دوام كامل"],["part_time","دوام جزئي"],["contract","عقد"],["temporary","مؤقت"]]} /><Input label="تاريخ التعيين" type="date" value={form.hiringDate} onChange={(v) => set("hiringDate", v)} /><Input label="أول راتب" type="date" value={form.firstPayrollDate} onChange={(v) => set("firstPayrollDate", v)} /><Select label="حالة الرواتب *" value={String(form.payrollStatus)} onChange={(v) => set("payrollStatus", v)} options={[["active","نشط"],["suspended","معلّق"],["terminated","منتهي"],["on_leave","في إجازة"]]} /></Group>
    <Group title="جدول العمل"><Input label="أيام العمل أسبوعياً" type="number" value={form.workingDaysPerWeek} onChange={(v) => set("workingDaysPerWeek", v)} /><Input label="ساعات العمل يومياً" type="number" value={form.workingHoursPerDay} onChange={(v) => set("workingHoursPerDay", v)} /><Input label="ساعات العمل الشهرية" type="number" value={form.monthlyWorkingHours} onChange={(v) => set("monthlyWorkingHours", v)} /><Input label="بداية الوردية" type="time" value={form.shiftStart} onChange={(v) => set("shiftStart", v)} /><Input label="نهاية الوردية" type="time" value={form.shiftEnd} onChange={(v) => set("shiftEnd", v)} /><Days value={(form.weeklyDaysOff as string[]) ?? []} onChange={(v) => set("weeklyDaysOff", v)} /></Group>
    <Group title="البدلات"><MoneyInputs form={form} set={set} fields={[["transportationAllowance","بدل النقل"],["foodAllowance","بدل الطعام"],["housingAllowance","بدل السكن"],["phoneAllowance","بدل الهاتف"],["riskAllowance","بدل الخطورة"],["otherAllowance","بدل آخر"]]} /></Group>
    <Group title="الإضافي"><MoneyInputs form={form} set={set} fields={[["overtimeHourRate","ساعة إضافية"],["weekendHourRate","ساعة عطلة أسبوعية"],["holidayHourRate","ساعة عطلة رسمية"],["maxMonthlyOvertime","الحد الشهري للإضافي"]]} /></Group>
    <Group title="الخصومات"><MoneyInputs form={form} set={set} fields={[["fixedDeduction","خصم ثابت"],["taxDeduction","الضريبة"],["insuranceDeduction","التأمين"],["retirementDeduction","التقاعد"],["lateDeduction","خصم التأخير"],["absenceDeduction","خصم الغياب"],["otherDeduction","خصم آخر"]]} /><p className="col-span-full text-xs text-muted-foreground">السلف تُخصم تلقائياً من وحدة سلف الموظفين عند تفعيل الخيار أدناه.</p></Group>
    <Group title="المكافآت"><MoneyInputs form={form} set={set} fields={[["monthlyBonus","مكافأة شهرية"],["performanceBonus","مكافأة الأداء"],["commission","العمولة"],["annualBonus","مكافأة سنوية"],["otherBonus","مكافأة أخرى"]]} /></Group>
    <Group title="الدفع"><Select label="طريقة الدفع *" value={String(form.paymentMethod)} onChange={(v) => set("paymentMethod", v)} options={[["main_cash_box","الصندوق الرئيسي"],["bank","بنك"],["cash","نقدي"],["transfer","تحويل"]]} /><Input label="اسم البنك" value={form.bankName} onChange={(v) => set("bankName", v)} /><Input label="رقم الحساب" value={form.accountNumber} onChange={(v) => set("accountNumber", v)} /><Input label="IBAN" value={form.iban} onChange={(v) => set("iban", v)} /><Landmark className="m-4 h-5 w-5 text-primary" /></Group>
    <section className="rounded-xl border border-border/40 p-4"><h5 className="mb-3 font-semibold">خيارات الرواتب</h5><div className="grid gap-2 sm:grid-cols-2">{[["generatePayrollAutomatically","إنشاء الراتب تلقائياً"],["enableOvertime","تفعيل الإضافي"],["enableAttendanceIntegration","ربط الحضور"],["enableAdvanceDeduction","خصم السلف"],["enableBonuses","تفعيل المكافآت"],["enablePenalties","تفعيل الجزاءات"]].map(([key,label]) => <label key={key} className="flex items-center gap-2 rounded-lg bg-muted/50 px-3 py-2 text-sm"><input type="checkbox" checked={form[key] === true} onChange={(e) => set(key, e.target.checked)} className="accent-primary" />{label}</label>)}</div></section>
    <div className="flex justify-end"><Button onClick={() => save.mutate()} disabled={save.isPending}>{save.isPending && <Loader2 className="ms-1 h-4 w-4 animate-spin" />}حفظ إعدادات الراتب</Button></div></div>;
}
function Group({ title, children }: { title: string; children: React.ReactNode }) { return <section><h5 className="mb-2 font-semibold text-foreground">{title}</h5><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{children}</div></section>; }
function Input({ label, type = "text", value, onChange }: { label: string; type?: string; value: unknown; onChange: (value: string) => void }) { return <label className="block text-xs text-muted-foreground">{label}<input type={type} min={type === "number" ? 0 : undefined} value={String(value ?? "")} onChange={(e) => onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-border/40 bg-background px-3 py-2 text-sm text-foreground" /></label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <label className="block text-xs text-muted-foreground">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 w-full rounded-lg border border-border/40 bg-background px-3 py-2 text-sm text-foreground">{options.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label>; }
function MoneyInputs({ fields, form, set }: { fields: string[][]; form: Form; set: (key: string, value: string) => void }) { return <>{fields.map(([key,label]) => <Input key={key} label={label} type="number" value={form[key]} onChange={(v) => set(key,v)} />)}</>; }
function Days({ value, onChange }: { value: string[]; onChange: (value: string[]) => void }) { const days = [["sat","السبت"],["sun","الأحد"],["mon","الاثنين"],["tue","الثلاثاء"],["wed","الأربعاء"],["thu","الخميس"],["fri","الجمعة"]]; return <div className="sm:col-span-2"><p className="mb-1 text-xs text-muted-foreground">أيام العطلة الأسبوعية</p><div className="flex flex-wrap gap-2">{days.map(([key,label]) => <label key={key} className="flex items-center gap-1 text-xs"><input type="checkbox" checked={value.includes(key)} onChange={(e) => onChange(e.target.checked ? [...value,key] : value.filter((day) => day !== key))} className="accent-primary" />{label}</label>)}</div></div>; }
function Summary({ label, value, strong = false }: { label: string; value: string; strong?: boolean }) { return <div className="rounded-lg bg-background/80 p-2"><p className="text-muted-foreground">{label}</p><p className={strong ? "mt-1 font-bold text-primary" : "mt-1 font-semibold"}>{value}</p></div>; }
function paymentLabel(value: string) { return ({ main_cash_box: "الصندوق الرئيسي", bank: "بنك", cash: "نقدي", transfer: "تحويل" } as Record<string,string>)[value] ?? "—"; }
