import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckSquare, Plus, Pencil, Printer, Trash2, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { adminFetch } from "./_lib";
import { useToast } from "@/hooks/use-toast";
import { logoSrc, usePublicSettings } from "@/lib/public-settings";
import { openSimpleSalarySlipPrintWindow } from "./print-helpers";

type Salary = { id:number; runId:number; employeeId:number; employeeName:string; username:string; department:string; month:string; baseSalary:number; bonus:number; deduction:number; netSalary:number; paymentStatus:string; notes?:string|null; paidAt?:string|null };
type Staff = { id:number; fullName:string; username:string; department:string; baseSalary:number };
type Data = { month:string; rows:Salary[]; staff:Staff[]; history?:Salary[]; totals:{count:number;base:number;bonus:number;deduction:number;net:number} };
type BulkResult = { processed:Array<{lineId:number;amount:number}>; skipped:Array<{lineId:number;reason:string}>; failed:Array<{lineId:number;reason:string}> };
const currentMonth=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Baghdad",year:"numeric",month:"2-digit"}).format(new Date()).slice(0,7);
const money=(n:number)=>`${Math.round(Number(n||0)).toLocaleString("ar-IQ-u-nu-latn")} د.ع`;
const date=(v?:string|null)=>v?new Intl.DateTimeFormat("ar-IQ-u-nu-latn",{dateStyle:"medium"}).format(new Date(v)):"—";
const blank=(month=currentMonth())=>({employeeId:"",month,baseSalary:"0",bonus:"0",deduction:"0",notes:""});

export default function SimpleSalariesPage(){
 const {toast}=useToast(); const qc=useQueryClient();
 const {data:settings}=usePublicSettings();
 const [month,setMonth]=useState(currentMonth()); const [search,setSearch]=useState(""); const [department,setDepartment]=useState(""); const [status,setStatus]=useState("");
 const [form,setForm]=useState(blank()); const [editing,setEditing]=useState<Salary|null>(null); const [open,setOpen]=useState(false); const [historyEmployee,setHistoryEmployee]=useState<Salary|null>(null);
 const [selected,setSelected]=useState<Set<number>>(new Set()); const [paying,setPaying]=useState<Salary|null>(null); const [deleting,setDeleting]=useState<Salary|null>(null); const [bulkOpen,setBulkOpen]=useState(false); const [bulkResult,setBulkResult]=useState<BulkResult|null>(null);
 const query=useQuery<Data>({queryKey:["simple-salaries",month,search,department,status],queryFn:()=>adminFetch(`/admin/hr/simple-salaries?month=${encodeURIComponent(month)}&search=${encodeURIComponent(search)}&department=${encodeURIComponent(department)}&status=${encodeURIComponent(status)}`)});
 const history=useQuery<Data>({queryKey:["simple-salary-history",historyEmployee?.employeeId],queryFn:()=>adminFetch(`/admin/hr/simple-salaries?historyEmployeeId=${historyEmployee?.employeeId}`),enabled:Boolean(historyEmployee?.employeeId)});
 const refresh=async()=>{setSelected(new Set());await qc.invalidateQueries({queryKey:["simple-salaries"]});};
 const save=useMutation({mutationFn:()=>{const payload={...form,employeeId:Number(form.employeeId),baseSalary:Number(form.baseSalary),bonus:Number(form.bonus),deduction:Number(form.deduction)};return adminFetch(editing?`/admin/hr/simple-salaries/${editing.id}`:"/admin/hr/simple-salaries",{method:editing?"PATCH":"POST",body:JSON.stringify(payload)});},onSuccess:async()=>{await refresh();setOpen(false);toast({title:editing?"تم تعديل الراتب":"تم حفظ الراتب"});},onError:(e:Error)=>toast({title:"تعذر حفظ الراتب",description:e.message,variant:"destructive"})});
 const pay=useMutation({mutationFn:(row:Salary)=>adminFetch<{kind:string;reason?:string}>(`/admin/hr/simple-salaries/${row.id}/pay`,{method:"POST",body:JSON.stringify({})}),onSuccess:async(result)=>{await refresh();setPaying(null);toast({title:result.kind==="skipped"?(result.reason||"تم صرفه مسبقاً"):"تم صرف راتب الموظف بنجاح"});},onError:(e:Error)=>toast({title:"تعذر صرف الراتب",description:e.message,variant:"destructive"})});
 const remove=useMutation({mutationFn:(row:Salary)=>adminFetch<{deleted:boolean}>(`/admin/hr/simple-salaries/${row.id}`,{method:"DELETE"}),onSuccess:async()=>{await refresh();setDeleting(null);toast({title:"تم حذف سجل الراتب"});},onError:(e:Error)=>toast({title:"تعذر حذف سجل الراتب",description:e.message,variant:"destructive"})});
 const bulkPay=useMutation({mutationFn:(lineIds:number[])=>adminFetch<BulkResult>("/admin/hr/simple-salaries/bulk-pay",{method:"POST",body:JSON.stringify({lineIds})}),onSuccess:async(result)=>{await refresh();setBulkOpen(false);setBulkResult(result);toast({title:`تمت معالجة ${result.processed.length} راتب`});},onError:(e:Error)=>toast({title:"تعذر صرف الرواتب المحددة",description:e.message,variant:"destructive"})});
 const departments=useMemo(()=>Array.from(new Set((query.data?.staff||[]).map(s=>s.department).filter(Boolean))),[query.data?.staff]);
 const rows=query.data?.rows||[]; const unpaid=rows.filter(r=>r.paymentStatus!=="paid"); const selectedRows=unpaid.filter(r=>selected.has(r.id)); const selectedTotal=selectedRows.reduce((n,r)=>n+Number(r.netSalary||0),0);
 const chooseEmployee=(id:string)=>{const employee=query.data?.staff.find(x=>x.id===Number(id));setForm(x=>({...x,employeeId:id,baseSalary:String(employee?.baseSalary??0)}));};
 const net=Math.max(0,Number(form.baseSalary||0)+Number(form.bonus||0)-Number(form.deduction||0));
 const toggleAll=(checked:boolean)=>setSelected(checked?new Set(unpaid.map(r=>r.id)):new Set());
 const toggle=(id:number,checked:boolean)=>setSelected(old=>{const next=new Set(old);checked?next.add(id):next.delete(id);return next;});
 const printSalary=(row:Salary)=>openSimpleSalarySlipPrintWindow({companyName:settings?.site_name,logoUrl:logoSrc(settings),employeeName:row.employeeName||row.username,department:row.department,month:row.month,baseSalary:row.baseSalary,bonus:row.bonus,deduction:row.deduction,netSalary:row.netSalary,paymentStatus:row.paymentStatus,paidAt:row.paidAt});
 return <div className="space-y-4" dir="rtl">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">رواتب الموظفين</h1><p className="text-sm text-muted-foreground">سجل شهري بسيط: الأساسي + المكافأة − الخصم.</p></div><Button onClick={()=>{setEditing(null);setForm(blank(month));setOpen(true);}}><Plus className="ml-1 h-4 w-4"/>إضافة راتب</Button></div>
  <div className="grid grid-cols-2 gap-3 md:grid-cols-5">{[["عدد الموظفين",query.data?.totals.count||0],["إجمالي الرواتب الأساسية",money(query.data?.totals.base||0)],["إجمالي المكافآت",money(query.data?.totals.bonus||0)],["إجمالي الخصومات",money(query.data?.totals.deduction||0)],["صافي الرواتب",money(query.data?.totals.net||0)]].map(([label,value])=><div key={String(label)} className="rounded-xl border bg-card p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-bold">{value}</p></div>)}</div>
  <div className="grid gap-2 rounded-xl border bg-card p-3 md:grid-cols-4"><Input type="month" value={month} onChange={e=>setMonth(e.target.value||currentMonth())}/><Input placeholder="بحث باسم الموظف" value={search} onChange={e=>setSearch(e.target.value)}/><select className="h-10 rounded-md border bg-background px-3" value={department} onChange={e=>setDepartment(e.target.value)}><option value="">كل الأقسام</option>{departments.map(x=><option key={x} value={x}>{x}</option>)}</select><select className="h-10 rounded-md border bg-background px-3" value={status} onChange={e=>setStatus(e.target.value)}><option value="">كل الحالات</option><option value="unpaid">غير مصروف</option><option value="paid">تم الصرف</option></select></div>
  {selectedRows.length?<div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-primary/30 bg-primary/5 p-3"><p className="text-sm font-bold">تم تحديد {selectedRows.length} موظف · الإجمالي {money(selectedTotal)}</p><div className="flex gap-2"><Button type="button" variant="outline" onClick={()=>setSelected(new Set())}>إلغاء التحديد</Button><Button type="button" onClick={()=>setBulkOpen(true)}><CheckSquare className="ml-1 h-4 w-4"/>صرف المحدد ({selectedRows.length})</Button></div></div>:null}
  <div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full min-w-[970px] text-sm"><thead className="bg-muted/50 text-right"><tr><th className="w-12 p-3"><input aria-label="تحديد كل الرواتب غير المصروفة" type="checkbox" checked={unpaid.length>0&&selectedRows.length===unpaid.length} onChange={e=>toggleAll(e.target.checked)}/></th>{["الموظف","القسم","الشهر","الراتب الأساسي","المكافأة","الخصم","الصافي","الحالة","الإجراءات"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t"><td className="p-3">{row.paymentStatus!=="paid"?<input aria-label={`تحديد راتب ${row.employeeName||row.username}`} type="checkbox" checked={selected.has(row.id)} onChange={e=>toggle(row.id,e.target.checked)}/>:null}</td><td className="p-3 font-medium"><button type="button" className="text-right underline-offset-4 hover:underline" onClick={()=>setHistoryEmployee(row)}>{row.employeeName||row.username}</button></td><td>{row.department}</td><td>{row.month}</td><td>{money(row.baseSalary)}</td><td>{money(row.bonus)}</td><td>{money(row.deduction)}</td><td className="font-semibold">{money(row.netSalary)}</td><td><span className={row.paymentStatus==="paid"?"text-emerald-600":"text-amber-600"}>{row.paymentStatus==="paid"?"تم الصرف":"غير مصروف"}</span></td><td className="p-2"><div className="flex gap-1"><Button size="sm" variant="outline" aria-label="طباعة الراتب" onClick={()=>printSalary(row)}><Printer className="ml-1 h-4 w-4"/>طباعة</Button>{row.paymentStatus!=="paid"?<><Button size="sm" variant="outline" aria-label="تعديل الراتب" onClick={()=>{setEditing(row);setForm({employeeId:String(row.employeeId),month:row.month,baseSalary:String(row.baseSalary),bonus:String(row.bonus),deduction:String(row.deduction),notes:row.notes||""});setOpen(true);}}><Pencil className="h-4 w-4"/></Button><Button size="sm" variant="outline" className="text-destructive hover:text-destructive" aria-label="حذف الراتب" onClick={()=>setDeleting(row)}><Trash2 className="h-4 w-4"/></Button><Button size="sm" disabled={pay.isPending} onClick={()=>setPaying(row)}><WalletCards className="ml-1 h-4 w-4"/>صرف الراتب</Button></>:null}</div></td></tr>)}</tbody></table>{!query.isLoading&&!rows.length?<p className="p-10 text-center text-muted-foreground">لا توجد رواتب لهذا الشهر.</p>:null}</div>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent dir="rtl"><DialogHeader><DialogTitle>{editing?"تعديل راتب":"إضافة راتب"}</DialogTitle></DialogHeader><div className="grid gap-3"><select disabled={!!editing} className="h-10 rounded-md border bg-background px-3" value={form.employeeId} onChange={e=>chooseEmployee(e.target.value)}><option value="">اختر الموظف</option>{query.data?.staff.map(s=><option key={s.id} value={s.id}>{s.fullName||s.username} — {s.department}</option>)}</select><Input type="month" value={form.month} onChange={e=>setForm({...form,month:e.target.value})}/><Input type="number" min="0" placeholder="الراتب الأساسي" value={form.baseSalary} onChange={e=>setForm({...form,baseSalary:e.target.value})}/><Input type="number" min="0" placeholder="المكافأة" value={form.bonus} onChange={e=>setForm({...form,bonus:e.target.value})}/><Input type="number" min="0" placeholder="الخصم" value={form.deduction} onChange={e=>setForm({...form,deduction:e.target.value})}/><textarea className="min-h-20 rounded-md border bg-background p-2" placeholder="ملاحظة" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><div className="rounded-lg bg-muted p-3 font-semibold">الصافي: {money(net)}</div></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>إلغاء</Button><Button disabled={!form.employeeId||!form.month||save.isPending} onClick={()=>save.mutate()}>حفظ</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={Boolean(paying)} onOpenChange={v=>{if(!v)setPaying(null);}}><DialogContent dir="rtl"><DialogHeader><DialogTitle>تأكيد صرف راتب الموظف</DialogTitle></DialogHeader>{paying?<div className="grid grid-cols-2 gap-3 rounded-xl bg-muted/40 p-4 text-sm"><p>الموظف <b className="mt-1 block">{paying.employeeName||paying.username}</b></p><p>القسم <b className="mt-1 block">{paying.department||"—"}</b></p><p>الشهر <b className="mt-1 block">{paying.month}</b></p><p>الراتب الأساسي <b className="mt-1 block">{money(paying.baseSalary)}</b></p><p>المكافأة <b className="mt-1 block">{money(paying.bonus)}</b></p><p>الخصم <b className="mt-1 block">{money(paying.deduction)}</b></p><p className="col-span-2 text-base">الصافي <b className="mr-2 text-primary">{money(paying.netSalary)}</b></p></div>:null}<DialogFooter><Button variant="outline" onClick={()=>setPaying(null)}>إلغاء</Button><Button disabled={pay.isPending||!paying} onClick={()=>paying&&pay.mutate(paying)}>تأكيد الصرف</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={Boolean(deleting)} onOpenChange={v=>{if(!v)setDeleting(null);}}><DialogContent dir="rtl"><DialogHeader><DialogTitle>حذف سجل الراتب</DialogTitle></DialogHeader>{deleting?<p className="text-sm leading-7 text-muted-foreground">هل تريد حذف راتب <b className="text-foreground">{deleting.employeeName||deleting.username}</b> لشهر <b className="text-foreground">{deleting.month}</b>؟ الحذف متاح فقط قبل الصرف، ولا يؤثر على أي حركة مالية.</p>:null}<DialogFooter><Button variant="outline" onClick={()=>setDeleting(null)}>إلغاء</Button><Button variant="destructive" disabled={remove.isPending||!deleting} onClick={()=>deleting&&remove.mutate(deleting)}>حذف الراتب</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={bulkOpen} onOpenChange={setBulkOpen}><DialogContent dir="rtl" className="max-w-lg"><DialogHeader><DialogTitle>صرف رواتب الموظفين المحددين</DialogTitle></DialogHeader><div className="space-y-3"><p className="text-sm">عدد الموظفين: <b>{selectedRows.length}</b> · إجمالي المبلغ: <b>{money(selectedTotal)}</b></p><div className="max-h-52 overflow-auto rounded-lg border"><table className="w-full text-sm"><thead className="bg-muted/50"><tr><th className="p-2 text-right">الموظف</th><th className="p-2 text-right">الصافي</th></tr></thead><tbody>{selectedRows.map(row=><tr key={row.id} className="border-t"><td className="p-2">{row.employeeName||row.username}</td><td className="p-2 font-bold">{money(row.netSalary)}</td></tr>)}</tbody></table></div></div><DialogFooter><Button variant="outline" onClick={()=>setBulkOpen(false)}>إلغاء</Button><Button disabled={bulkPay.isPending||!selectedRows.length} onClick={()=>bulkPay.mutate(selectedRows.map(row=>row.id))}>تأكيد الصرف</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={Boolean(bulkResult)} onOpenChange={v=>{if(!v)setBulkResult(null);}}><DialogContent dir="rtl"><DialogHeader><DialogTitle>نتيجة صرف الرواتب</DialogTitle></DialogHeader>{bulkResult?<div className="space-y-3 text-sm"><p>تمت المعالجة: <b>{bulkResult.processed.length}</b></p><p>تم التخطي: <b>{bulkResult.skipped.length}</b></p><p>فشل: <b>{bulkResult.failed.length}</b></p>{[...bulkResult.skipped,...bulkResult.failed].length?<ul className="max-h-40 list-inside list-disc overflow-auto rounded-lg bg-muted/40 p-3">{[...bulkResult.skipped,...bulkResult.failed].map(x=><li key={`${x.lineId}-${x.reason}`}>سجل #{x.lineId}: {x.reason}</li>)}</ul>:null}</div>:null}<DialogFooter><Button onClick={()=>setBulkResult(null)}>إغلاق</Button></DialogFooter></DialogContent></Dialog>
  <Dialog open={Boolean(historyEmployee)} onOpenChange={v=>{if(!v)setHistoryEmployee(null);}}><DialogContent dir="rtl" className="max-w-3xl"><DialogHeader><DialogTitle>سجل الرواتب — {historyEmployee?.employeeName||historyEmployee?.username}</DialogTitle></DialogHeader><div className="max-h-[60vh] overflow-auto rounded-lg border"><table className="w-full min-w-[680px] text-sm"><thead className="bg-muted/50 text-right"><tr>{["الشهر","الأساسي","المكافأة","الخصم","الصافي","الحالة","تاريخ الصرف"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{history.data?.history?.map(row=><tr key={row.id} className="border-t"><td className="p-3">{row.month}</td><td>{money(row.baseSalary)}</td><td>{money(row.bonus)}</td><td>{money(row.deduction)}</td><td className="font-semibold">{money(row.netSalary)}</td><td>{row.paymentStatus==="paid"?"تم الصرف":"غير مصروف"}</td><td>{date(row.paidAt)}</td></tr>)}</tbody></table>{history.isLoading?<p className="p-6 text-center text-muted-foreground">جاري تحميل السجل…</p>:null}{history.isSuccess&&!(history.data?.history??[]).length?<p className="p-6 text-center text-muted-foreground">لا يوجد سجل رواتب مبسط لهذا الموظف.</p>:null}</div></DialogContent></Dialog>
 </div>;
}
