import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, Pencil, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { adminFetch } from "./_lib";
import { useToast } from "@/hooks/use-toast";

type Salary = { id: number; runId: number; employeeId: number; employeeName: string; username: string; department: string; month: string; baseSalary: number; bonus: number; deduction: number; netSalary: number; paymentStatus: string; notes?: string | null; paidAt?: string | null };
type Staff = { id: number; fullName: string; username: string; department: string; baseSalary: number };
type Data = { month: string; rows: Salary[]; staff: Staff[]; history?: Salary[]; totals: { count: number; base: number; bonus: number; deduction: number; net: number } };
const currentMonth = () => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Baghdad", year: "numeric", month: "2-digit" }).format(new Date()).slice(0, 7);
const money = (value: number) => `${Math.round(Number(value || 0)).toLocaleString("ar-IQ-u-nu-latn")} د.ع`;
const blank = (month = currentMonth()) => ({ employeeId: "", month, baseSalary: "0", bonus: "0", deduction: "0", notes: "" });

export default function SimpleSalariesPage() {
  const { toast } = useToast(); const qc = useQueryClient();
  const [month, setMonth] = useState(currentMonth()); const [search, setSearch] = useState(""); const [department, setDepartment] = useState(""); const [status, setStatus] = useState("");
  const [form, setForm] = useState(blank()); const [editing, setEditing] = useState<Salary | null>(null); const [open, setOpen] = useState(false); const [historyEmployee, setHistoryEmployee] = useState<Salary | null>(null);
  const query = useQuery<Data>({ queryKey: ["simple-salaries", month, search, department, status], queryFn: () => adminFetch(`/admin/hr/simple-salaries?month=${encodeURIComponent(month)}&search=${encodeURIComponent(search)}&department=${encodeURIComponent(department)}&status=${encodeURIComponent(status)}`) });
  const history = useQuery<Data>({ queryKey: ["simple-salary-history", historyEmployee?.employeeId], queryFn: () => adminFetch(`/admin/hr/simple-salaries?historyEmployeeId=${historyEmployee?.employeeId}`), enabled: Boolean(historyEmployee?.employeeId) });
  const refresh = () => qc.invalidateQueries({ queryKey: ["simple-salaries"] });
  const save = useMutation({ mutationFn: () => { const payload = { ...form, employeeId: Number(form.employeeId), baseSalary: Number(form.baseSalary), bonus: Number(form.bonus), deduction: Number(form.deduction) }; return adminFetch(editing ? `/admin/hr/simple-salaries/${editing.id}` : "/admin/hr/simple-salaries", { method: editing ? "PATCH" : "POST", body: JSON.stringify(payload) }); }, onSuccess: () => { refresh(); setOpen(false); toast({ title: editing ? "تم تعديل الراتب" : "تم حفظ الراتب" }); }, onError: (e: Error) => toast({ title: "تعذر حفظ الراتب", description: e.message, variant: "destructive" }) });
  const pay = useMutation({ mutationFn: (row: Salary) => adminFetch(`/admin/hr/simple-salaries/${row.id}/pay`, { method: "POST", body: JSON.stringify({ employeeId: row.employeeId, month: row.month, baseSalary: row.baseSalary, bonus: row.bonus, deduction: row.deduction, notes: row.notes || "" }) }), onSuccess: () => { refresh(); toast({ title: "تم صرف الراتب" }); }, onError: (e: Error) => toast({ title: "تعذر صرف الراتب", description: e.message, variant: "destructive" }) });
  const departments = useMemo(() => Array.from(new Set((query.data?.staff || []).map((s) => s.department).filter(Boolean))), [query.data?.staff]);
  const chooseEmployee = (id: string) => { const employee = query.data?.staff.find((item) => item.id === Number(id)); setForm((current) => ({ ...current, employeeId: id, baseSalary: String(employee?.baseSalary ?? 0) })); };
  const net = Math.max(0, Number(form.baseSalary || 0) + Number(form.bonus || 0) - Number(form.deduction || 0));
  return <div className="space-y-4" dir="rtl"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">رواتب الموظفين</h1><p className="text-sm text-muted-foreground">سجل شهري بسيط: الأساسي + المكافأة − الخصم.</p></div><Button onClick={() => { setEditing(null); setForm(blank(month)); setOpen(true); }}><Plus className="ml-1 h-4 w-4" />إضافة راتب</Button></div>
    <div className="grid grid-cols-2 gap-3 md:grid-cols-5">{[["عدد الموظفين", query.data?.totals.count || 0], ["إجمالي الرواتب الأساسية", money(query.data?.totals.base || 0)], ["إجمالي المكافآت", money(query.data?.totals.bonus || 0)], ["إجمالي الخصومات", money(query.data?.totals.deduction || 0)], ["صافي الرواتب", money(query.data?.totals.net || 0)]].map(([label, value]) => <div key={String(label)} className="rounded-xl border bg-card p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-bold">{value}</p></div>)}</div>
    <div className="grid gap-2 rounded-xl border bg-card p-3 md:grid-cols-4"><Input type="month" value={month} onChange={(e) => setMonth(e.target.value || currentMonth())} /><Input placeholder="بحث باسم الموظف" value={search} onChange={(e) => setSearch(e.target.value)} /><select className="h-10 rounded-md border bg-background px-3" value={department} onChange={(e) => setDepartment(e.target.value)}><option value="">كل الأقسام</option>{departments.map((item) => <option key={item} value={item}>{item}</option>)}</select><select className="h-10 rounded-md border bg-background px-3" value={status} onChange={(e) => setStatus(e.target.value)}><option value="">كل الحالات</option><option value="unpaid">غير مصروف</option><option value="paid">تم الصرف</option></select></div>
    <div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full min-w-[850px] text-sm"><thead className="bg-muted/50 text-right"><tr>{["الموظف", "القسم", "الشهر", "الراتب الأساسي", "المكافأة", "الخصم", "الصافي", "الحالة", "الإجراءات"].map((x) => <th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{query.data?.rows.map((row) => <tr key={row.id} className="border-t"><td className="p-3 font-medium"><button type="button" className="text-right underline-offset-4 hover:underline" onClick={() => setHistoryEmployee(row)}>{row.employeeName || row.username}</button></td><td>{row.department}</td><td>{row.month}</td><td>{money(row.baseSalary)}</td><td>{money(row.bonus)}</td><td>{money(row.deduction)}</td><td className="font-semibold">{money(row.netSalary)}</td><td><span className={row.paymentStatus === "paid" ? "text-emerald-600" : "text-amber-600"}>{row.paymentStatus === "paid" ? "تم الصرف" : "غير مصروف"}</span></td><td className="p-2"><div className="flex gap-1">{row.paymentStatus !== "paid" && <><Button size="sm" variant="outline" onClick={() => { setEditing(row); setForm({ employeeId: String(row.employeeId), month: row.month, baseSalary: String(row.baseSalary), bonus: String(row.bonus), deduction: String(row.deduction), notes: row.notes || "" }); setOpen(true); }}><Pencil className="h-4 w-4" /></Button><Button size="sm" disabled={pay.isPending} onClick={() => confirm(`تأكيد صرف ${money(row.netSalary)} للموظف ${row.employeeName}؟`) && pay.mutate(row)}><WalletCards className="ml-1 h-4 w-4" />صرف الراتب</Button></>}</div></td></tr>)}</tbody></table>{!query.isLoading && !query.data?.rows.length && <p className="p-10 text-center text-muted-foreground">لا توجد رواتب لهذا الشهر.</p>}</div>
    <Dialog open={open} onOpenChange={setOpen}><DialogContent dir="rtl"><DialogHeader><DialogTitle>{editing ? "تعديل راتب" : "إضافة راتب"}</DialogTitle></DialogHeader><div className="grid gap-3"><select disabled={!!editing} className="h-10 rounded-md border bg-background px-3" value={form.employeeId} onChange={(e) => chooseEmployee(e.target.value)}><option value="">اختر الموظف</option>{query.data?.staff.map((s) => <option key={s.id} value={s.id}>{s.fullName || s.username} — {s.department}</option>)}</select><Input type="month" value={form.month} onChange={(e) => setForm({ ...form, month: e.target.value })} /><Input type="number" min="0" placeholder="الراتب الأساسي" value={form.baseSalary} onChange={(e) => setForm({ ...form, baseSalary: e.target.value })} /><Input type="number" min="0" placeholder="المكافأة" value={form.bonus} onChange={(e) => setForm({ ...form, bonus: e.target.value })} /><Input type="number" min="0" placeholder="الخصم" value={form.deduction} onChange={(e) => setForm({ ...form, deduction: e.target.value })} /><textarea className="min-h-20 rounded-md border bg-background p-2" placeholder="ملاحظة" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /><div className="rounded-lg bg-muted p-3 font-semibold">الصافي: {money(net)}</div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>إلغاء</Button><Button disabled={!form.employeeId || !form.month || save.isPending} onClick={() => save.mutate()}>حفظ</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={Boolean(historyEmployee)} onOpenChange={(value) => { if (!value) setHistoryEmployee(null); }}><DialogContent dir="rtl" className="max-w-3xl"><DialogHeader><DialogTitle>سجل الرواتب — {historyEmployee?.employeeName || historyEmployee?.username}</DialogTitle></DialogHeader><div className="max-h-[60vh] overflow-auto rounded-lg border"><table className="w-full min-w-[680px] text-sm"><thead className="bg-muted/50 text-right"><tr>{["الشهر", "الأساسي", "المكافأة", "الخصم", "الصافي", "الحالة", "تاريخ الصرف"].map((label) => <th key={label} className="p-3">{label}</th>)}</tr></thead><tbody>{history.data?.history?.map((row) => <tr key={row.id} className="border-t"><td className="p-3">{row.month}</td><td>{money(row.baseSalary)}</td><td>{money(row.bonus)}</td><td>{money(row.deduction)}</td><td className="font-semibold">{money(row.netSalary)}</td><td>{row.paymentStatus === "paid" ? "تم الصرف" : "غير مصروف"}</td><td>{row.paidAt ? new Intl.DateTimeFormat("ar-IQ-u-nu-latn", { dateStyle: "medium" }).format(new Date(row.paidAt)) : "—"}</td></tr>)}</tbody></table>{history.isLoading ? <p className="p-6 text-center text-muted-foreground">جاري تحميل السجل…</p> : null}{history.isSuccess && !(history.data?.history ?? []).length ? <p className="p-6 text-center text-muted-foreground">لا يوجد سجل رواتب مبسط لهذا الموظف.</p> : null}</div></DialogContent></Dialog>
  </div>;
}
