import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Eye, Plus, Search, Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { TableTotalsFooter } from "@/components/ui/table-totals-footer";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import { adminFetch, apiErrorMessage } from "./_lib";

type Supplier = { id: number; supplierCode?: string; name: string; company?: string; contactPerson?: string; phone?: string; whatsapp?: string; email?: string; address?: string; category?: string; paymentTerms?: string; creditLimit?: number; openingBalance?: number; balance: number | string; notes?: string; status?: string; isActive: number };
const money = new Intl.NumberFormat("ar-IQ", { style: "currency", currency: "IQD", maximumFractionDigits: 0 });
const blank = (): Partial<Supplier> => ({ name: "", company: "", contactPerson: "", phone: "", whatsapp: "", email: "", address: "", category: "", paymentTerms: "", creditLimit: 0, openingBalance: 0, notes: "", status: "active" });

export default function SuppliersPage() {
  const qc = useQueryClient(); const { toast } = useToast(); const [q, setQ] = useState(""); const [status, setStatus] = useState("all"); const [editing, setEditing] = useState<Partial<Supplier> | null>(null); const [profile, setProfile] = useState<any>(null);
  const suppliers = useQuery({ queryKey: ["admin", "suppliers"], queryFn: () => adminFetch<Supplier[]>("/admin/suppliers") }); const dashboard = useQuery({ queryKey: ["admin", "suppliers", "dashboard"], queryFn: () => adminFetch<any>("/admin/suppliers/dashboard") });
  const rows = useMemo(() => (suppliers.data ?? []).filter((s) => (status === "all" || s.status === status) && `${s.name} ${s.company ?? ""} ${s.phone ?? ""} ${s.supplierCode ?? ""}`.toLowerCase().includes(q.toLowerCase())), [suppliers.data, q, status]);
  const save = useMutation({ mutationFn: (value: Partial<Supplier>) => adminFetch<Supplier>(value.id ? `/admin/suppliers/${value.id}` : "/admin/suppliers", { method: value.id ? "PUT" : "POST", body: JSON.stringify(value) }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["admin", "suppliers"] }); setEditing(null); toast({ title: "تم حفظ المورد" }); }, onError: (e) => toast({ title: "تعذر الحفظ", description: apiErrorMessage(e), variant: "destructive" }) });
  const disable = useMutation({ mutationFn: (id: number) => adminFetch(`/admin/suppliers/${id}`, { method: "DELETE" }), onSuccess: () => { qc.invalidateQueries({ queryKey: ["admin", "suppliers"] }); toast({ title: "تم تعطيل المورد" }); } });
  async function showProfile(id: number) { try { setProfile(await adminFetch(`/admin/suppliers/${id}/profile`)); } catch (e) { toast({ title: "تعذر فتح الملف", description: apiErrorMessage(e), variant: "destructive" }); } }
  const stats = [["إجمالي الموردين", dashboard.data?.total, false], ["الموردون النشطون", dashboard.data?.active, false], ["الرصيد المستحق", dashboard.data?.outstanding, true], ["مشتريات الشهر", dashboard.data?.monthly_purchases, true]] as const;
  return <div className="space-y-5" dir="rtl"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">الموردون</h1><p className="text-sm text-muted-foreground">إدارة الموردين، الأرصدة، وسجل التوريد.</p></div><Button onClick={() => setEditing(blank())}><Plus className="ms-1 h-4 w-4" />إضافة مورد</Button></div><div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{stats.map(([label, value, isMoney]) => <div key={label} className="rounded-xl border bg-card p-3"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-bold">{isMoney ? money.format(Number(value ?? 0)) : Number(value ?? 0).toLocaleString("ar-IQ")}</p></div>)}</div><div className="flex gap-2"><div className="relative min-w-64"><Search className="absolute right-3 top-3 h-4 w-4 text-muted-foreground" /><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="بحث بالاسم، الرمز، الشركة، الهاتف" className="w-full rounded-lg border bg-background py-2 ps-9 pe-3 text-sm" /></div><select value={status} onChange={(e) => setStatus(e.target.value)} className="rounded-lg border bg-background px-3 text-sm"><option value="all">كل الحالات</option><option value="active">نشط</option><option value="inactive">غير نشط</option><option value="blocked">محظور</option></select></div><div className="overflow-x-auto rounded-xl border bg-card"><table className="w-full min-w-[900px] text-sm"><thead className="text-muted-foreground"><tr><th className="p-3 text-right">الرمز / المورد</th><th className="text-right">الشركة والتواصل</th><th className="text-right">الفئة</th><th className="text-right">الرصيد</th><th className="text-right">الحالة</th><th /></tr></thead><tbody>{rows.map((s) => <tr key={s.id} className="border-t"><td className="p-3"><b>{s.name}</b><div className="text-xs text-muted-foreground">{s.supplierCode}</div></td><td>{s.company || "—"}<div className="text-xs text-muted-foreground">{s.phone || s.email || "—"}</div></td><td>{s.category || "—"}</td><td>{money.format(Number(s.balance ?? 0))}</td><td>{s.status ?? "active"}</td><td className="flex gap-1 p-2"><Button size="sm" variant="ghost" onClick={() => showProfile(s.id)}><Eye className="h-4 w-4" /></Button><Button size="sm" variant="ghost" onClick={() => setEditing(s)}>تعديل</Button><Button size="sm" variant="ghost" className="text-destructive" onClick={() => disable.mutate(s.id)}><Trash2 className="h-4 w-4" /></Button></td></tr>)}</tbody><TableTotalsFooter rows={rows} allRows={rows} labelColSpan={3} cells={[{ key: "balance", label: "الرصيد المستحق", value: (supplier) => Number(supplier.balance ?? 0), format: money.format }, { key: "status", label: "" }, { key: "actions", label: "" }]} /></table></div><SupplierForm item={editing} onClose={() => setEditing(null)} onSave={save.mutate} /><SupplierProfile profile={profile} onClose={() => setProfile(null)} /></div>;
}
function SupplierForm({ item, onClose, onSave }: any) { const [form, setForm] = useState(item); if (!item) return null; const field = (key: string, label: string, type = "text") => <label className="grid gap-1 text-sm"><span className="text-muted-foreground">{label}</span><input type={type} value={form[key] ?? ""} onChange={(e) => setForm((x: any) => ({ ...x, [key]: e.target.value }))} className="rounded-md border bg-background p-2" /></label>; return <Dialog open={!!item} onOpenChange={(v) => !v && onClose()}><DialogContent className="max-w-3xl" dir="rtl"><DialogHeader><DialogTitle>{item.id ? "تعديل المورد" : "مورد جديد"}</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-3">{field("name", "الاسم *")}{field("company", "الشركة")}{field("contactPerson", "جهة الاتصال")}{field("phone", "الهاتف")}{field("whatsapp", "واتساب")}{field("email", "البريد", "email")}{field("address", "العنوان")}{field("category", "الفئة")}{field("paymentTerms", "شروط الدفع")}{field("creditLimit", "الحد الائتماني", "number")}{field("openingBalance", "الرصيد الافتتاحي", "number")}<label className="grid gap-1 text-sm"><span className="text-muted-foreground">الحالة</span><select value={form.status ?? "active"} onChange={(e) => setForm((x: any) => ({ ...x, status: e.target.value }))} className="rounded-md border bg-background p-2"><option value="active">نشط</option><option value="inactive">غير نشط</option><option value="blocked">محظور</option></select></label></div><label className="grid gap-1 text-sm"><span className="text-muted-foreground">ملاحظات</span><textarea value={form.notes ?? ""} onChange={(e) => setForm((x: any) => ({ ...x, notes: e.target.value }))} className="rounded-md border bg-background p-2" /></label><DialogFooter><Button variant="outline" onClick={onClose}>إلغاء</Button><Button onClick={() => onSave(form)}>حفظ</Button></DialogFooter></DialogContent></Dialog>; }
function SupplierProfile({ profile, onClose }: any) { return <Dialog open={!!profile} onOpenChange={(v) => !v && onClose()}><DialogContent className="max-w-4xl" dir="rtl"><DialogHeader><DialogTitle>ملف المورد — {profile?.supplier?.name}</DialogTitle></DialogHeader><div className="grid grid-cols-3 gap-2"><Box title="الرصيد المستحق" value={money.format(profile?.outstandingBalance ?? 0)} /><Box title="الفواتير" value={String(profile?.invoices?.length ?? 0)} /><Box title="المدفوعات" value={String(profile?.payments?.length ?? 0)} /></div><h3 className="font-semibold">آخر فواتير الشراء</h3><div className="max-h-44 overflow-auto text-sm">{profile?.invoices?.map((i: any) => <div key={i.id} className="flex justify-between border-b p-2"><span>{i.invoice_no}</span><span>{money.format(Number(i.total))}</span><span>متبقي {money.format(Number(i.remaining_amount))}</span></div>)}</div><h3 className="font-semibold">المنتجات المرتبطة</h3><div className="max-h-32 overflow-auto text-sm">{profile?.products?.map((p: any) => <div key={p.id} className="flex justify-between border-b p-2"><span>{p.name_ar || p.name}</span><span>{money.format(Number(p.last_purchase_price))}</span><span>{p.supplier_sku || "—"}</span></div>)}</div><DialogFooter><Button onClick={onClose}>إغلاق</Button></DialogFooter></DialogContent></Dialog>; } function Box({ title, value }: any) { return <div className="rounded-lg bg-muted p-3"><p className="text-xs text-muted-foreground">{title}</p><b>{value}</b></div>; }
