import { date, index, integer, jsonb, numeric, pgTable, serial, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/pg-core";

/** External funding owed by the company; it is never sales revenue. */
export const companyLoansTable = pgTable("company_loans", {
  id: serial("id").primaryKey(), loanNo: varchar("loan_no", { length: 50 }).notNull().unique(),
  lenderName: text("lender_name").notNull(), lenderPhone: varchar("lender_phone", { length: 30 }),
  originalAmount: numeric("original_amount", { precision: 16, scale: 2 }).notNull(), totalRepaid: numeric("total_repaid", { precision: 16, scale: 2 }).notNull().default("0"), remainingAmount: numeric("remaining_amount", { precision: 16, scale: 2 }).notNull(),
  receivedDate: date("received_date").notNull(), agreementDate: date("agreement_date"), dueDate: date("due_date"), attachments: jsonb("attachments").$type<string[]>().notNull().default([]), paymentMethod: varchar("payment_method", { length: 20 }).notNull().default("cash"), referenceNo: varchar("reference_no", { length: 120 }), notes: text("notes"), status: varchar("status", { length: 24 }).notNull().default("pending"), receiptTransactionId: integer("receipt_transaction_id"), createdBy: integer("created_by"), createdByName: text("created_by_name").notNull().default(""), createdAt: timestamp("created_at").notNull().defaultNow(), updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (t) => ({ statusIdx: index("company_loans_status_idx").on(t.status, t.receivedDate), lenderIdx: index("company_loans_lender_idx").on(t.lenderName) }));

export const companyLoanRepaymentsTable = pgTable("company_loan_repayments", {
  id: serial("id").primaryKey(), loanId: integer("loan_id").notNull().references(() => companyLoansTable.id, { onDelete: "restrict" }), repaymentNo: varchar("repayment_no", { length: 50 }).notNull().unique(), paymentDate: date("payment_date").notNull(), amount: numeric("amount", { precision: 16, scale: 2 }).notNull(), cashAccountCode: varchar("cash_account_code", { length: 30 }), attachments: jsonb("attachments").$type<string[]>().notNull().default([]), idempotencyKey: varchar("idempotency_key", { length: 180 }), paymentMethod: varchar("payment_method", { length: 20 }).notNull().default("cash"), referenceNo: varchar("reference_no", { length: 120 }), notes: text("notes"), status: varchar("status", { length: 24 }).notNull().default("pending"), financialTransactionId: integer("financial_transaction_id"), createdBy: integer("created_by"), createdByName: text("created_by_name").notNull().default(""), createdAt: timestamp("created_at").notNull().defaultNow(), updatedAt: timestamp("updated_at").notNull().defaultNow(),
}, (t) => ({ loanIdx: index("company_loan_repayments_loan_idx").on(t.loanId, t.paymentDate), idempotencyIdx: uniqueIndex("company_loan_repayments_idempotency_key_idx").on(t.idempotencyKey) }));
